package com.ddas.sns.userphoto.dto;

import java.io.Serializable;

public class UserPhotoDto implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_photo.up_id
     *
     * @mbggenerated Sun Jul 03 12:15:21 CST 2016
     */
    private String upId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_photo.user_id
     *
     * @mbggenerated Sun Jul 03 12:15:21 CST 2016
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_photo.group_id
     *
     * @mbggenerated Sun Jul 03 12:15:21 CST 2016
     */
    private String groupId;

    private String groupName;//相册名称

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_photo.photo_description
     *
     * @mbggenerated Sun Jul 03 12:15:21 CST 2016
     */
    private String photoDescription;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_photo.photo_url
     *
     * @mbggenerated Sun Jul 03 12:15:21 CST 2016
     */
    private String photoUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_photo.thumbnailUrl
     *
     * @mbggenerated Sun Jul 03 12:15:21 CST 2016
     */
    private String thumbnailurl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_photo.created_time
     *
     * @mbggenerated Sun Jul 03 12:15:21 CST 2016
     */
    private String createdTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_photo.updated_time
     *
     * @mbggenerated Sun Jul 03 12:15:21 CST 2016
     */
    private String updatedTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table user_photo
     *
     * @mbggenerated Sun Jul 03 12:15:21 CST 2016
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_photo.up_id
     *
     * @return the value of user_photo.up_id
     *
     * @mbggenerated Sun Jul 03 12:15:21 CST 2016
     */
    public String getUpId() {
        return upId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_photo.up_id
     *
     * @param upId the value for user_photo.up_id
     *
     * @mbggenerated Sun Jul 03 12:15:21 CST 2016
     */
    public void setUpId(String upId) {
        this.upId = upId == null ? null : upId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_photo.user_id
     *
     * @return the value of user_photo.user_id
     *
     * @mbggenerated Sun Jul 03 12:15:21 CST 2016
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_photo.user_id
     *
     * @param userId the value for user_photo.user_id
     *
     * @mbggenerated Sun Jul 03 12:15:21 CST 2016
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_photo.group_id
     *
     * @return the value of user_photo.group_id
     *
     * @mbggenerated Sun Jul 03 12:15:21 CST 2016
     */
    public String getGroupId() {
        return groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_photo.group_id
     *
     * @param groupId the value for user_photo.group_id
     *
     * @mbggenerated Sun Jul 03 12:15:21 CST 2016
     */
    public void setGroupId(String groupId) {
        this.groupId = groupId == null ? null : groupId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_photo.photo_description
     *
     * @return the value of user_photo.photo_description
     *
     * @mbggenerated Sun Jul 03 12:15:21 CST 2016
     */
    public String getPhotoDescription() {
        return photoDescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_photo.photo_description
     *
     * @param photoDescription the value for user_photo.photo_description
     *
     * @mbggenerated Sun Jul 03 12:15:21 CST 2016
     */
    public void setPhotoDescription(String photoDescription) {
        this.photoDescription = photoDescription == null ? null : photoDescription.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_photo.photo_url
     *
     * @return the value of user_photo.photo_url
     *
     * @mbggenerated Sun Jul 03 12:15:21 CST 2016
     */
    public String getPhotoUrl() {
        return photoUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_photo.photo_url
     *
     * @param photoUrl the value for user_photo.photo_url
     *
     * @mbggenerated Sun Jul 03 12:15:21 CST 2016
     */
    public void setPhotoUrl(String photoUrl) {
        this.photoUrl = photoUrl == null ? null : photoUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_photo.thumbnailUrl
     *
     * @return the value of user_photo.thumbnailUrl
     *
     * @mbggenerated Sun Jul 03 12:15:21 CST 2016
     */
    public String getThumbnailurl() {
        return thumbnailurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_photo.thumbnailUrl
     *
     * @param thumbnailurl the value for user_photo.thumbnailUrl
     *
     * @mbggenerated Sun Jul 03 12:15:21 CST 2016
     */
    public void setThumbnailurl(String thumbnailurl) {
        this.thumbnailurl = thumbnailurl == null ? null : thumbnailurl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_photo.created_time
     *
     * @return the value of user_photo.created_time
     *
     * @mbggenerated Sun Jul 03 12:15:21 CST 2016
     */
    public String getCreatedTime() {
        return createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_photo.created_time
     *
     * @param createdTime the value for user_photo.created_time
     *
     * @mbggenerated Sun Jul 03 12:15:21 CST 2016
     */
    public void setCreatedTime(String createdTime) {
        this.createdTime = createdTime == null ? null : createdTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_photo.updated_time
     *
     * @return the value of user_photo.updated_time
     *
     * @mbggenerated Sun Jul 03 12:15:21 CST 2016
     */
    public String getUpdatedTime() {
        return updatedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_photo.updated_time
     *
     * @param updatedTime the value for user_photo.updated_time
     *
     * @mbggenerated Sun Jul 03 12:15:21 CST 2016
     */
    public void setUpdatedTime(String updatedTime) {
        this.updatedTime = updatedTime == null ? null : updatedTime.trim();
    }

    public String getGroupName() {
        return groupName;
    }

    public void setGroupName(String groupName) {
        this.groupName = groupName;
    }
}