package com.ddas.sns.gift.domain;

import java.util.ArrayList;
import java.util.List;

public class UserGiftCriteria {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table user_gift
     *
     * @mbggenerated Tue Aug 09 22:22:17 CST 2016
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table user_gift
     *
     * @mbggenerated Tue Aug 09 22:22:17 CST 2016
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table user_gift
     *
     * @mbggenerated Tue Aug 09 22:22:17 CST 2016
     */
    protected List<Criteria> oredCriteria;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table user_gift
     *
     * @mbggenerated Tue Aug 09 22:22:17 CST 2016
     */
    protected int limitStart = -1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table user_gift
     *
     * @mbggenerated Tue Aug 09 22:22:17 CST 2016
     */
    protected int limitEnd = -1;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_gift
     *
     * @mbggenerated Tue Aug 09 22:22:17 CST 2016
     */
    public UserGiftCriteria() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_gift
     *
     * @mbggenerated Tue Aug 09 22:22:17 CST 2016
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_gift
     *
     * @mbggenerated Tue Aug 09 22:22:17 CST 2016
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_gift
     *
     * @mbggenerated Tue Aug 09 22:22:17 CST 2016
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_gift
     *
     * @mbggenerated Tue Aug 09 22:22:17 CST 2016
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_gift
     *
     * @mbggenerated Tue Aug 09 22:22:17 CST 2016
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_gift
     *
     * @mbggenerated Tue Aug 09 22:22:17 CST 2016
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_gift
     *
     * @mbggenerated Tue Aug 09 22:22:17 CST 2016
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_gift
     *
     * @mbggenerated Tue Aug 09 22:22:17 CST 2016
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_gift
     *
     * @mbggenerated Tue Aug 09 22:22:17 CST 2016
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_gift
     *
     * @mbggenerated Tue Aug 09 22:22:17 CST 2016
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_gift
     *
     * @mbggenerated Tue Aug 09 22:22:17 CST 2016
     */
    public void setLimitStart(int limitStart) {
        this.limitStart=limitStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_gift
     *
     * @mbggenerated Tue Aug 09 22:22:17 CST 2016
     */
    public int getLimitStart() {
        return limitStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_gift
     *
     * @mbggenerated Tue Aug 09 22:22:17 CST 2016
     */
    public void setLimitEnd(int limitEnd) {
        this.limitEnd=limitEnd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_gift
     *
     * @mbggenerated Tue Aug 09 22:22:17 CST 2016
     */
    public int getLimitEnd() {
        return limitEnd;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table user_gift
     *
     * @mbggenerated Tue Aug 09 22:22:17 CST 2016
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andUgIdIsNull() {
            addCriterion("ug_id is null");
            return (Criteria) this;
        }

        public Criteria andUgIdIsNotNull() {
            addCriterion("ug_id is not null");
            return (Criteria) this;
        }

        public Criteria andUgIdEqualTo(String value) {
            addCriterion("ug_id =", value, "ugId");
            return (Criteria) this;
        }

        public Criteria andUgIdNotEqualTo(String value) {
            addCriterion("ug_id <>", value, "ugId");
            return (Criteria) this;
        }

        public Criteria andUgIdGreaterThan(String value) {
            addCriterion("ug_id >", value, "ugId");
            return (Criteria) this;
        }

        public Criteria andUgIdGreaterThanOrEqualTo(String value) {
            addCriterion("ug_id >=", value, "ugId");
            return (Criteria) this;
        }

        public Criteria andUgIdLessThan(String value) {
            addCriterion("ug_id <", value, "ugId");
            return (Criteria) this;
        }

        public Criteria andUgIdLessThanOrEqualTo(String value) {
            addCriterion("ug_id <=", value, "ugId");
            return (Criteria) this;
        }

        public Criteria andUgIdLike(String value) {
            addCriterion("ug_id like", value, "ugId");
            return (Criteria) this;
        }

        public Criteria andUgIdNotLike(String value) {
            addCriterion("ug_id not like", value, "ugId");
            return (Criteria) this;
        }

        public Criteria andUgIdIn(List<String> values) {
            addCriterion("ug_id in", values, "ugId");
            return (Criteria) this;
        }

        public Criteria andUgIdNotIn(List<String> values) {
            addCriterion("ug_id not in", values, "ugId");
            return (Criteria) this;
        }

        public Criteria andUgIdBetween(String value1, String value2) {
            addCriterion("ug_id between", value1, value2, "ugId");
            return (Criteria) this;
        }

        public Criteria andUgIdNotBetween(String value1, String value2) {
            addCriterion("ug_id not between", value1, value2, "ugId");
            return (Criteria) this;
        }

        public Criteria andGiftSenderIsNull() {
            addCriterion("gift_sender is null");
            return (Criteria) this;
        }

        public Criteria andGiftSenderIsNotNull() {
            addCriterion("gift_sender is not null");
            return (Criteria) this;
        }

        public Criteria andGiftSenderEqualTo(String value) {
            addCriterion("gift_sender =", value, "giftSender");
            return (Criteria) this;
        }

        public Criteria andGiftSenderNotEqualTo(String value) {
            addCriterion("gift_sender <>", value, "giftSender");
            return (Criteria) this;
        }

        public Criteria andGiftSenderGreaterThan(String value) {
            addCriterion("gift_sender >", value, "giftSender");
            return (Criteria) this;
        }

        public Criteria andGiftSenderGreaterThanOrEqualTo(String value) {
            addCriterion("gift_sender >=", value, "giftSender");
            return (Criteria) this;
        }

        public Criteria andGiftSenderLessThan(String value) {
            addCriterion("gift_sender <", value, "giftSender");
            return (Criteria) this;
        }

        public Criteria andGiftSenderLessThanOrEqualTo(String value) {
            addCriterion("gift_sender <=", value, "giftSender");
            return (Criteria) this;
        }

        public Criteria andGiftSenderLike(String value) {
            addCriterion("gift_sender like", value, "giftSender");
            return (Criteria) this;
        }

        public Criteria andGiftSenderNotLike(String value) {
            addCriterion("gift_sender not like", value, "giftSender");
            return (Criteria) this;
        }

        public Criteria andGiftSenderIn(List<String> values) {
            addCriterion("gift_sender in", values, "giftSender");
            return (Criteria) this;
        }

        public Criteria andGiftSenderNotIn(List<String> values) {
            addCriterion("gift_sender not in", values, "giftSender");
            return (Criteria) this;
        }

        public Criteria andGiftSenderBetween(String value1, String value2) {
            addCriterion("gift_sender between", value1, value2, "giftSender");
            return (Criteria) this;
        }

        public Criteria andGiftSenderNotBetween(String value1, String value2) {
            addCriterion("gift_sender not between", value1, value2, "giftSender");
            return (Criteria) this;
        }

        public Criteria andGiftReceiverIsNull() {
            addCriterion("gift_receiver is null");
            return (Criteria) this;
        }

        public Criteria andGiftReceiverIsNotNull() {
            addCriterion("gift_receiver is not null");
            return (Criteria) this;
        }

        public Criteria andGiftReceiverEqualTo(String value) {
            addCriterion("gift_receiver =", value, "giftReceiver");
            return (Criteria) this;
        }

        public Criteria andGiftReceiverNotEqualTo(String value) {
            addCriterion("gift_receiver <>", value, "giftReceiver");
            return (Criteria) this;
        }

        public Criteria andGiftReceiverGreaterThan(String value) {
            addCriterion("gift_receiver >", value, "giftReceiver");
            return (Criteria) this;
        }

        public Criteria andGiftReceiverGreaterThanOrEqualTo(String value) {
            addCriterion("gift_receiver >=", value, "giftReceiver");
            return (Criteria) this;
        }

        public Criteria andGiftReceiverLessThan(String value) {
            addCriterion("gift_receiver <", value, "giftReceiver");
            return (Criteria) this;
        }

        public Criteria andGiftReceiverLessThanOrEqualTo(String value) {
            addCriterion("gift_receiver <=", value, "giftReceiver");
            return (Criteria) this;
        }

        public Criteria andGiftReceiverLike(String value) {
            addCriterion("gift_receiver like", value, "giftReceiver");
            return (Criteria) this;
        }

        public Criteria andGiftReceiverNotLike(String value) {
            addCriterion("gift_receiver not like", value, "giftReceiver");
            return (Criteria) this;
        }

        public Criteria andGiftReceiverIn(List<String> values) {
            addCriterion("gift_receiver in", values, "giftReceiver");
            return (Criteria) this;
        }

        public Criteria andGiftReceiverNotIn(List<String> values) {
            addCriterion("gift_receiver not in", values, "giftReceiver");
            return (Criteria) this;
        }

        public Criteria andGiftReceiverBetween(String value1, String value2) {
            addCriterion("gift_receiver between", value1, value2, "giftReceiver");
            return (Criteria) this;
        }

        public Criteria andGiftReceiverNotBetween(String value1, String value2) {
            addCriterion("gift_receiver not between", value1, value2, "giftReceiver");
            return (Criteria) this;
        }

        public Criteria andGiftCountIsNull() {
            addCriterion("gift_count is null");
            return (Criteria) this;
        }

        public Criteria andGiftCountIsNotNull() {
            addCriterion("gift_count is not null");
            return (Criteria) this;
        }

        public Criteria andGiftCountEqualTo(String value) {
            addCriterion("gift_count =", value, "giftCount");
            return (Criteria) this;
        }

        public Criteria andGiftCountNotEqualTo(String value) {
            addCriterion("gift_count <>", value, "giftCount");
            return (Criteria) this;
        }

        public Criteria andGiftCountGreaterThan(String value) {
            addCriterion("gift_count >", value, "giftCount");
            return (Criteria) this;
        }

        public Criteria andGiftCountGreaterThanOrEqualTo(String value) {
            addCriterion("gift_count >=", value, "giftCount");
            return (Criteria) this;
        }

        public Criteria andGiftCountLessThan(String value) {
            addCriterion("gift_count <", value, "giftCount");
            return (Criteria) this;
        }

        public Criteria andGiftCountLessThanOrEqualTo(String value) {
            addCriterion("gift_count <=", value, "giftCount");
            return (Criteria) this;
        }

        public Criteria andGiftCountLike(String value) {
            addCriterion("gift_count like", value, "giftCount");
            return (Criteria) this;
        }

        public Criteria andGiftCountNotLike(String value) {
            addCriterion("gift_count not like", value, "giftCount");
            return (Criteria) this;
        }

        public Criteria andGiftCountIn(List<String> values) {
            addCriterion("gift_count in", values, "giftCount");
            return (Criteria) this;
        }

        public Criteria andGiftCountNotIn(List<String> values) {
            addCriterion("gift_count not in", values, "giftCount");
            return (Criteria) this;
        }

        public Criteria andGiftCountBetween(String value1, String value2) {
            addCriterion("gift_count between", value1, value2, "giftCount");
            return (Criteria) this;
        }

        public Criteria andGiftCountNotBetween(String value1, String value2) {
            addCriterion("gift_count not between", value1, value2, "giftCount");
            return (Criteria) this;
        }

        public Criteria andGiftIdIsNull() {
            addCriterion("gift_id is null");
            return (Criteria) this;
        }

        public Criteria andGiftIdIsNotNull() {
            addCriterion("gift_id is not null");
            return (Criteria) this;
        }

        public Criteria andGiftIdEqualTo(String value) {
            addCriterion("gift_id =", value, "giftId");
            return (Criteria) this;
        }

        public Criteria andGiftIdNotEqualTo(String value) {
            addCriterion("gift_id <>", value, "giftId");
            return (Criteria) this;
        }

        public Criteria andGiftIdGreaterThan(String value) {
            addCriterion("gift_id >", value, "giftId");
            return (Criteria) this;
        }

        public Criteria andGiftIdGreaterThanOrEqualTo(String value) {
            addCriterion("gift_id >=", value, "giftId");
            return (Criteria) this;
        }

        public Criteria andGiftIdLessThan(String value) {
            addCriterion("gift_id <", value, "giftId");
            return (Criteria) this;
        }

        public Criteria andGiftIdLessThanOrEqualTo(String value) {
            addCriterion("gift_id <=", value, "giftId");
            return (Criteria) this;
        }

        public Criteria andGiftIdLike(String value) {
            addCriterion("gift_id like", value, "giftId");
            return (Criteria) this;
        }

        public Criteria andGiftIdNotLike(String value) {
            addCriterion("gift_id not like", value, "giftId");
            return (Criteria) this;
        }

        public Criteria andGiftIdIn(List<String> values) {
            addCriterion("gift_id in", values, "giftId");
            return (Criteria) this;
        }

        public Criteria andGiftIdNotIn(List<String> values) {
            addCriterion("gift_id not in", values, "giftId");
            return (Criteria) this;
        }

        public Criteria andGiftIdBetween(String value1, String value2) {
            addCriterion("gift_id between", value1, value2, "giftId");
            return (Criteria) this;
        }

        public Criteria andGiftIdNotBetween(String value1, String value2) {
            addCriterion("gift_id not between", value1, value2, "giftId");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeIsNull() {
            addCriterion("created_time is null");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeIsNotNull() {
            addCriterion("created_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeEqualTo(String value) {
            addCriterion("created_time =", value, "createdTime");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeNotEqualTo(String value) {
            addCriterion("created_time <>", value, "createdTime");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeGreaterThan(String value) {
            addCriterion("created_time >", value, "createdTime");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeGreaterThanOrEqualTo(String value) {
            addCriterion("created_time >=", value, "createdTime");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeLessThan(String value) {
            addCriterion("created_time <", value, "createdTime");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeLessThanOrEqualTo(String value) {
            addCriterion("created_time <=", value, "createdTime");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeLike(String value) {
            addCriterion("created_time like", value, "createdTime");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeNotLike(String value) {
            addCriterion("created_time not like", value, "createdTime");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeIn(List<String> values) {
            addCriterion("created_time in", values, "createdTime");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeNotIn(List<String> values) {
            addCriterion("created_time not in", values, "createdTime");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeBetween(String value1, String value2) {
            addCriterion("created_time between", value1, value2, "createdTime");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeNotBetween(String value1, String value2) {
            addCriterion("created_time not between", value1, value2, "createdTime");
            return (Criteria) this;
        }

        public Criteria andUpdatedTimeIsNull() {
            addCriterion("updated_time is null");
            return (Criteria) this;
        }

        public Criteria andUpdatedTimeIsNotNull() {
            addCriterion("updated_time is not null");
            return (Criteria) this;
        }

        public Criteria andUpdatedTimeEqualTo(String value) {
            addCriterion("updated_time =", value, "updatedTime");
            return (Criteria) this;
        }

        public Criteria andUpdatedTimeNotEqualTo(String value) {
            addCriterion("updated_time <>", value, "updatedTime");
            return (Criteria) this;
        }

        public Criteria andUpdatedTimeGreaterThan(String value) {
            addCriterion("updated_time >", value, "updatedTime");
            return (Criteria) this;
        }

        public Criteria andUpdatedTimeGreaterThanOrEqualTo(String value) {
            addCriterion("updated_time >=", value, "updatedTime");
            return (Criteria) this;
        }

        public Criteria andUpdatedTimeLessThan(String value) {
            addCriterion("updated_time <", value, "updatedTime");
            return (Criteria) this;
        }

        public Criteria andUpdatedTimeLessThanOrEqualTo(String value) {
            addCriterion("updated_time <=", value, "updatedTime");
            return (Criteria) this;
        }

        public Criteria andUpdatedTimeLike(String value) {
            addCriterion("updated_time like", value, "updatedTime");
            return (Criteria) this;
        }

        public Criteria andUpdatedTimeNotLike(String value) {
            addCriterion("updated_time not like", value, "updatedTime");
            return (Criteria) this;
        }

        public Criteria andUpdatedTimeIn(List<String> values) {
            addCriterion("updated_time in", values, "updatedTime");
            return (Criteria) this;
        }

        public Criteria andUpdatedTimeNotIn(List<String> values) {
            addCriterion("updated_time not in", values, "updatedTime");
            return (Criteria) this;
        }

        public Criteria andUpdatedTimeBetween(String value1, String value2) {
            addCriterion("updated_time between", value1, value2, "updatedTime");
            return (Criteria) this;
        }

        public Criteria andUpdatedTimeNotBetween(String value1, String value2) {
            addCriterion("updated_time not between", value1, value2, "updatedTime");
            return (Criteria) this;
        }

        public Criteria andGiftTotalPriceIsNull() {
            addCriterion("gift_total_price is null");
            return (Criteria) this;
        }

        public Criteria andGiftTotalPriceIsNotNull() {
            addCriterion("gift_total_price is not null");
            return (Criteria) this;
        }

        public Criteria andGiftTotalPriceEqualTo(String value) {
            addCriterion("gift_total_price =", value, "giftTotalPrice");
            return (Criteria) this;
        }

        public Criteria andGiftTotalPriceNotEqualTo(String value) {
            addCriterion("gift_total_price <>", value, "giftTotalPrice");
            return (Criteria) this;
        }

        public Criteria andGiftTotalPriceGreaterThan(String value) {
            addCriterion("gift_total_price >", value, "giftTotalPrice");
            return (Criteria) this;
        }

        public Criteria andGiftTotalPriceGreaterThanOrEqualTo(String value) {
            addCriterion("gift_total_price >=", value, "giftTotalPrice");
            return (Criteria) this;
        }

        public Criteria andGiftTotalPriceLessThan(String value) {
            addCriterion("gift_total_price <", value, "giftTotalPrice");
            return (Criteria) this;
        }

        public Criteria andGiftTotalPriceLessThanOrEqualTo(String value) {
            addCriterion("gift_total_price <=", value, "giftTotalPrice");
            return (Criteria) this;
        }

        public Criteria andGiftTotalPriceLike(String value) {
            addCriterion("gift_total_price like", value, "giftTotalPrice");
            return (Criteria) this;
        }

        public Criteria andGiftTotalPriceNotLike(String value) {
            addCriterion("gift_total_price not like", value, "giftTotalPrice");
            return (Criteria) this;
        }

        public Criteria andGiftTotalPriceIn(List<String> values) {
            addCriterion("gift_total_price in", values, "giftTotalPrice");
            return (Criteria) this;
        }

        public Criteria andGiftTotalPriceNotIn(List<String> values) {
            addCriterion("gift_total_price not in", values, "giftTotalPrice");
            return (Criteria) this;
        }

        public Criteria andGiftTotalPriceBetween(String value1, String value2) {
            addCriterion("gift_total_price between", value1, value2, "giftTotalPrice");
            return (Criteria) this;
        }

        public Criteria andGiftTotalPriceNotBetween(String value1, String value2) {
            addCriterion("gift_total_price not between", value1, value2, "giftTotalPrice");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table user_gift
     *
     * @mbggenerated do_not_delete_during_merge Tue Aug 09 22:22:17 CST 2016
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }

        public Criteria andUgIdLikeInsensitive(String value) {
            addCriterion("upper(ug_id) like", value.toUpperCase(), "ugId");
            return this;
        }

        public Criteria andGiftSenderLikeInsensitive(String value) {
            addCriterion("upper(gift_sender) like", value.toUpperCase(), "giftSender");
            return this;
        }

        public Criteria andGiftReceiverLikeInsensitive(String value) {
            addCriterion("upper(gift_receiver) like", value.toUpperCase(), "giftReceiver");
            return this;
        }

        public Criteria andGiftCountLikeInsensitive(String value) {
            addCriterion("upper(gift_count) like", value.toUpperCase(), "giftCount");
            return this;
        }

        public Criteria andGiftIdLikeInsensitive(String value) {
            addCriterion("upper(gift_id) like", value.toUpperCase(), "giftId");
            return this;
        }

        public Criteria andCreatedTimeLikeInsensitive(String value) {
            addCriterion("upper(created_time) like", value.toUpperCase(), "createdTime");
            return this;
        }

        public Criteria andUpdatedTimeLikeInsensitive(String value) {
            addCriterion("upper(updated_time) like", value.toUpperCase(), "updatedTime");
            return this;
        }

        public Criteria andGiftTotalPriceLikeInsensitive(String value) {
            addCriterion("upper(gift_total_price) like", value.toUpperCase(), "giftTotalPrice");
            return this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table user_gift
     *
     * @mbggenerated Tue Aug 09 22:22:17 CST 2016
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}