package com.ddas.sns.userfriend.domain;

import java.io.Serializable;

public class UserFriend implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_friend.uf_id
     *
     * @mbggenerated Sun Jul 31 14:19:54 CST 2016
     */
    private String ufId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_friend.user_id
     *
     * @mbggenerated Sun Jul 31 14:19:54 CST 2016
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_friend.friend_id
     *
     * @mbggenerated Sun Jul 31 14:19:54 CST 2016
     */
    private String friendId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_friend.friend_name
     *
     * @mbggenerated Sun Jul 31 14:19:54 CST 2016
     */
    private String friendName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_friend.group_id
     *
     * @mbggenerated Sun Jul 31 14:19:54 CST 2016
     */
    private String groupId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_friend.status
     *
     * @mbggenerated Sun Jul 31 14:19:54 CST 2016
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_friend.created_time
     *
     * @mbggenerated Sun Jul 31 14:19:54 CST 2016
     */
    private String createdTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_friend.updated_time
     *
     * @mbggenerated Sun Jul 31 14:19:54 CST 2016
     */
    private String updatedTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table user_friend
     *
     * @mbggenerated Sun Jul 31 14:19:54 CST 2016
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_friend.uf_id
     *
     * @return the value of user_friend.uf_id
     *
     * @mbggenerated Sun Jul 31 14:19:54 CST 2016
     */
    public String getUfId() {
        return ufId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_friend.uf_id
     *
     * @param ufId the value for user_friend.uf_id
     *
     * @mbggenerated Sun Jul 31 14:19:54 CST 2016
     */
    public void setUfId(String ufId) {
        this.ufId = ufId == null ? null : ufId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_friend.user_id
     *
     * @return the value of user_friend.user_id
     *
     * @mbggenerated Sun Jul 31 14:19:54 CST 2016
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_friend.user_id
     *
     * @param userId the value for user_friend.user_id
     *
     * @mbggenerated Sun Jul 31 14:19:54 CST 2016
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_friend.friend_id
     *
     * @return the value of user_friend.friend_id
     *
     * @mbggenerated Sun Jul 31 14:19:54 CST 2016
     */
    public String getFriendId() {
        return friendId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_friend.friend_id
     *
     * @param friendId the value for user_friend.friend_id
     *
     * @mbggenerated Sun Jul 31 14:19:54 CST 2016
     */
    public void setFriendId(String friendId) {
        this.friendId = friendId == null ? null : friendId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_friend.friend_name
     *
     * @return the value of user_friend.friend_name
     *
     * @mbggenerated Sun Jul 31 14:19:54 CST 2016
     */
    public String getFriendName() {
        return friendName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_friend.friend_name
     *
     * @param friendName the value for user_friend.friend_name
     *
     * @mbggenerated Sun Jul 31 14:19:54 CST 2016
     */
    public void setFriendName(String friendName) {
        this.friendName = friendName == null ? null : friendName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_friend.group_id
     *
     * @return the value of user_friend.group_id
     *
     * @mbggenerated Sun Jul 31 14:19:54 CST 2016
     */
    public String getGroupId() {
        return groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_friend.group_id
     *
     * @param groupId the value for user_friend.group_id
     *
     * @mbggenerated Sun Jul 31 14:19:54 CST 2016
     */
    public void setGroupId(String groupId) {
        this.groupId = groupId == null ? null : groupId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_friend.status
     *
     * @return the value of user_friend.status
     *
     * @mbggenerated Sun Jul 31 14:19:54 CST 2016
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_friend.status
     *
     * @param status the value for user_friend.status
     *
     * @mbggenerated Sun Jul 31 14:19:54 CST 2016
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_friend.created_time
     *
     * @return the value of user_friend.created_time
     *
     * @mbggenerated Sun Jul 31 14:19:54 CST 2016
     */
    public String getCreatedTime() {
        return createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_friend.created_time
     *
     * @param createdTime the value for user_friend.created_time
     *
     * @mbggenerated Sun Jul 31 14:19:54 CST 2016
     */
    public void setCreatedTime(String createdTime) {
        this.createdTime = createdTime == null ? null : createdTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_friend.updated_time
     *
     * @return the value of user_friend.updated_time
     *
     * @mbggenerated Sun Jul 31 14:19:54 CST 2016
     */
    public String getUpdatedTime() {
        return updatedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_friend.updated_time
     *
     * @param updatedTime the value for user_friend.updated_time
     *
     * @mbggenerated Sun Jul 31 14:19:54 CST 2016
     */
    public void setUpdatedTime(String updatedTime) {
        this.updatedTime = updatedTime == null ? null : updatedTime.trim();
    }
}