package com.ddas.sns.userrechargerecords.mapper;

import com.ddas.sns.admin.dto.UserRechargeRecordDto;
import com.ddas.sns.userrechargerecords.domain.UserRechargeRecord;
import com.ddas.sns.userrechargerecords.domain.UserRechargeRecordCriteria;
import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

public interface UserRechargeRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_recharge_records
     *
     * @mbggenerated Thu Sep 15 16:15:26 CST 2016
     */
    int countByExample(UserRechargeRecordCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_recharge_records
     *
     * @mbggenerated Thu Sep 15 16:15:26 CST 2016
     */
    int deleteByExample(UserRechargeRecordCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_recharge_records
     *
     * @mbggenerated Thu Sep 15 16:15:26 CST 2016
     */
    int deleteByPrimaryKey(String urId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_recharge_records
     *
     * @mbggenerated Thu Sep 15 16:15:26 CST 2016
     */
    int insert(UserRechargeRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_recharge_records
     *
     * @mbggenerated Thu Sep 15 16:15:26 CST 2016
     */
    int insertSelective(UserRechargeRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_recharge_records
     *
     * @mbggenerated Thu Sep 15 16:15:26 CST 2016
     */
    List<UserRechargeRecord> selectByExample(UserRechargeRecordCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_recharge_records
     *
     * @mbggenerated Thu Sep 15 16:15:26 CST 2016
     */
    UserRechargeRecord selectByPrimaryKey(String urId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_recharge_records
     *
     * @mbggenerated Thu Sep 15 16:15:26 CST 2016
     */
    int updateByExampleSelective(@Param("record") UserRechargeRecord record, @Param("example") UserRechargeRecordCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_recharge_records
     *
     * @mbggenerated Thu Sep 15 16:15:26 CST 2016
     */
    int updateByExample(@Param("record") UserRechargeRecord record, @Param("example") UserRechargeRecordCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_recharge_records
     *
     * @mbggenerated Thu Sep 15 16:15:26 CST 2016
     */
    int updateByPrimaryKeySelective(UserRechargeRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_recharge_records
     *
     * @mbggenerated Thu Sep 15 16:15:26 CST 2016
     */
    int updateByPrimaryKey(UserRechargeRecord record);

    int countAllRecords(Map<String, Object> queryParams);

    List<UserRechargeRecordDto> selectAllRecords(Map<String, Object> queryParams);

}