package com.ddas.sns.userfriendgift.mapper;

import com.ddas.common.page.Page;
import com.ddas.sns.userfriendgift.dto.UserFriendGiftDto;

import java.util.List;

public interface UserFriendGiftMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_friend
     *
     * @mbggenerated Thu Jul 07 15:08:48 CST 2016
     */
    public int getCount(Page page);
    public List<UserFriendGiftDto> queryByPage(Page page);
}