package com.ddas.sns.usermessage.mapper;

import com.ddas.sns.usermessage.domain.UserMessage;
import com.ddas.sns.usermessage.domain.UserMessageCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UserMessageMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_message
     *
     * @mbggenerated Mon Jul 11 21:52:52 CST 2016
     */
    int countByExample(UserMessageCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_message
     *
     * @mbggenerated Mon Jul 11 21:52:52 CST 2016
     */
    int deleteByExample(UserMessageCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_message
     *
     * @mbggenerated Mon Jul 11 21:52:52 CST 2016
     */
    int insert(UserMessage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_message
     *
     * @mbggenerated Mon Jul 11 21:52:52 CST 2016
     */
    int insertSelective(UserMessage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_message
     *
     * @mbggenerated Mon Jul 11 21:52:52 CST 2016
     */
    List<UserMessage> selectByExample(UserMessageCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_message
     *
     * @mbggenerated Mon Jul 11 21:52:52 CST 2016
     */
    int updateByExampleSelective(@Param("record") UserMessage record, @Param("example") UserMessageCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_message
     *
     * @mbggenerated Mon Jul 11 21:52:52 CST 2016
     */
    int updateByExample(@Param("record") UserMessage record, @Param("example") UserMessageCriteria example);
}