package com.ddas.sns.image.mapper;

import com.ddas.sns.image.domain.ImageInfo;
import com.ddas.sns.image.domain.ImageInfoCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ImageInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table image_info
     *
     * @mbggenerated Mon Dec 12 21:26:57 CST 2016
     */
    int countByExample(ImageInfoCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table image_info
     *
     * @mbggenerated Mon Dec 12 21:26:57 CST 2016
     */
    int deleteByExample(ImageInfoCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table image_info
     *
     * @mbggenerated Mon Dec 12 21:26:57 CST 2016
     */
    int deleteByPrimaryKey(String zoimId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table image_info
     *
     * @mbggenerated Mon Dec 12 21:26:57 CST 2016
     */
    int insert(ImageInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table image_info
     *
     * @mbggenerated Mon Dec 12 21:26:57 CST 2016
     */
    int insertSelective(ImageInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table image_info
     *
     * @mbggenerated Mon Dec 12 21:26:57 CST 2016
     */
    List<ImageInfo> selectByExample(ImageInfoCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table image_info
     *
     * @mbggenerated Mon Dec 12 21:26:57 CST 2016
     */
    ImageInfo selectByPrimaryKey(String zoimId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table image_info
     *
     * @mbggenerated Mon Dec 12 21:26:57 CST 2016
     */
    int updateByExampleSelective(@Param("record") ImageInfo record, @Param("example") ImageInfoCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table image_info
     *
     * @mbggenerated Mon Dec 12 21:26:57 CST 2016
     */
    int updateByExample(@Param("record") ImageInfo record, @Param("example") ImageInfoCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table image_info
     *
     * @mbggenerated Mon Dec 12 21:26:57 CST 2016
     */
    int updateByPrimaryKeySelective(ImageInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table image_info
     *
     * @mbggenerated Mon Dec 12 21:26:57 CST 2016
     */
    int updateByPrimaryKey(ImageInfo record);
}