package com.ddas.sns.zoneccomment.domain;

import java.io.Serializable;

public class ZoneComment implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zone_comment.zoco_id
     *
     * @mbggenerated Wed Dec 14 21:38:06 CST 2016
     */
    private String zocoId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zone_comment.zoco_gagaid
     *
     * @mbggenerated Wed Dec 14 21:38:06 CST 2016
     */
    private String zocoGagaid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zone_comment.zoco_content
     *
     * @mbggenerated Wed Dec 14 21:38:06 CST 2016
     */
    private String zocoContent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zone_comment.zoco_zoneid
     *
     * @mbggenerated Wed Dec 14 21:38:06 CST 2016
     */
    private String zocoZoneid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zone_comment.zoco_state
     *
     * @mbggenerated Wed Dec 14 21:38:06 CST 2016
     */
    private String zocoState;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zone_comment.zoco_time
     *
     * @mbggenerated Wed Dec 14 21:38:06 CST 2016
     */
    private String zocoTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zone_comment.zoco_parentid
     *
     * @mbggenerated Wed Dec 14 21:38:06 CST 2016
     */
    private String zocoParentid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table zone_comment
     *
     * @mbggenerated Wed Dec 14 21:38:06 CST 2016
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zone_comment.zoco_id
     *
     * @return the value of zone_comment.zoco_id
     *
     * @mbggenerated Wed Dec 14 21:38:06 CST 2016
     */
    public String getZocoId() {
        return zocoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zone_comment.zoco_id
     *
     * @param zocoId the value for zone_comment.zoco_id
     *
     * @mbggenerated Wed Dec 14 21:38:06 CST 2016
     */
    public void setZocoId(String zocoId) {
        this.zocoId = zocoId == null ? null : zocoId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zone_comment.zoco_gagaid
     *
     * @return the value of zone_comment.zoco_gagaid
     *
     * @mbggenerated Wed Dec 14 21:38:06 CST 2016
     */
    public String getZocoGagaid() {
        return zocoGagaid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zone_comment.zoco_gagaid
     *
     * @param zocoGagaid the value for zone_comment.zoco_gagaid
     *
     * @mbggenerated Wed Dec 14 21:38:06 CST 2016
     */
    public void setZocoGagaid(String zocoGagaid) {
        this.zocoGagaid = zocoGagaid == null ? null : zocoGagaid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zone_comment.zoco_content
     *
     * @return the value of zone_comment.zoco_content
     *
     * @mbggenerated Wed Dec 14 21:38:06 CST 2016
     */
    public String getZocoContent() {
        return zocoContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zone_comment.zoco_content
     *
     * @param zocoContent the value for zone_comment.zoco_content
     *
     * @mbggenerated Wed Dec 14 21:38:06 CST 2016
     */
    public void setZocoContent(String zocoContent) {
        this.zocoContent = zocoContent == null ? null : zocoContent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zone_comment.zoco_zoneid
     *
     * @return the value of zone_comment.zoco_zoneid
     *
     * @mbggenerated Wed Dec 14 21:38:06 CST 2016
     */
    public String getZocoZoneid() {
        return zocoZoneid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zone_comment.zoco_zoneid
     *
     * @param zocoZoneid the value for zone_comment.zoco_zoneid
     *
     * @mbggenerated Wed Dec 14 21:38:06 CST 2016
     */
    public void setZocoZoneid(String zocoZoneid) {
        this.zocoZoneid = zocoZoneid == null ? null : zocoZoneid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zone_comment.zoco_state
     *
     * @return the value of zone_comment.zoco_state
     *
     * @mbggenerated Wed Dec 14 21:38:06 CST 2016
     */
    public String getZocoState() {
        return zocoState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zone_comment.zoco_state
     *
     * @param zocoState the value for zone_comment.zoco_state
     *
     * @mbggenerated Wed Dec 14 21:38:06 CST 2016
     */
    public void setZocoState(String zocoState) {
        this.zocoState = zocoState == null ? null : zocoState.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zone_comment.zoco_time
     *
     * @return the value of zone_comment.zoco_time
     *
     * @mbggenerated Wed Dec 14 21:38:06 CST 2016
     */
    public String getZocoTime() {
        return zocoTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zone_comment.zoco_time
     *
     * @param zocoTime the value for zone_comment.zoco_time
     *
     * @mbggenerated Wed Dec 14 21:38:06 CST 2016
     */
    public void setZocoTime(String zocoTime) {
        this.zocoTime = zocoTime == null ? null : zocoTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zone_comment.zoco_parentid
     *
     * @return the value of zone_comment.zoco_parentid
     *
     * @mbggenerated Wed Dec 14 21:38:06 CST 2016
     */
    public String getZocoParentid() {
        return zocoParentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zone_comment.zoco_parentid
     *
     * @param zocoParentid the value for zone_comment.zoco_parentid
     *
     * @mbggenerated Wed Dec 14 21:38:06 CST 2016
     */
    public void setZocoParentid(String zocoParentid) {
        this.zocoParentid = zocoParentid == null ? null : zocoParentid.trim();
    }
}