package com.ddas.sns.zoneccomment.domain;

import java.util.ArrayList;
import java.util.List;

public class ZoneCommentCriteria {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table zone_comment
     *
     * @mbggenerated Wed Dec 14 21:38:06 CST 2016
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table zone_comment
     *
     * @mbggenerated Wed Dec 14 21:38:06 CST 2016
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table zone_comment
     *
     * @mbggenerated Wed Dec 14 21:38:06 CST 2016
     */
    protected List<Criteria> oredCriteria;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table zone_comment
     *
     * @mbggenerated Wed Dec 14 21:38:06 CST 2016
     */
    protected int limitStart = -1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table zone_comment
     *
     * @mbggenerated Wed Dec 14 21:38:06 CST 2016
     */
    protected int limitEnd = -1;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zone_comment
     *
     * @mbggenerated Wed Dec 14 21:38:06 CST 2016
     */
    public ZoneCommentCriteria() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zone_comment
     *
     * @mbggenerated Wed Dec 14 21:38:06 CST 2016
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zone_comment
     *
     * @mbggenerated Wed Dec 14 21:38:06 CST 2016
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zone_comment
     *
     * @mbggenerated Wed Dec 14 21:38:06 CST 2016
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zone_comment
     *
     * @mbggenerated Wed Dec 14 21:38:06 CST 2016
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zone_comment
     *
     * @mbggenerated Wed Dec 14 21:38:06 CST 2016
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zone_comment
     *
     * @mbggenerated Wed Dec 14 21:38:06 CST 2016
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zone_comment
     *
     * @mbggenerated Wed Dec 14 21:38:06 CST 2016
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zone_comment
     *
     * @mbggenerated Wed Dec 14 21:38:06 CST 2016
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zone_comment
     *
     * @mbggenerated Wed Dec 14 21:38:06 CST 2016
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zone_comment
     *
     * @mbggenerated Wed Dec 14 21:38:06 CST 2016
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zone_comment
     *
     * @mbggenerated Wed Dec 14 21:38:06 CST 2016
     */
    public void setLimitStart(int limitStart) {
        this.limitStart=limitStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zone_comment
     *
     * @mbggenerated Wed Dec 14 21:38:06 CST 2016
     */
    public int getLimitStart() {
        return limitStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zone_comment
     *
     * @mbggenerated Wed Dec 14 21:38:06 CST 2016
     */
    public void setLimitEnd(int limitEnd) {
        this.limitEnd=limitEnd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zone_comment
     *
     * @mbggenerated Wed Dec 14 21:38:06 CST 2016
     */
    public int getLimitEnd() {
        return limitEnd;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table zone_comment
     *
     * @mbggenerated Wed Dec 14 21:38:06 CST 2016
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andZocoIdIsNull() {
            addCriterion("zoco_id is null");
            return (Criteria) this;
        }

        public Criteria andZocoIdIsNotNull() {
            addCriterion("zoco_id is not null");
            return (Criteria) this;
        }

        public Criteria andZocoIdEqualTo(String value) {
            addCriterion("zoco_id =", value, "zocoId");
            return (Criteria) this;
        }

        public Criteria andZocoIdNotEqualTo(String value) {
            addCriterion("zoco_id <>", value, "zocoId");
            return (Criteria) this;
        }

        public Criteria andZocoIdGreaterThan(String value) {
            addCriterion("zoco_id >", value, "zocoId");
            return (Criteria) this;
        }

        public Criteria andZocoIdGreaterThanOrEqualTo(String value) {
            addCriterion("zoco_id >=", value, "zocoId");
            return (Criteria) this;
        }

        public Criteria andZocoIdLessThan(String value) {
            addCriterion("zoco_id <", value, "zocoId");
            return (Criteria) this;
        }

        public Criteria andZocoIdLessThanOrEqualTo(String value) {
            addCriterion("zoco_id <=", value, "zocoId");
            return (Criteria) this;
        }

        public Criteria andZocoIdLike(String value) {
            addCriterion("zoco_id like", value, "zocoId");
            return (Criteria) this;
        }

        public Criteria andZocoIdNotLike(String value) {
            addCriterion("zoco_id not like", value, "zocoId");
            return (Criteria) this;
        }

        public Criteria andZocoIdIn(List<String> values) {
            addCriterion("zoco_id in", values, "zocoId");
            return (Criteria) this;
        }

        public Criteria andZocoIdNotIn(List<String> values) {
            addCriterion("zoco_id not in", values, "zocoId");
            return (Criteria) this;
        }

        public Criteria andZocoIdBetween(String value1, String value2) {
            addCriterion("zoco_id between", value1, value2, "zocoId");
            return (Criteria) this;
        }

        public Criteria andZocoIdNotBetween(String value1, String value2) {
            addCriterion("zoco_id not between", value1, value2, "zocoId");
            return (Criteria) this;
        }

        public Criteria andZocoGagaidIsNull() {
            addCriterion("zoco_gagaid is null");
            return (Criteria) this;
        }

        public Criteria andZocoGagaidIsNotNull() {
            addCriterion("zoco_gagaid is not null");
            return (Criteria) this;
        }

        public Criteria andZocoGagaidEqualTo(String value) {
            addCriterion("zoco_gagaid =", value, "zocoGagaid");
            return (Criteria) this;
        }

        public Criteria andZocoGagaidNotEqualTo(String value) {
            addCriterion("zoco_gagaid <>", value, "zocoGagaid");
            return (Criteria) this;
        }

        public Criteria andZocoGagaidGreaterThan(String value) {
            addCriterion("zoco_gagaid >", value, "zocoGagaid");
            return (Criteria) this;
        }

        public Criteria andZocoGagaidGreaterThanOrEqualTo(String value) {
            addCriterion("zoco_gagaid >=", value, "zocoGagaid");
            return (Criteria) this;
        }

        public Criteria andZocoGagaidLessThan(String value) {
            addCriterion("zoco_gagaid <", value, "zocoGagaid");
            return (Criteria) this;
        }

        public Criteria andZocoGagaidLessThanOrEqualTo(String value) {
            addCriterion("zoco_gagaid <=", value, "zocoGagaid");
            return (Criteria) this;
        }

        public Criteria andZocoGagaidLike(String value) {
            addCriterion("zoco_gagaid like", value, "zocoGagaid");
            return (Criteria) this;
        }

        public Criteria andZocoGagaidNotLike(String value) {
            addCriterion("zoco_gagaid not like", value, "zocoGagaid");
            return (Criteria) this;
        }

        public Criteria andZocoGagaidIn(List<String> values) {
            addCriterion("zoco_gagaid in", values, "zocoGagaid");
            return (Criteria) this;
        }

        public Criteria andZocoGagaidNotIn(List<String> values) {
            addCriterion("zoco_gagaid not in", values, "zocoGagaid");
            return (Criteria) this;
        }

        public Criteria andZocoGagaidBetween(String value1, String value2) {
            addCriterion("zoco_gagaid between", value1, value2, "zocoGagaid");
            return (Criteria) this;
        }

        public Criteria andZocoGagaidNotBetween(String value1, String value2) {
            addCriterion("zoco_gagaid not between", value1, value2, "zocoGagaid");
            return (Criteria) this;
        }

        public Criteria andZocoContentIsNull() {
            addCriterion("zoco_content is null");
            return (Criteria) this;
        }

        public Criteria andZocoContentIsNotNull() {
            addCriterion("zoco_content is not null");
            return (Criteria) this;
        }

        public Criteria andZocoContentEqualTo(String value) {
            addCriterion("zoco_content =", value, "zocoContent");
            return (Criteria) this;
        }

        public Criteria andZocoContentNotEqualTo(String value) {
            addCriterion("zoco_content <>", value, "zocoContent");
            return (Criteria) this;
        }

        public Criteria andZocoContentGreaterThan(String value) {
            addCriterion("zoco_content >", value, "zocoContent");
            return (Criteria) this;
        }

        public Criteria andZocoContentGreaterThanOrEqualTo(String value) {
            addCriterion("zoco_content >=", value, "zocoContent");
            return (Criteria) this;
        }

        public Criteria andZocoContentLessThan(String value) {
            addCriterion("zoco_content <", value, "zocoContent");
            return (Criteria) this;
        }

        public Criteria andZocoContentLessThanOrEqualTo(String value) {
            addCriterion("zoco_content <=", value, "zocoContent");
            return (Criteria) this;
        }

        public Criteria andZocoContentLike(String value) {
            addCriterion("zoco_content like", value, "zocoContent");
            return (Criteria) this;
        }

        public Criteria andZocoContentNotLike(String value) {
            addCriterion("zoco_content not like", value, "zocoContent");
            return (Criteria) this;
        }

        public Criteria andZocoContentIn(List<String> values) {
            addCriterion("zoco_content in", values, "zocoContent");
            return (Criteria) this;
        }

        public Criteria andZocoContentNotIn(List<String> values) {
            addCriterion("zoco_content not in", values, "zocoContent");
            return (Criteria) this;
        }

        public Criteria andZocoContentBetween(String value1, String value2) {
            addCriterion("zoco_content between", value1, value2, "zocoContent");
            return (Criteria) this;
        }

        public Criteria andZocoContentNotBetween(String value1, String value2) {
            addCriterion("zoco_content not between", value1, value2, "zocoContent");
            return (Criteria) this;
        }

        public Criteria andZocoZoneidIsNull() {
            addCriterion("zoco_zoneid is null");
            return (Criteria) this;
        }

        public Criteria andZocoZoneidIsNotNull() {
            addCriterion("zoco_zoneid is not null");
            return (Criteria) this;
        }

        public Criteria andZocoZoneidEqualTo(String value) {
            addCriterion("zoco_zoneid =", value, "zocoZoneid");
            return (Criteria) this;
        }

        public Criteria andZocoZoneidNotEqualTo(String value) {
            addCriterion("zoco_zoneid <>", value, "zocoZoneid");
            return (Criteria) this;
        }

        public Criteria andZocoZoneidGreaterThan(String value) {
            addCriterion("zoco_zoneid >", value, "zocoZoneid");
            return (Criteria) this;
        }

        public Criteria andZocoZoneidGreaterThanOrEqualTo(String value) {
            addCriterion("zoco_zoneid >=", value, "zocoZoneid");
            return (Criteria) this;
        }

        public Criteria andZocoZoneidLessThan(String value) {
            addCriterion("zoco_zoneid <", value, "zocoZoneid");
            return (Criteria) this;
        }

        public Criteria andZocoZoneidLessThanOrEqualTo(String value) {
            addCriterion("zoco_zoneid <=", value, "zocoZoneid");
            return (Criteria) this;
        }

        public Criteria andZocoZoneidLike(String value) {
            addCriterion("zoco_zoneid like", value, "zocoZoneid");
            return (Criteria) this;
        }

        public Criteria andZocoZoneidNotLike(String value) {
            addCriterion("zoco_zoneid not like", value, "zocoZoneid");
            return (Criteria) this;
        }

        public Criteria andZocoZoneidIn(List<String> values) {
            addCriterion("zoco_zoneid in", values, "zocoZoneid");
            return (Criteria) this;
        }

        public Criteria andZocoZoneidNotIn(List<String> values) {
            addCriterion("zoco_zoneid not in", values, "zocoZoneid");
            return (Criteria) this;
        }

        public Criteria andZocoZoneidBetween(String value1, String value2) {
            addCriterion("zoco_zoneid between", value1, value2, "zocoZoneid");
            return (Criteria) this;
        }

        public Criteria andZocoZoneidNotBetween(String value1, String value2) {
            addCriterion("zoco_zoneid not between", value1, value2, "zocoZoneid");
            return (Criteria) this;
        }

        public Criteria andZocoStateIsNull() {
            addCriterion("zoco_state is null");
            return (Criteria) this;
        }

        public Criteria andZocoStateIsNotNull() {
            addCriterion("zoco_state is not null");
            return (Criteria) this;
        }

        public Criteria andZocoStateEqualTo(String value) {
            addCriterion("zoco_state =", value, "zocoState");
            return (Criteria) this;
        }

        public Criteria andZocoStateNotEqualTo(String value) {
            addCriterion("zoco_state <>", value, "zocoState");
            return (Criteria) this;
        }

        public Criteria andZocoStateGreaterThan(String value) {
            addCriterion("zoco_state >", value, "zocoState");
            return (Criteria) this;
        }

        public Criteria andZocoStateGreaterThanOrEqualTo(String value) {
            addCriterion("zoco_state >=", value, "zocoState");
            return (Criteria) this;
        }

        public Criteria andZocoStateLessThan(String value) {
            addCriterion("zoco_state <", value, "zocoState");
            return (Criteria) this;
        }

        public Criteria andZocoStateLessThanOrEqualTo(String value) {
            addCriterion("zoco_state <=", value, "zocoState");
            return (Criteria) this;
        }

        public Criteria andZocoStateLike(String value) {
            addCriterion("zoco_state like", value, "zocoState");
            return (Criteria) this;
        }

        public Criteria andZocoStateNotLike(String value) {
            addCriterion("zoco_state not like", value, "zocoState");
            return (Criteria) this;
        }

        public Criteria andZocoStateIn(List<String> values) {
            addCriterion("zoco_state in", values, "zocoState");
            return (Criteria) this;
        }

        public Criteria andZocoStateNotIn(List<String> values) {
            addCriterion("zoco_state not in", values, "zocoState");
            return (Criteria) this;
        }

        public Criteria andZocoStateBetween(String value1, String value2) {
            addCriterion("zoco_state between", value1, value2, "zocoState");
            return (Criteria) this;
        }

        public Criteria andZocoStateNotBetween(String value1, String value2) {
            addCriterion("zoco_state not between", value1, value2, "zocoState");
            return (Criteria) this;
        }

        public Criteria andZocoTimeIsNull() {
            addCriterion("zoco_time is null");
            return (Criteria) this;
        }

        public Criteria andZocoTimeIsNotNull() {
            addCriterion("zoco_time is not null");
            return (Criteria) this;
        }

        public Criteria andZocoTimeEqualTo(String value) {
            addCriterion("zoco_time =", value, "zocoTime");
            return (Criteria) this;
        }

        public Criteria andZocoTimeNotEqualTo(String value) {
            addCriterion("zoco_time <>", value, "zocoTime");
            return (Criteria) this;
        }

        public Criteria andZocoTimeGreaterThan(String value) {
            addCriterion("zoco_time >", value, "zocoTime");
            return (Criteria) this;
        }

        public Criteria andZocoTimeGreaterThanOrEqualTo(String value) {
            addCriterion("zoco_time >=", value, "zocoTime");
            return (Criteria) this;
        }

        public Criteria andZocoTimeLessThan(String value) {
            addCriterion("zoco_time <", value, "zocoTime");
            return (Criteria) this;
        }

        public Criteria andZocoTimeLessThanOrEqualTo(String value) {
            addCriterion("zoco_time <=", value, "zocoTime");
            return (Criteria) this;
        }

        public Criteria andZocoTimeLike(String value) {
            addCriterion("zoco_time like", value, "zocoTime");
            return (Criteria) this;
        }

        public Criteria andZocoTimeNotLike(String value) {
            addCriterion("zoco_time not like", value, "zocoTime");
            return (Criteria) this;
        }

        public Criteria andZocoTimeIn(List<String> values) {
            addCriterion("zoco_time in", values, "zocoTime");
            return (Criteria) this;
        }

        public Criteria andZocoTimeNotIn(List<String> values) {
            addCriterion("zoco_time not in", values, "zocoTime");
            return (Criteria) this;
        }

        public Criteria andZocoTimeBetween(String value1, String value2) {
            addCriterion("zoco_time between", value1, value2, "zocoTime");
            return (Criteria) this;
        }

        public Criteria andZocoTimeNotBetween(String value1, String value2) {
            addCriterion("zoco_time not between", value1, value2, "zocoTime");
            return (Criteria) this;
        }

        public Criteria andZocoParentidIsNull() {
            addCriterion("zoco_parentid is null");
            return (Criteria) this;
        }

        public Criteria andZocoParentidIsNotNull() {
            addCriterion("zoco_parentid is not null");
            return (Criteria) this;
        }

        public Criteria andZocoParentidEqualTo(String value) {
            addCriterion("zoco_parentid =", value, "zocoParentid");
            return (Criteria) this;
        }

        public Criteria andZocoParentidNotEqualTo(String value) {
            addCriterion("zoco_parentid <>", value, "zocoParentid");
            return (Criteria) this;
        }

        public Criteria andZocoParentidGreaterThan(String value) {
            addCriterion("zoco_parentid >", value, "zocoParentid");
            return (Criteria) this;
        }

        public Criteria andZocoParentidGreaterThanOrEqualTo(String value) {
            addCriterion("zoco_parentid >=", value, "zocoParentid");
            return (Criteria) this;
        }

        public Criteria andZocoParentidLessThan(String value) {
            addCriterion("zoco_parentid <", value, "zocoParentid");
            return (Criteria) this;
        }

        public Criteria andZocoParentidLessThanOrEqualTo(String value) {
            addCriterion("zoco_parentid <=", value, "zocoParentid");
            return (Criteria) this;
        }

        public Criteria andZocoParentidLike(String value) {
            addCriterion("zoco_parentid like", value, "zocoParentid");
            return (Criteria) this;
        }

        public Criteria andZocoParentidNotLike(String value) {
            addCriterion("zoco_parentid not like", value, "zocoParentid");
            return (Criteria) this;
        }

        public Criteria andZocoParentidIn(List<String> values) {
            addCriterion("zoco_parentid in", values, "zocoParentid");
            return (Criteria) this;
        }

        public Criteria andZocoParentidNotIn(List<String> values) {
            addCriterion("zoco_parentid not in", values, "zocoParentid");
            return (Criteria) this;
        }

        public Criteria andZocoParentidBetween(String value1, String value2) {
            addCriterion("zoco_parentid between", value1, value2, "zocoParentid");
            return (Criteria) this;
        }

        public Criteria andZocoParentidNotBetween(String value1, String value2) {
            addCriterion("zoco_parentid not between", value1, value2, "zocoParentid");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table zone_comment
     *
     * @mbggenerated do_not_delete_during_merge Wed Dec 14 21:38:06 CST 2016
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }

        public Criteria andZocoIdLikeInsensitive(String value) {
            addCriterion("upper(zoco_id) like", value.toUpperCase(), "zocoId");
            return this;
        }

        public Criteria andZocoGagaidLikeInsensitive(String value) {
            addCriterion("upper(zoco_gagaid) like", value.toUpperCase(), "zocoGagaid");
            return this;
        }

        public Criteria andZocoContentLikeInsensitive(String value) {
            addCriterion("upper(zoco_content) like", value.toUpperCase(), "zocoContent");
            return this;
        }

        public Criteria andZocoZoneidLikeInsensitive(String value) {
            addCriterion("upper(zoco_zoneid) like", value.toUpperCase(), "zocoZoneid");
            return this;
        }

        public Criteria andZocoStateLikeInsensitive(String value) {
            addCriterion("upper(zoco_state) like", value.toUpperCase(), "zocoState");
            return this;
        }

        public Criteria andZocoTimeLikeInsensitive(String value) {
            addCriterion("upper(zoco_time) like", value.toUpperCase(), "zocoTime");
            return this;
        }

        public Criteria andZocoParentidLikeInsensitive(String value) {
            addCriterion("upper(zoco_parentid) like", value.toUpperCase(), "zocoParentid");
            return this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table zone_comment
     *
     * @mbggenerated Wed Dec 14 21:38:06 CST 2016
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}