package com.ddas.sns.zone.domain;

import java.util.ArrayList;
import java.util.List;

public class ZoneInfoCriteria {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table zone_info
     *
     * @mbggenerated Mon Dec 05 22:51:07 CST 2016
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table zone_info
     *
     * @mbggenerated Mon Dec 05 22:51:07 CST 2016
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table zone_info
     *
     * @mbggenerated Mon Dec 05 22:51:07 CST 2016
     */
    protected List<Criteria> oredCriteria;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table zone_info
     *
     * @mbggenerated Mon Dec 05 22:51:07 CST 2016
     */
    protected int limitStart = -1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table zone_info
     *
     * @mbggenerated Mon Dec 05 22:51:07 CST 2016
     */
    protected int limitEnd = -1;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zone_info
     *
     * @mbggenerated Mon Dec 05 22:51:07 CST 2016
     */
    public ZoneInfoCriteria() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zone_info
     *
     * @mbggenerated Mon Dec 05 22:51:07 CST 2016
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zone_info
     *
     * @mbggenerated Mon Dec 05 22:51:07 CST 2016
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zone_info
     *
     * @mbggenerated Mon Dec 05 22:51:07 CST 2016
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zone_info
     *
     * @mbggenerated Mon Dec 05 22:51:07 CST 2016
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zone_info
     *
     * @mbggenerated Mon Dec 05 22:51:07 CST 2016
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zone_info
     *
     * @mbggenerated Mon Dec 05 22:51:07 CST 2016
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zone_info
     *
     * @mbggenerated Mon Dec 05 22:51:07 CST 2016
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zone_info
     *
     * @mbggenerated Mon Dec 05 22:51:07 CST 2016
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zone_info
     *
     * @mbggenerated Mon Dec 05 22:51:07 CST 2016
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zone_info
     *
     * @mbggenerated Mon Dec 05 22:51:07 CST 2016
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zone_info
     *
     * @mbggenerated Mon Dec 05 22:51:07 CST 2016
     */
    public void setLimitStart(int limitStart) {
        this.limitStart=limitStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zone_info
     *
     * @mbggenerated Mon Dec 05 22:51:07 CST 2016
     */
    public int getLimitStart() {
        return limitStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zone_info
     *
     * @mbggenerated Mon Dec 05 22:51:07 CST 2016
     */
    public void setLimitEnd(int limitEnd) {
        this.limitEnd=limitEnd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zone_info
     *
     * @mbggenerated Mon Dec 05 22:51:07 CST 2016
     */
    public int getLimitEnd() {
        return limitEnd;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table zone_info
     *
     * @mbggenerated Mon Dec 05 22:51:07 CST 2016
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andZoneIdIsNull() {
            addCriterion("zone_id is null");
            return (Criteria) this;
        }

        public Criteria andZoneIdIsNotNull() {
            addCriterion("zone_id is not null");
            return (Criteria) this;
        }

        public Criteria andZoneIdEqualTo(String value) {
            addCriterion("zone_id =", value, "zoneId");
            return (Criteria) this;
        }

        public Criteria andZoneIdNotEqualTo(String value) {
            addCriterion("zone_id <>", value, "zoneId");
            return (Criteria) this;
        }

        public Criteria andZoneIdGreaterThan(String value) {
            addCriterion("zone_id >", value, "zoneId");
            return (Criteria) this;
        }

        public Criteria andZoneIdGreaterThanOrEqualTo(String value) {
            addCriterion("zone_id >=", value, "zoneId");
            return (Criteria) this;
        }

        public Criteria andZoneIdLessThan(String value) {
            addCriterion("zone_id <", value, "zoneId");
            return (Criteria) this;
        }

        public Criteria andZoneIdLessThanOrEqualTo(String value) {
            addCriterion("zone_id <=", value, "zoneId");
            return (Criteria) this;
        }

        public Criteria andZoneIdLike(String value) {
            addCriterion("zone_id like", value, "zoneId");
            return (Criteria) this;
        }

        public Criteria andZoneIdNotLike(String value) {
            addCriterion("zone_id not like", value, "zoneId");
            return (Criteria) this;
        }

        public Criteria andZoneIdIn(List<String> values) {
            addCriterion("zone_id in", values, "zoneId");
            return (Criteria) this;
        }

        public Criteria andZoneIdNotIn(List<String> values) {
            addCriterion("zone_id not in", values, "zoneId");
            return (Criteria) this;
        }

        public Criteria andZoneIdBetween(String value1, String value2) {
            addCriterion("zone_id between", value1, value2, "zoneId");
            return (Criteria) this;
        }

        public Criteria andZoneIdNotBetween(String value1, String value2) {
            addCriterion("zone_id not between", value1, value2, "zoneId");
            return (Criteria) this;
        }

        public Criteria andZoneContentIsNull() {
            addCriterion("zone_content is null");
            return (Criteria) this;
        }

        public Criteria andZoneContentIsNotNull() {
            addCriterion("zone_content is not null");
            return (Criteria) this;
        }

        public Criteria andZoneContentEqualTo(String value) {
            addCriterion("zone_content =", value, "zoneContent");
            return (Criteria) this;
        }

        public Criteria andZoneContentNotEqualTo(String value) {
            addCriterion("zone_content <>", value, "zoneContent");
            return (Criteria) this;
        }

        public Criteria andZoneContentGreaterThan(String value) {
            addCriterion("zone_content >", value, "zoneContent");
            return (Criteria) this;
        }

        public Criteria andZoneContentGreaterThanOrEqualTo(String value) {
            addCriterion("zone_content >=", value, "zoneContent");
            return (Criteria) this;
        }

        public Criteria andZoneContentLessThan(String value) {
            addCriterion("zone_content <", value, "zoneContent");
            return (Criteria) this;
        }

        public Criteria andZoneContentLessThanOrEqualTo(String value) {
            addCriterion("zone_content <=", value, "zoneContent");
            return (Criteria) this;
        }

        public Criteria andZoneContentLike(String value) {
            addCriterion("zone_content like", value, "zoneContent");
            return (Criteria) this;
        }

        public Criteria andZoneContentNotLike(String value) {
            addCriterion("zone_content not like", value, "zoneContent");
            return (Criteria) this;
        }

        public Criteria andZoneContentIn(List<String> values) {
            addCriterion("zone_content in", values, "zoneContent");
            return (Criteria) this;
        }

        public Criteria andZoneContentNotIn(List<String> values) {
            addCriterion("zone_content not in", values, "zoneContent");
            return (Criteria) this;
        }

        public Criteria andZoneContentBetween(String value1, String value2) {
            addCriterion("zone_content between", value1, value2, "zoneContent");
            return (Criteria) this;
        }

        public Criteria andZoneContentNotBetween(String value1, String value2) {
            addCriterion("zone_content not between", value1, value2, "zoneContent");
            return (Criteria) this;
        }

        public Criteria andZoneDatetimeIsNull() {
            addCriterion("zone_datetime is null");
            return (Criteria) this;
        }

        public Criteria andZoneDatetimeIsNotNull() {
            addCriterion("zone_datetime is not null");
            return (Criteria) this;
        }

        public Criteria andZoneDatetimeEqualTo(String value) {
            addCriterion("zone_datetime =", value, "zoneDatetime");
            return (Criteria) this;
        }

        public Criteria andZoneDatetimeNotEqualTo(String value) {
            addCriterion("zone_datetime <>", value, "zoneDatetime");
            return (Criteria) this;
        }

        public Criteria andZoneDatetimeGreaterThan(String value) {
            addCriterion("zone_datetime >", value, "zoneDatetime");
            return (Criteria) this;
        }

        public Criteria andZoneDatetimeGreaterThanOrEqualTo(String value) {
            addCriterion("zone_datetime >=", value, "zoneDatetime");
            return (Criteria) this;
        }

        public Criteria andZoneDatetimeLessThan(String value) {
            addCriterion("zone_datetime <", value, "zoneDatetime");
            return (Criteria) this;
        }

        public Criteria andZoneDatetimeLessThanOrEqualTo(String value) {
            addCriterion("zone_datetime <=", value, "zoneDatetime");
            return (Criteria) this;
        }

        public Criteria andZoneDatetimeLike(String value) {
            addCriterion("zone_datetime like", value, "zoneDatetime");
            return (Criteria) this;
        }

        public Criteria andZoneDatetimeNotLike(String value) {
            addCriterion("zone_datetime not like", value, "zoneDatetime");
            return (Criteria) this;
        }

        public Criteria andZoneDatetimeIn(List<String> values) {
            addCriterion("zone_datetime in", values, "zoneDatetime");
            return (Criteria) this;
        }

        public Criteria andZoneDatetimeNotIn(List<String> values) {
            addCriterion("zone_datetime not in", values, "zoneDatetime");
            return (Criteria) this;
        }

        public Criteria andZoneDatetimeBetween(String value1, String value2) {
            addCriterion("zone_datetime between", value1, value2, "zoneDatetime");
            return (Criteria) this;
        }

        public Criteria andZoneDatetimeNotBetween(String value1, String value2) {
            addCriterion("zone_datetime not between", value1, value2, "zoneDatetime");
            return (Criteria) this;
        }

        public Criteria andZoneLikecountIsNull() {
            addCriterion("zone_likecount is null");
            return (Criteria) this;
        }

        public Criteria andZoneLikecountIsNotNull() {
            addCriterion("zone_likecount is not null");
            return (Criteria) this;
        }

        public Criteria andZoneLikecountEqualTo(Integer value) {
            addCriterion("zone_likecount =", value, "zoneLikecount");
            return (Criteria) this;
        }

        public Criteria andZoneLikecountNotEqualTo(Integer value) {
            addCriterion("zone_likecount <>", value, "zoneLikecount");
            return (Criteria) this;
        }

        public Criteria andZoneLikecountGreaterThan(Integer value) {
            addCriterion("zone_likecount >", value, "zoneLikecount");
            return (Criteria) this;
        }

        public Criteria andZoneLikecountGreaterThanOrEqualTo(Integer value) {
            addCriterion("zone_likecount >=", value, "zoneLikecount");
            return (Criteria) this;
        }

        public Criteria andZoneLikecountLessThan(Integer value) {
            addCriterion("zone_likecount <", value, "zoneLikecount");
            return (Criteria) this;
        }

        public Criteria andZoneLikecountLessThanOrEqualTo(Integer value) {
            addCriterion("zone_likecount <=", value, "zoneLikecount");
            return (Criteria) this;
        }

        public Criteria andZoneLikecountIn(List<Integer> values) {
            addCriterion("zone_likecount in", values, "zoneLikecount");
            return (Criteria) this;
        }

        public Criteria andZoneLikecountNotIn(List<Integer> values) {
            addCriterion("zone_likecount not in", values, "zoneLikecount");
            return (Criteria) this;
        }

        public Criteria andZoneLikecountBetween(Integer value1, Integer value2) {
            addCriterion("zone_likecount between", value1, value2, "zoneLikecount");
            return (Criteria) this;
        }

        public Criteria andZoneLikecountNotBetween(Integer value1, Integer value2) {
            addCriterion("zone_likecount not between", value1, value2, "zoneLikecount");
            return (Criteria) this;
        }

        public Criteria andZoneGagaidIsNull() {
            addCriterion("zone_gagaid is null");
            return (Criteria) this;
        }

        public Criteria andZoneGagaidIsNotNull() {
            addCriterion("zone_gagaid is not null");
            return (Criteria) this;
        }

        public Criteria andZoneGagaidEqualTo(String value) {
            addCriterion("zone_gagaid =", value, "zoneGagaid");
            return (Criteria) this;
        }

        public Criteria andZoneGagaidNotEqualTo(String value) {
            addCriterion("zone_gagaid <>", value, "zoneGagaid");
            return (Criteria) this;
        }

        public Criteria andZoneGagaidGreaterThan(String value) {
            addCriterion("zone_gagaid >", value, "zoneGagaid");
            return (Criteria) this;
        }

        public Criteria andZoneGagaidGreaterThanOrEqualTo(String value) {
            addCriterion("zone_gagaid >=", value, "zoneGagaid");
            return (Criteria) this;
        }

        public Criteria andZoneGagaidLessThan(String value) {
            addCriterion("zone_gagaid <", value, "zoneGagaid");
            return (Criteria) this;
        }

        public Criteria andZoneGagaidLessThanOrEqualTo(String value) {
            addCriterion("zone_gagaid <=", value, "zoneGagaid");
            return (Criteria) this;
        }

        public Criteria andZoneGagaidLike(String value) {
            addCriterion("zone_gagaid like", value, "zoneGagaid");
            return (Criteria) this;
        }

        public Criteria andZoneGagaidNotLike(String value) {
            addCriterion("zone_gagaid not like", value, "zoneGagaid");
            return (Criteria) this;
        }

        public Criteria andZoneGagaidIn(List<String> values) {
            addCriterion("zone_gagaid in", values, "zoneGagaid");
            return (Criteria) this;
        }

        public Criteria andZoneGagaidNotIn(List<String> values) {
            addCriterion("zone_gagaid not in", values, "zoneGagaid");
            return (Criteria) this;
        }

        public Criteria andZoneGagaidBetween(String value1, String value2) {
            addCriterion("zone_gagaid between", value1, value2, "zoneGagaid");
            return (Criteria) this;
        }

        public Criteria andZoneGagaidNotBetween(String value1, String value2) {
            addCriterion("zone_gagaid not between", value1, value2, "zoneGagaid");
            return (Criteria) this;
        }

        public Criteria andZoneImgcountIsNull() {
            addCriterion("zone_imgcount is null");
            return (Criteria) this;
        }

        public Criteria andZoneImgcountIsNotNull() {
            addCriterion("zone_imgcount is not null");
            return (Criteria) this;
        }

        public Criteria andZoneImgcountEqualTo(Integer value) {
            addCriterion("zone_imgcount =", value, "zoneImgcount");
            return (Criteria) this;
        }

        public Criteria andZoneImgcountNotEqualTo(Integer value) {
            addCriterion("zone_imgcount <>", value, "zoneImgcount");
            return (Criteria) this;
        }

        public Criteria andZoneImgcountGreaterThan(Integer value) {
            addCriterion("zone_imgcount >", value, "zoneImgcount");
            return (Criteria) this;
        }

        public Criteria andZoneImgcountGreaterThanOrEqualTo(Integer value) {
            addCriterion("zone_imgcount >=", value, "zoneImgcount");
            return (Criteria) this;
        }

        public Criteria andZoneImgcountLessThan(Integer value) {
            addCriterion("zone_imgcount <", value, "zoneImgcount");
            return (Criteria) this;
        }

        public Criteria andZoneImgcountLessThanOrEqualTo(Integer value) {
            addCriterion("zone_imgcount <=", value, "zoneImgcount");
            return (Criteria) this;
        }

        public Criteria andZoneImgcountIn(List<Integer> values) {
            addCriterion("zone_imgcount in", values, "zoneImgcount");
            return (Criteria) this;
        }

        public Criteria andZoneImgcountNotIn(List<Integer> values) {
            addCriterion("zone_imgcount not in", values, "zoneImgcount");
            return (Criteria) this;
        }

        public Criteria andZoneImgcountBetween(Integer value1, Integer value2) {
            addCriterion("zone_imgcount between", value1, value2, "zoneImgcount");
            return (Criteria) this;
        }

        public Criteria andZoneImgcountNotBetween(Integer value1, Integer value2) {
            addCriterion("zone_imgcount not between", value1, value2, "zoneImgcount");
            return (Criteria) this;
        }

        public Criteria andZoneStateIsNull() {
            addCriterion("zone_state is null");
            return (Criteria) this;
        }

        public Criteria andZoneStateIsNotNull() {
            addCriterion("zone_state is not null");
            return (Criteria) this;
        }

        public Criteria andZoneStateEqualTo(String value) {
            addCriterion("zone_state =", value, "zoneState");
            return (Criteria) this;
        }

        public Criteria andZoneStateNotEqualTo(String value) {
            addCriterion("zone_state <>", value, "zoneState");
            return (Criteria) this;
        }

        public Criteria andZoneStateGreaterThan(String value) {
            addCriterion("zone_state >", value, "zoneState");
            return (Criteria) this;
        }

        public Criteria andZoneStateGreaterThanOrEqualTo(String value) {
            addCriterion("zone_state >=", value, "zoneState");
            return (Criteria) this;
        }

        public Criteria andZoneStateLessThan(String value) {
            addCriterion("zone_state <", value, "zoneState");
            return (Criteria) this;
        }

        public Criteria andZoneStateLessThanOrEqualTo(String value) {
            addCriterion("zone_state <=", value, "zoneState");
            return (Criteria) this;
        }

        public Criteria andZoneStateLike(String value) {
            addCriterion("zone_state like", value, "zoneState");
            return (Criteria) this;
        }

        public Criteria andZoneStateNotLike(String value) {
            addCriterion("zone_state not like", value, "zoneState");
            return (Criteria) this;
        }

        public Criteria andZoneStateIn(List<String> values) {
            addCriterion("zone_state in", values, "zoneState");
            return (Criteria) this;
        }

        public Criteria andZoneStateNotIn(List<String> values) {
            addCriterion("zone_state not in", values, "zoneState");
            return (Criteria) this;
        }

        public Criteria andZoneStateBetween(String value1, String value2) {
            addCriterion("zone_state between", value1, value2, "zoneState");
            return (Criteria) this;
        }

        public Criteria andZoneStateNotBetween(String value1, String value2) {
            addCriterion("zone_state not between", value1, value2, "zoneState");
            return (Criteria) this;
        }

        public Criteria andZoneCommentcountIsNull() {
            addCriterion("zone_commentcount is null");
            return (Criteria) this;
        }

        public Criteria andZoneCommentcountIsNotNull() {
            addCriterion("zone_commentcount is not null");
            return (Criteria) this;
        }

        public Criteria andZoneCommentcountEqualTo(Integer value) {
            addCriterion("zone_commentcount =", value, "zoneCommentcount");
            return (Criteria) this;
        }

        public Criteria andZoneCommentcountNotEqualTo(Integer value) {
            addCriterion("zone_commentcount <>", value, "zoneCommentcount");
            return (Criteria) this;
        }

        public Criteria andZoneCommentcountGreaterThan(Integer value) {
            addCriterion("zone_commentcount >", value, "zoneCommentcount");
            return (Criteria) this;
        }

        public Criteria andZoneCommentcountGreaterThanOrEqualTo(Integer value) {
            addCriterion("zone_commentcount >=", value, "zoneCommentcount");
            return (Criteria) this;
        }

        public Criteria andZoneCommentcountLessThan(Integer value) {
            addCriterion("zone_commentcount <", value, "zoneCommentcount");
            return (Criteria) this;
        }

        public Criteria andZoneCommentcountLessThanOrEqualTo(Integer value) {
            addCriterion("zone_commentcount <=", value, "zoneCommentcount");
            return (Criteria) this;
        }

        public Criteria andZoneCommentcountIn(List<Integer> values) {
            addCriterion("zone_commentcount in", values, "zoneCommentcount");
            return (Criteria) this;
        }

        public Criteria andZoneCommentcountNotIn(List<Integer> values) {
            addCriterion("zone_commentcount not in", values, "zoneCommentcount");
            return (Criteria) this;
        }

        public Criteria andZoneCommentcountBetween(Integer value1, Integer value2) {
            addCriterion("zone_commentcount between", value1, value2, "zoneCommentcount");
            return (Criteria) this;
        }

        public Criteria andZoneCommentcountNotBetween(Integer value1, Integer value2) {
            addCriterion("zone_commentcount not between", value1, value2, "zoneCommentcount");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table zone_info
     *
     * @mbggenerated do_not_delete_during_merge Mon Dec 05 22:51:07 CST 2016
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }

        public Criteria andZoneIdLikeInsensitive(String value) {
            addCriterion("upper(zone_id) like", value.toUpperCase(), "zoneId");
            return this;
        }

        public Criteria andZoneContentLikeInsensitive(String value) {
            addCriterion("upper(zone_content) like", value.toUpperCase(), "zoneContent");
            return this;
        }

        public Criteria andZoneDatetimeLikeInsensitive(String value) {
            addCriterion("upper(zone_datetime) like", value.toUpperCase(), "zoneDatetime");
            return this;
        }

        public Criteria andZoneGagaidLikeInsensitive(String value) {
            addCriterion("upper(zone_gagaid) like", value.toUpperCase(), "zoneGagaid");
            return this;
        }

        public Criteria andZoneStateLikeInsensitive(String value) {
            addCriterion("upper(zone_state) like", value.toUpperCase(), "zoneState");
            return this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table zone_info
     *
     * @mbggenerated Mon Dec 05 22:51:07 CST 2016
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}