package com.ddas.sns.image.domain;

import java.io.Serializable;

public class ImageInfo implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column image_info.zoim_id
     *
     * @mbggenerated Mon Dec 12 21:26:57 CST 2016
     */
    private String zoimId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column image_info.zoim_gagaid
     *
     * @mbggenerated Mon Dec 12 21:26:57 CST 2016
     */
    private String zoimGagaid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column image_info.zoim_zoneid
     *
     * @mbggenerated Mon Dec 12 21:26:57 CST 2016
     */
    private String zoimZoneid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column image_info.zoim_imgurl
     *
     * @mbggenerated Mon Dec 12 21:26:57 CST 2016
     */
    private String zoimImgurl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column image_info.zoim_sort
     *
     * @mbggenerated Mon Dec 12 21:26:57 CST 2016
     */
    private Integer zoimSort;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column image_info.zoim_state
     *
     * @mbggenerated Mon Dec 12 21:26:57 CST 2016
     */
    private String zoimState;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column image_info.zoim_isrecommend
     *
     * @mbggenerated Mon Dec 12 21:26:57 CST 2016
     */
    private String zoimIsrecommend;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column image_info.zoim_likecount
     *
     * @mbggenerated Mon Dec 12 21:26:57 CST 2016
     */
    private Integer zoimLikecount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column image_info.zoim_time
     *
     * @mbggenerated Mon Dec 12 21:26:57 CST 2016
     */
    private String zoimTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column image_info.zone_imgcount
     *
     * @mbggenerated Mon Dec 12 21:26:57 CST 2016
     */
    private Integer zoneImgcount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table image_info
     *
     * @mbggenerated Mon Dec 12 21:26:57 CST 2016
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column image_info.zoim_id
     *
     * @return the value of image_info.zoim_id
     *
     * @mbggenerated Mon Dec 12 21:26:57 CST 2016
     */
    public String getZoimId() {
        return zoimId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column image_info.zoim_id
     *
     * @param zoimId the value for image_info.zoim_id
     *
     * @mbggenerated Mon Dec 12 21:26:57 CST 2016
     */
    public void setZoimId(String zoimId) {
        this.zoimId = zoimId == null ? null : zoimId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column image_info.zoim_gagaid
     *
     * @return the value of image_info.zoim_gagaid
     *
     * @mbggenerated Mon Dec 12 21:26:57 CST 2016
     */
    public String getZoimGagaid() {
        return zoimGagaid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column image_info.zoim_gagaid
     *
     * @param zoimGagaid the value for image_info.zoim_gagaid
     *
     * @mbggenerated Mon Dec 12 21:26:57 CST 2016
     */
    public void setZoimGagaid(String zoimGagaid) {
        this.zoimGagaid = zoimGagaid == null ? null : zoimGagaid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column image_info.zoim_zoneid
     *
     * @return the value of image_info.zoim_zoneid
     *
     * @mbggenerated Mon Dec 12 21:26:57 CST 2016
     */
    public String getZoimZoneid() {
        return zoimZoneid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column image_info.zoim_zoneid
     *
     * @param zoimZoneid the value for image_info.zoim_zoneid
     *
     * @mbggenerated Mon Dec 12 21:26:57 CST 2016
     */
    public void setZoimZoneid(String zoimZoneid) {
        this.zoimZoneid = zoimZoneid == null ? null : zoimZoneid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column image_info.zoim_imgurl
     *
     * @return the value of image_info.zoim_imgurl
     *
     * @mbggenerated Mon Dec 12 21:26:57 CST 2016
     */
    public String getZoimImgurl() {
        return zoimImgurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column image_info.zoim_imgurl
     *
     * @param zoimImgurl the value for image_info.zoim_imgurl
     *
     * @mbggenerated Mon Dec 12 21:26:57 CST 2016
     */
    public void setZoimImgurl(String zoimImgurl) {
        this.zoimImgurl = zoimImgurl == null ? null : zoimImgurl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column image_info.zoim_sort
     *
     * @return the value of image_info.zoim_sort
     *
     * @mbggenerated Mon Dec 12 21:26:57 CST 2016
     */
    public Integer getZoimSort() {
        return zoimSort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column image_info.zoim_sort
     *
     * @param zoimSort the value for image_info.zoim_sort
     *
     * @mbggenerated Mon Dec 12 21:26:57 CST 2016
     */
    public void setZoimSort(Integer zoimSort) {
        this.zoimSort = zoimSort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column image_info.zoim_state
     *
     * @return the value of image_info.zoim_state
     *
     * @mbggenerated Mon Dec 12 21:26:57 CST 2016
     */
    public String getZoimState() {
        return zoimState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column image_info.zoim_state
     *
     * @param zoimState the value for image_info.zoim_state
     *
     * @mbggenerated Mon Dec 12 21:26:57 CST 2016
     */
    public void setZoimState(String zoimState) {
        this.zoimState = zoimState == null ? null : zoimState.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column image_info.zoim_isrecommend
     *
     * @return the value of image_info.zoim_isrecommend
     *
     * @mbggenerated Mon Dec 12 21:26:57 CST 2016
     */
    public String getZoimIsrecommend() {
        return zoimIsrecommend;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column image_info.zoim_isrecommend
     *
     * @param zoimIsrecommend the value for image_info.zoim_isrecommend
     *
     * @mbggenerated Mon Dec 12 21:26:57 CST 2016
     */
    public void setZoimIsrecommend(String zoimIsrecommend) {
        this.zoimIsrecommend = zoimIsrecommend == null ? null : zoimIsrecommend.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column image_info.zoim_likecount
     *
     * @return the value of image_info.zoim_likecount
     *
     * @mbggenerated Mon Dec 12 21:26:57 CST 2016
     */
    public Integer getZoimLikecount() {
        return zoimLikecount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column image_info.zoim_likecount
     *
     * @param zoimLikecount the value for image_info.zoim_likecount
     *
     * @mbggenerated Mon Dec 12 21:26:57 CST 2016
     */
    public void setZoimLikecount(Integer zoimLikecount) {
        this.zoimLikecount = zoimLikecount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column image_info.zoim_time
     *
     * @return the value of image_info.zoim_time
     *
     * @mbggenerated Mon Dec 12 21:26:57 CST 2016
     */
    public String getZoimTime() {
        return zoimTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column image_info.zoim_time
     *
     * @param zoimTime the value for image_info.zoim_time
     *
     * @mbggenerated Mon Dec 12 21:26:57 CST 2016
     */
    public void setZoimTime(String zoimTime) {
        this.zoimTime = zoimTime == null ? null : zoimTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column image_info.zone_imgcount
     *
     * @return the value of image_info.zone_imgcount
     *
     * @mbggenerated Mon Dec 12 21:26:57 CST 2016
     */
    public Integer getZoneImgcount() {
        return zoneImgcount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column image_info.zone_imgcount
     *
     * @param zoneImgcount the value for image_info.zone_imgcount
     *
     * @mbggenerated Mon Dec 12 21:26:57 CST 2016
     */
    public void setZoneImgcount(Integer zoneImgcount) {
        this.zoneImgcount = zoneImgcount;
    }
}