package com.ddas.sns.userblog.mapper;

import com.ddas.sns.userblog.domain.UserBlog;
import com.ddas.sns.userblog.domain.UserBlogCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UserBlogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_blog
     *
     * @mbggenerated Sun Jul 03 12:22:26 CST 2016
     */
    int countByExample(UserBlogCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_blog
     *
     * @mbggenerated Sun Jul 03 12:22:26 CST 2016
     */
    int deleteByExample(UserBlogCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_blog
     *
     * @mbggenerated Sun Jul 03 12:22:26 CST 2016
     */
    int insert(UserBlog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_blog
     *
     * @mbggenerated Sun Jul 03 12:22:26 CST 2016
     */
    int insertSelective(UserBlog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_blog
     *
     * @mbggenerated Sun Jul 03 12:22:26 CST 2016
     */
    List<UserBlog> selectByExample(UserBlogCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_blog
     *
     * @mbggenerated Sun Jul 03 12:22:26 CST 2016
     */
    int updateByExampleSelective(@Param("record") UserBlog record, @Param("example") UserBlogCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_blog
     *
     * @mbggenerated Sun Jul 03 12:22:26 CST 2016
     */
    int updateByExample(@Param("record") UserBlog record, @Param("example") UserBlogCriteria example);
}