package com.ddas.sns.privateletter.mapper;

import com.ddas.sns.privateletter.domain.UserPrivateLetter;
import com.ddas.sns.privateletter.domain.UserPrivateLetterCriteria;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface UserPrivateLetterMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_private_letter
     *
     * @mbggenerated Sat Nov 26 19:39:03 CST 2016
     */
    int countByExample(UserPrivateLetterCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_private_letter
     *
     * @mbggenerated Sat Nov 26 19:39:03 CST 2016
     */
    int deleteByExample(UserPrivateLetterCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_private_letter
     *
     * @mbggenerated Sat Nov 26 19:39:03 CST 2016
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_private_letter
     *
     * @mbggenerated Sat Nov 26 19:39:03 CST 2016
     */
    int insert(UserPrivateLetter record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_private_letter
     *
     * @mbggenerated Sat Nov 26 19:39:03 CST 2016
     */
    int insertSelective(UserPrivateLetter record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_private_letter
     *
     * @mbggenerated Sat Nov 26 19:39:03 CST 2016
     */
    List<UserPrivateLetter> selectByExample(UserPrivateLetterCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_private_letter
     *
     * @mbggenerated Sat Nov 26 19:39:03 CST 2016
     */
    UserPrivateLetter selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_private_letter
     *
     * @mbggenerated Sat Nov 26 19:39:03 CST 2016
     */
    int updateByExampleSelective(@Param("record") UserPrivateLetter record, @Param("example") UserPrivateLetterCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_private_letter
     *
     * @mbggenerated Sat Nov 26 19:39:03 CST 2016
     */
    int updateByExample(@Param("record") UserPrivateLetter record, @Param("example") UserPrivateLetterCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_private_letter
     *
     * @mbggenerated Sat Nov 26 19:39:03 CST 2016
     */
    int updateByPrimaryKeySelective(UserPrivateLetter record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_private_letter
     *
     * @mbggenerated Sat Nov 26 19:39:03 CST 2016
     */
    int updateByPrimaryKey(UserPrivateLetter record);
}