package com.ddas.sns.userblog.domain;

import java.io.Serializable;

public class UserBlog implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_blog.ub_id
     *
     * @mbggenerated Sun Jul 03 12:22:26 CST 2016
     */
    private String ubId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_blog.user_id
     *
     * @mbggenerated Sun Jul 03 12:22:26 CST 2016
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_blog.group_id
     *
     * @mbggenerated Sun Jul 03 12:22:26 CST 2016
     */
    private String groupId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_blog.blog_title
     *
     * @mbggenerated Sun Jul 03 12:22:26 CST 2016
     */
    private String blogTitle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_blog.blog_content
     *
     * @mbggenerated Sun Jul 03 12:22:26 CST 2016
     */
    private String blogContent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_blog.blog_privilege
     *
     * @mbggenerated Sun Jul 03 12:22:26 CST 2016
     */
    private String blogPrivilege;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_blog.blog_tags
     *
     * @mbggenerated Sun Jul 03 12:22:26 CST 2016
     */
    private String blogTags;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_blog.created_time
     *
     * @mbggenerated Sun Jul 03 12:22:26 CST 2016
     */
    private String createdTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_blog.updated_time
     *
     * @mbggenerated Sun Jul 03 12:22:26 CST 2016
     */
    private String updatedTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table user_blog
     *
     * @mbggenerated Sun Jul 03 12:22:26 CST 2016
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_blog.ub_id
     *
     * @return the value of user_blog.ub_id
     *
     * @mbggenerated Sun Jul 03 12:22:26 CST 2016
     */
    public String getUbId() {
        return ubId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_blog.ub_id
     *
     * @param ubId the value for user_blog.ub_id
     *
     * @mbggenerated Sun Jul 03 12:22:26 CST 2016
     */
    public void setUbId(String ubId) {
        this.ubId = ubId == null ? null : ubId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_blog.user_id
     *
     * @return the value of user_blog.user_id
     *
     * @mbggenerated Sun Jul 03 12:22:26 CST 2016
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_blog.user_id
     *
     * @param userId the value for user_blog.user_id
     *
     * @mbggenerated Sun Jul 03 12:22:26 CST 2016
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_blog.group_id
     *
     * @return the value of user_blog.group_id
     *
     * @mbggenerated Sun Jul 03 12:22:26 CST 2016
     */
    public String getGroupId() {
        return groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_blog.group_id
     *
     * @param groupId the value for user_blog.group_id
     *
     * @mbggenerated Sun Jul 03 12:22:26 CST 2016
     */
    public void setGroupId(String groupId) {
        this.groupId = groupId == null ? null : groupId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_blog.blog_title
     *
     * @return the value of user_blog.blog_title
     *
     * @mbggenerated Sun Jul 03 12:22:26 CST 2016
     */
    public String getBlogTitle() {
        return blogTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_blog.blog_title
     *
     * @param blogTitle the value for user_blog.blog_title
     *
     * @mbggenerated Sun Jul 03 12:22:26 CST 2016
     */
    public void setBlogTitle(String blogTitle) {
        this.blogTitle = blogTitle == null ? null : blogTitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_blog.blog_content
     *
     * @return the value of user_blog.blog_content
     *
     * @mbggenerated Sun Jul 03 12:22:26 CST 2016
     */
    public String getBlogContent() {
        return blogContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_blog.blog_content
     *
     * @param blogContent the value for user_blog.blog_content
     *
     * @mbggenerated Sun Jul 03 12:22:26 CST 2016
     */
    public void setBlogContent(String blogContent) {
        this.blogContent = blogContent == null ? null : blogContent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_blog.blog_privilege
     *
     * @return the value of user_blog.blog_privilege
     *
     * @mbggenerated Sun Jul 03 12:22:26 CST 2016
     */
    public String getBlogPrivilege() {
        return blogPrivilege;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_blog.blog_privilege
     *
     * @param blogPrivilege the value for user_blog.blog_privilege
     *
     * @mbggenerated Sun Jul 03 12:22:26 CST 2016
     */
    public void setBlogPrivilege(String blogPrivilege) {
        this.blogPrivilege = blogPrivilege == null ? null : blogPrivilege.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_blog.blog_tags
     *
     * @return the value of user_blog.blog_tags
     *
     * @mbggenerated Sun Jul 03 12:22:26 CST 2016
     */
    public String getBlogTags() {
        return blogTags;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_blog.blog_tags
     *
     * @param blogTags the value for user_blog.blog_tags
     *
     * @mbggenerated Sun Jul 03 12:22:26 CST 2016
     */
    public void setBlogTags(String blogTags) {
        this.blogTags = blogTags == null ? null : blogTags.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_blog.created_time
     *
     * @return the value of user_blog.created_time
     *
     * @mbggenerated Sun Jul 03 12:22:26 CST 2016
     */
    public String getCreatedTime() {
        return createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_blog.created_time
     *
     * @param createdTime the value for user_blog.created_time
     *
     * @mbggenerated Sun Jul 03 12:22:26 CST 2016
     */
    public void setCreatedTime(String createdTime) {
        this.createdTime = createdTime == null ? null : createdTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_blog.updated_time
     *
     * @return the value of user_blog.updated_time
     *
     * @mbggenerated Sun Jul 03 12:22:26 CST 2016
     */
    public String getUpdatedTime() {
        return updatedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_blog.updated_time
     *
     * @param updatedTime the value for user_blog.updated_time
     *
     * @mbggenerated Sun Jul 03 12:22:26 CST 2016
     */
    public void setUpdatedTime(String updatedTime) {
        this.updatedTime = updatedTime == null ? null : updatedTime.trim();
    }
}