package com.ddas.sns.userinfo.domain;

import java.io.Serializable;

public class UserInfo implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.memb_gagaid
     *
     * @mbggenerated Tue Nov 29 00:12:37 CST 2016
     */
    private String membGagaid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.memb_gagano
     *
     * @mbggenerated Tue Nov 29 00:12:37 CST 2016
     */
    private String membGagano;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.memb_light_gagano
     *
     * @mbggenerated Tue Nov 29 00:12:37 CST 2016
     */
    private String membLightGagano;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.memb_nickname
     *
     * @mbggenerated Tue Nov 29 00:12:37 CST 2016
     */
    private String membNickname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.memb_light_nickname
     *
     * @mbggenerated Tue Nov 29 00:12:37 CST 2016
     */
    private String membLightNickname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.memb_date
     *
     * @mbggenerated Tue Nov 29 00:12:37 CST 2016
     */
    private String membDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.memb_birth
     *
     * @mbggenerated Tue Nov 29 00:12:37 CST 2016
     */
    private String membBirth;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.memb_age
     *
     * @mbggenerated Tue Nov 29 00:12:37 CST 2016
     */
    private String membAge;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.memb_sex
     *
     * @mbggenerated Tue Nov 29 00:12:37 CST 2016
     */
    private String membSex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.memb_email
     *
     * @mbggenerated Tue Nov 29 00:12:37 CST 2016
     */
    private String membEmail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.memb_country
     *
     * @mbggenerated Tue Nov 29 00:12:37 CST 2016
     */
    private String membCountry;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.memb_language
     *
     * @mbggenerated Tue Nov 29 00:12:37 CST 2016
     */
    private String membLanguage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.memb_job
     *
     * @mbggenerated Tue Nov 29 00:12:37 CST 2016
     */
    private String membJob;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.memb_height
     *
     * @mbggenerated Tue Nov 29 00:12:37 CST 2016
     */
    private String membHeight;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.memb_pwd
     *
     * @mbggenerated Tue Nov 29 00:12:37 CST 2016
     */
    private String membPwd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.memb_weight
     *
     * @mbggenerated Tue Nov 29 00:12:37 CST 2016
     */
    private String membWeight;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.memb_bigimg
     *
     * @mbggenerated Tue Nov 29 00:12:37 CST 2016
     */
    private String membBigimg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.memb_registertime
     *
     * @mbggenerated Tue Nov 29 00:12:37 CST 2016
     */
    private String membRegistertime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.mefi_level
     *
     * @mbggenerated Tue Nov 29 00:12:37 CST 2016
     */
    private String mefiLevel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.mefi_isshowfirst
     *
     * @mbggenerated Tue Nov 29 00:12:37 CST 2016
     */
    private String mefiIsshowfirst;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.last_login
     *
     * @mbggenerated Tue Nov 29 00:12:37 CST 2016
     */
    private String lastLogin;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.if_online
     *
     * @mbggenerated Tue Nov 29 00:12:37 CST 2016
     */
    private String ifOnline;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.weight_val
     *
     * @mbggenerated Tue Nov 29 00:12:37 CST 2016
     */
    private String weightVal;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.is_hand
     *
     * @mbggenerated Tue Nov 29 00:12:37 CST 2016
     */
    private String isHand;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.memb_lable
     *
     * @mbggenerated Tue Nov 29 00:12:37 CST 2016
     */
    private String membLable;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.memb_country_code
     *
     * @mbggenerated Tue Nov 29 00:12:37 CST 2016
     */
    private String membCountryCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.memb_signature
     *
     * @mbggenerated Tue Nov 29 00:12:37 CST 2016
     */
    private String membSignature;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.memb_coin
     *
     * @mbggenerated Tue Nov 29 00:12:37 CST 2016
     */
    private String membCoin;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.memb_phone_no
     *
     * @mbggenerated Tue Nov 29 00:12:37 CST 2016
     */
    private String membPhoneNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.meco_isopenperson
     *
     * @mbggenerated Tue Nov 29 00:12:37 CST 2016
     */
    private String mecoIsopenperson;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.meco_isonline
     *
     * @mbggenerated Tue Nov 29 00:12:37 CST 2016
     */
    private String mecoIsonline;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.meco_isallowaddfriend
     *
     * @mbggenerated Tue Nov 29 00:12:37 CST 2016
     */
    private String mecoIsallowaddfriend;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.meco_isletter
     *
     * @mbggenerated Tue Nov 29 00:12:37 CST 2016
     */
    private String mecoIsletter;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.meco_islike
     *
     * @mbggenerated Tue Nov 29 00:12:37 CST 2016
     */
    private String mecoIslike;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.meco_isvisito
     *
     * @mbggenerated Tue Nov 29 00:12:37 CST 2016
     */
    private String mecoIsvisito;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.meco_isaddfriend
     *
     * @mbggenerated Tue Nov 29 00:12:37 CST 2016
     */
    private String mecoIsaddfriend;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.meco_isacceptgift
     *
     * @mbggenerated Tue Nov 29 00:12:37 CST 2016
     */
    private String mecoIsacceptgift;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.meco_iszone
     *
     * @mbggenerated Tue Nov 29 00:12:37 CST 2016
     */
    private String mecoIszone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.meco_isbuy
     *
     * @mbggenerated Tue Nov 29 00:12:37 CST 2016
     */
    private String mecoIsbuy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.meco_issound
     *
     * @mbggenerated Tue Nov 29 00:12:37 CST 2016
     */
    private String mecoIssound;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table user_info
     *
     * @mbggenerated Tue Nov 29 00:12:37 CST 2016
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.memb_gagaid
     *
     * @return the value of user_info.memb_gagaid
     *
     * @mbggenerated Tue Nov 29 00:12:37 CST 2016
     */
    public String getMembGagaid() {
        return membGagaid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.memb_gagaid
     *
     * @param membGagaid the value for user_info.memb_gagaid
     *
     * @mbggenerated Tue Nov 29 00:12:37 CST 2016
     */
    public void setMembGagaid(String membGagaid) {
        this.membGagaid = membGagaid == null ? null : membGagaid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.memb_gagano
     *
     * @return the value of user_info.memb_gagano
     *
     * @mbggenerated Tue Nov 29 00:12:37 CST 2016
     */
    public String getMembGagano() {
        return membGagano;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.memb_gagano
     *
     * @param membGagano the value for user_info.memb_gagano
     *
     * @mbggenerated Tue Nov 29 00:12:37 CST 2016
     */
    public void setMembGagano(String membGagano) {
        this.membGagano = membGagano == null ? null : membGagano.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.memb_light_gagano
     *
     * @return the value of user_info.memb_light_gagano
     *
     * @mbggenerated Tue Nov 29 00:12:37 CST 2016
     */
    public String getMembLightGagano() {
        return membLightGagano;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.memb_light_gagano
     *
     * @param membLightGagano the value for user_info.memb_light_gagano
     *
     * @mbggenerated Tue Nov 29 00:12:37 CST 2016
     */
    public void setMembLightGagano(String membLightGagano) {
        this.membLightGagano = membLightGagano == null ? null : membLightGagano.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.memb_nickname
     *
     * @return the value of user_info.memb_nickname
     *
     * @mbggenerated Tue Nov 29 00:12:37 CST 2016
     */
    public String getMembNickname() {
        return membNickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.memb_nickname
     *
     * @param membNickname the value for user_info.memb_nickname
     *
     * @mbggenerated Tue Nov 29 00:12:37 CST 2016
     */
    public void setMembNickname(String membNickname) {
        this.membNickname = membNickname == null ? null : membNickname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.memb_light_nickname
     *
     * @return the value of user_info.memb_light_nickname
     *
     * @mbggenerated Tue Nov 29 00:12:37 CST 2016
     */
    public String getMembLightNickname() {
        return membLightNickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.memb_light_nickname
     *
     * @param membLightNickname the value for user_info.memb_light_nickname
     *
     * @mbggenerated Tue Nov 29 00:12:37 CST 2016
     */
    public void setMembLightNickname(String membLightNickname) {
        this.membLightNickname = membLightNickname == null ? null : membLightNickname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.memb_date
     *
     * @return the value of user_info.memb_date
     *
     * @mbggenerated Tue Nov 29 00:12:37 CST 2016
     */
    public String getMembDate() {
        return membDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.memb_date
     *
     * @param membDate the value for user_info.memb_date
     *
     * @mbggenerated Tue Nov 29 00:12:37 CST 2016
     */
    public void setMembDate(String membDate) {
        this.membDate = membDate == null ? null : membDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.memb_birth
     *
     * @return the value of user_info.memb_birth
     *
     * @mbggenerated Tue Nov 29 00:12:37 CST 2016
     */
    public String getMembBirth() {
        return membBirth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.memb_birth
     *
     * @param membBirth the value for user_info.memb_birth
     *
     * @mbggenerated Tue Nov 29 00:12:37 CST 2016
     */
    public void setMembBirth(String membBirth) {
        this.membBirth = membBirth == null ? null : membBirth.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.memb_age
     *
     * @return the value of user_info.memb_age
     *
     * @mbggenerated Tue Nov 29 00:12:37 CST 2016
     */
    public String getMembAge() {
        return membAge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.memb_age
     *
     * @param membAge the value for user_info.memb_age
     *
     * @mbggenerated Tue Nov 29 00:12:37 CST 2016
     */
    public void setMembAge(String membAge) {
        this.membAge = membAge == null ? null : membAge.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.memb_sex
     *
     * @return the value of user_info.memb_sex
     *
     * @mbggenerated Tue Nov 29 00:12:37 CST 2016
     */
    public String getMembSex() {
        return membSex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.memb_sex
     *
     * @param membSex the value for user_info.memb_sex
     *
     * @mbggenerated Tue Nov 29 00:12:37 CST 2016
     */
    public void setMembSex(String membSex) {
        this.membSex = membSex == null ? null : membSex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.memb_email
     *
     * @return the value of user_info.memb_email
     *
     * @mbggenerated Tue Nov 29 00:12:37 CST 2016
     */
    public String getMembEmail() {
        return membEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.memb_email
     *
     * @param membEmail the value for user_info.memb_email
     *
     * @mbggenerated Tue Nov 29 00:12:37 CST 2016
     */
    public void setMembEmail(String membEmail) {
        this.membEmail = membEmail == null ? null : membEmail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.memb_country
     *
     * @return the value of user_info.memb_country
     *
     * @mbggenerated Tue Nov 29 00:12:37 CST 2016
     */
    public String getMembCountry() {
        return membCountry;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.memb_country
     *
     * @param membCountry the value for user_info.memb_country
     *
     * @mbggenerated Tue Nov 29 00:12:37 CST 2016
     */
    public void setMembCountry(String membCountry) {
        this.membCountry = membCountry == null ? null : membCountry.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.memb_language
     *
     * @return the value of user_info.memb_language
     *
     * @mbggenerated Tue Nov 29 00:12:37 CST 2016
     */
    public String getMembLanguage() {
        return membLanguage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.memb_language
     *
     * @param membLanguage the value for user_info.memb_language
     *
     * @mbggenerated Tue Nov 29 00:12:37 CST 2016
     */
    public void setMembLanguage(String membLanguage) {
        this.membLanguage = membLanguage == null ? null : membLanguage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.memb_job
     *
     * @return the value of user_info.memb_job
     *
     * @mbggenerated Tue Nov 29 00:12:37 CST 2016
     */
    public String getMembJob() {
        return membJob;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.memb_job
     *
     * @param membJob the value for user_info.memb_job
     *
     * @mbggenerated Tue Nov 29 00:12:37 CST 2016
     */
    public void setMembJob(String membJob) {
        this.membJob = membJob == null ? null : membJob.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.memb_height
     *
     * @return the value of user_info.memb_height
     *
     * @mbggenerated Tue Nov 29 00:12:37 CST 2016
     */
    public String getMembHeight() {
        return membHeight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.memb_height
     *
     * @param membHeight the value for user_info.memb_height
     *
     * @mbggenerated Tue Nov 29 00:12:37 CST 2016
     */
    public void setMembHeight(String membHeight) {
        this.membHeight = membHeight == null ? null : membHeight.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.memb_pwd
     *
     * @return the value of user_info.memb_pwd
     *
     * @mbggenerated Tue Nov 29 00:12:37 CST 2016
     */
    public String getMembPwd() {
        return membPwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.memb_pwd
     *
     * @param membPwd the value for user_info.memb_pwd
     *
     * @mbggenerated Tue Nov 29 00:12:37 CST 2016
     */
    public void setMembPwd(String membPwd) {
        this.membPwd = membPwd == null ? null : membPwd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.memb_weight
     *
     * @return the value of user_info.memb_weight
     *
     * @mbggenerated Tue Nov 29 00:12:37 CST 2016
     */
    public String getMembWeight() {
        return membWeight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.memb_weight
     *
     * @param membWeight the value for user_info.memb_weight
     *
     * @mbggenerated Tue Nov 29 00:12:37 CST 2016
     */
    public void setMembWeight(String membWeight) {
        this.membWeight = membWeight == null ? null : membWeight.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.memb_bigimg
     *
     * @return the value of user_info.memb_bigimg
     *
     * @mbggenerated Tue Nov 29 00:12:37 CST 2016
     */
    public String getMembBigimg() {
        return membBigimg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.memb_bigimg
     *
     * @param membBigimg the value for user_info.memb_bigimg
     *
     * @mbggenerated Tue Nov 29 00:12:37 CST 2016
     */
    public void setMembBigimg(String membBigimg) {
        this.membBigimg = membBigimg == null ? null : membBigimg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.memb_registertime
     *
     * @return the value of user_info.memb_registertime
     *
     * @mbggenerated Tue Nov 29 00:12:37 CST 2016
     */
    public String getMembRegistertime() {
        return membRegistertime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.memb_registertime
     *
     * @param membRegistertime the value for user_info.memb_registertime
     *
     * @mbggenerated Tue Nov 29 00:12:37 CST 2016
     */
    public void setMembRegistertime(String membRegistertime) {
        this.membRegistertime = membRegistertime == null ? null : membRegistertime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.mefi_level
     *
     * @return the value of user_info.mefi_level
     *
     * @mbggenerated Tue Nov 29 00:12:37 CST 2016
     */
    public String getMefiLevel() {
        return mefiLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.mefi_level
     *
     * @param mefiLevel the value for user_info.mefi_level
     *
     * @mbggenerated Tue Nov 29 00:12:37 CST 2016
     */
    public void setMefiLevel(String mefiLevel) {
        this.mefiLevel = mefiLevel == null ? null : mefiLevel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.mefi_isshowfirst
     *
     * @return the value of user_info.mefi_isshowfirst
     *
     * @mbggenerated Tue Nov 29 00:12:37 CST 2016
     */
    public String getMefiIsshowfirst() {
        return mefiIsshowfirst;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.mefi_isshowfirst
     *
     * @param mefiIsshowfirst the value for user_info.mefi_isshowfirst
     *
     * @mbggenerated Tue Nov 29 00:12:37 CST 2016
     */
    public void setMefiIsshowfirst(String mefiIsshowfirst) {
        this.mefiIsshowfirst = mefiIsshowfirst == null ? null : mefiIsshowfirst.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.last_login
     *
     * @return the value of user_info.last_login
     *
     * @mbggenerated Tue Nov 29 00:12:37 CST 2016
     */
    public String getLastLogin() {
        return lastLogin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.last_login
     *
     * @param lastLogin the value for user_info.last_login
     *
     * @mbggenerated Tue Nov 29 00:12:37 CST 2016
     */
    public void setLastLogin(String lastLogin) {
        this.lastLogin = lastLogin == null ? null : lastLogin.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.if_online
     *
     * @return the value of user_info.if_online
     *
     * @mbggenerated Tue Nov 29 00:12:37 CST 2016
     */
    public String getIfOnline() {
        return ifOnline;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.if_online
     *
     * @param ifOnline the value for user_info.if_online
     *
     * @mbggenerated Tue Nov 29 00:12:37 CST 2016
     */
    public void setIfOnline(String ifOnline) {
        this.ifOnline = ifOnline == null ? null : ifOnline.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.weight_val
     *
     * @return the value of user_info.weight_val
     *
     * @mbggenerated Tue Nov 29 00:12:37 CST 2016
     */
    public String getWeightVal() {
        return weightVal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.weight_val
     *
     * @param weightVal the value for user_info.weight_val
     *
     * @mbggenerated Tue Nov 29 00:12:37 CST 2016
     */
    public void setWeightVal(String weightVal) {
        this.weightVal = weightVal == null ? null : weightVal.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.is_hand
     *
     * @return the value of user_info.is_hand
     *
     * @mbggenerated Tue Nov 29 00:12:37 CST 2016
     */
    public String getIsHand() {
        return isHand;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.is_hand
     *
     * @param isHand the value for user_info.is_hand
     *
     * @mbggenerated Tue Nov 29 00:12:37 CST 2016
     */
    public void setIsHand(String isHand) {
        this.isHand = isHand == null ? null : isHand.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.memb_lable
     *
     * @return the value of user_info.memb_lable
     *
     * @mbggenerated Tue Nov 29 00:12:37 CST 2016
     */
    public String getMembLable() {
        return membLable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.memb_lable
     *
     * @param membLable the value for user_info.memb_lable
     *
     * @mbggenerated Tue Nov 29 00:12:37 CST 2016
     */
    public void setMembLable(String membLable) {
        this.membLable = membLable == null ? null : membLable.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.memb_country_code
     *
     * @return the value of user_info.memb_country_code
     *
     * @mbggenerated Tue Nov 29 00:12:37 CST 2016
     */
    public String getMembCountryCode() {
        return membCountryCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.memb_country_code
     *
     * @param membCountryCode the value for user_info.memb_country_code
     *
     * @mbggenerated Tue Nov 29 00:12:37 CST 2016
     */
    public void setMembCountryCode(String membCountryCode) {
        this.membCountryCode = membCountryCode == null ? null : membCountryCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.memb_signature
     *
     * @return the value of user_info.memb_signature
     *
     * @mbggenerated Tue Nov 29 00:12:37 CST 2016
     */
    public String getMembSignature() {
        return membSignature;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.memb_signature
     *
     * @param membSignature the value for user_info.memb_signature
     *
     * @mbggenerated Tue Nov 29 00:12:37 CST 2016
     */
    public void setMembSignature(String membSignature) {
        this.membSignature = membSignature == null ? null : membSignature.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.memb_coin
     *
     * @return the value of user_info.memb_coin
     *
     * @mbggenerated Tue Nov 29 00:12:37 CST 2016
     */
    public String getMembCoin() {
        return membCoin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.memb_coin
     *
     * @param membCoin the value for user_info.memb_coin
     *
     * @mbggenerated Tue Nov 29 00:12:37 CST 2016
     */
    public void setMembCoin(String membCoin) {
        this.membCoin = membCoin == null ? null : membCoin.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.memb_phone_no
     *
     * @return the value of user_info.memb_phone_no
     *
     * @mbggenerated Tue Nov 29 00:12:37 CST 2016
     */
    public String getMembPhoneNo() {
        return membPhoneNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.memb_phone_no
     *
     * @param membPhoneNo the value for user_info.memb_phone_no
     *
     * @mbggenerated Tue Nov 29 00:12:37 CST 2016
     */
    public void setMembPhoneNo(String membPhoneNo) {
        this.membPhoneNo = membPhoneNo == null ? null : membPhoneNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.meco_isopenperson
     *
     * @return the value of user_info.meco_isopenperson
     *
     * @mbggenerated Tue Nov 29 00:12:37 CST 2016
     */
    public String getMecoIsopenperson() {
        return mecoIsopenperson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.meco_isopenperson
     *
     * @param mecoIsopenperson the value for user_info.meco_isopenperson
     *
     * @mbggenerated Tue Nov 29 00:12:37 CST 2016
     */
    public void setMecoIsopenperson(String mecoIsopenperson) {
        this.mecoIsopenperson = mecoIsopenperson == null ? null : mecoIsopenperson.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.meco_isonline
     *
     * @return the value of user_info.meco_isonline
     *
     * @mbggenerated Tue Nov 29 00:12:37 CST 2016
     */
    public String getMecoIsonline() {
        return mecoIsonline;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.meco_isonline
     *
     * @param mecoIsonline the value for user_info.meco_isonline
     *
     * @mbggenerated Tue Nov 29 00:12:37 CST 2016
     */
    public void setMecoIsonline(String mecoIsonline) {
        this.mecoIsonline = mecoIsonline == null ? null : mecoIsonline.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.meco_isallowaddfriend
     *
     * @return the value of user_info.meco_isallowaddfriend
     *
     * @mbggenerated Tue Nov 29 00:12:37 CST 2016
     */
    public String getMecoIsallowaddfriend() {
        return mecoIsallowaddfriend;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.meco_isallowaddfriend
     *
     * @param mecoIsallowaddfriend the value for user_info.meco_isallowaddfriend
     *
     * @mbggenerated Tue Nov 29 00:12:37 CST 2016
     */
    public void setMecoIsallowaddfriend(String mecoIsallowaddfriend) {
        this.mecoIsallowaddfriend = mecoIsallowaddfriend == null ? null : mecoIsallowaddfriend.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.meco_isletter
     *
     * @return the value of user_info.meco_isletter
     *
     * @mbggenerated Tue Nov 29 00:12:37 CST 2016
     */
    public String getMecoIsletter() {
        return mecoIsletter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.meco_isletter
     *
     * @param mecoIsletter the value for user_info.meco_isletter
     *
     * @mbggenerated Tue Nov 29 00:12:37 CST 2016
     */
    public void setMecoIsletter(String mecoIsletter) {
        this.mecoIsletter = mecoIsletter == null ? null : mecoIsletter.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.meco_islike
     *
     * @return the value of user_info.meco_islike
     *
     * @mbggenerated Tue Nov 29 00:12:37 CST 2016
     */
    public String getMecoIslike() {
        return mecoIslike;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.meco_islike
     *
     * @param mecoIslike the value for user_info.meco_islike
     *
     * @mbggenerated Tue Nov 29 00:12:37 CST 2016
     */
    public void setMecoIslike(String mecoIslike) {
        this.mecoIslike = mecoIslike == null ? null : mecoIslike.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.meco_isvisito
     *
     * @return the value of user_info.meco_isvisito
     *
     * @mbggenerated Tue Nov 29 00:12:37 CST 2016
     */
    public String getMecoIsvisito() {
        return mecoIsvisito;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.meco_isvisito
     *
     * @param mecoIsvisito the value for user_info.meco_isvisito
     *
     * @mbggenerated Tue Nov 29 00:12:37 CST 2016
     */
    public void setMecoIsvisito(String mecoIsvisito) {
        this.mecoIsvisito = mecoIsvisito == null ? null : mecoIsvisito.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.meco_isaddfriend
     *
     * @return the value of user_info.meco_isaddfriend
     *
     * @mbggenerated Tue Nov 29 00:12:37 CST 2016
     */
    public String getMecoIsaddfriend() {
        return mecoIsaddfriend;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.meco_isaddfriend
     *
     * @param mecoIsaddfriend the value for user_info.meco_isaddfriend
     *
     * @mbggenerated Tue Nov 29 00:12:37 CST 2016
     */
    public void setMecoIsaddfriend(String mecoIsaddfriend) {
        this.mecoIsaddfriend = mecoIsaddfriend == null ? null : mecoIsaddfriend.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.meco_isacceptgift
     *
     * @return the value of user_info.meco_isacceptgift
     *
     * @mbggenerated Tue Nov 29 00:12:37 CST 2016
     */
    public String getMecoIsacceptgift() {
        return mecoIsacceptgift;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.meco_isacceptgift
     *
     * @param mecoIsacceptgift the value for user_info.meco_isacceptgift
     *
     * @mbggenerated Tue Nov 29 00:12:37 CST 2016
     */
    public void setMecoIsacceptgift(String mecoIsacceptgift) {
        this.mecoIsacceptgift = mecoIsacceptgift == null ? null : mecoIsacceptgift.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.meco_iszone
     *
     * @return the value of user_info.meco_iszone
     *
     * @mbggenerated Tue Nov 29 00:12:37 CST 2016
     */
    public String getMecoIszone() {
        return mecoIszone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.meco_iszone
     *
     * @param mecoIszone the value for user_info.meco_iszone
     *
     * @mbggenerated Tue Nov 29 00:12:37 CST 2016
     */
    public void setMecoIszone(String mecoIszone) {
        this.mecoIszone = mecoIszone == null ? null : mecoIszone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.meco_isbuy
     *
     * @return the value of user_info.meco_isbuy
     *
     * @mbggenerated Tue Nov 29 00:12:37 CST 2016
     */
    public String getMecoIsbuy() {
        return mecoIsbuy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.meco_isbuy
     *
     * @param mecoIsbuy the value for user_info.meco_isbuy
     *
     * @mbggenerated Tue Nov 29 00:12:37 CST 2016
     */
    public void setMecoIsbuy(String mecoIsbuy) {
        this.mecoIsbuy = mecoIsbuy == null ? null : mecoIsbuy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.meco_issound
     *
     * @return the value of user_info.meco_issound
     *
     * @mbggenerated Tue Nov 29 00:12:37 CST 2016
     */
    public String getMecoIssound() {
        return mecoIssound;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.meco_issound
     *
     * @param mecoIssound the value for user_info.meco_issound
     *
     * @mbggenerated Tue Nov 29 00:12:37 CST 2016
     */
    public void setMecoIssound(String mecoIssound) {
        this.mecoIssound = mecoIssound == null ? null : mecoIssound.trim();
    }
}