package com.ddas.sns.userinfo.domain;

import java.util.ArrayList;
import java.util.List;

public class UserInfoCriteria {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table user_info
     *
     * @mbggenerated Wed Nov 09 22:45:15 CST 2016
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table user_info
     *
     * @mbggenerated Wed Nov 09 22:45:15 CST 2016
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table user_info
     *
     * @mbggenerated Wed Nov 09 22:45:15 CST 2016
     */
    protected List<Criteria> oredCriteria;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table user_info
     *
     * @mbggenerated Wed Nov 09 22:45:15 CST 2016
     */
    protected int limitStart = -1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table user_info
     *
     * @mbggenerated Wed Nov 09 22:45:15 CST 2016
     */
    protected int limitEnd = -1;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbggenerated Wed Nov 09 22:45:15 CST 2016
     */
    public UserInfoCriteria() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbggenerated Wed Nov 09 22:45:15 CST 2016
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbggenerated Wed Nov 09 22:45:15 CST 2016
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbggenerated Wed Nov 09 22:45:15 CST 2016
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbggenerated Wed Nov 09 22:45:15 CST 2016
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbggenerated Wed Nov 09 22:45:15 CST 2016
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbggenerated Wed Nov 09 22:45:15 CST 2016
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbggenerated Wed Nov 09 22:45:15 CST 2016
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbggenerated Wed Nov 09 22:45:15 CST 2016
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbggenerated Wed Nov 09 22:45:15 CST 2016
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbggenerated Wed Nov 09 22:45:15 CST 2016
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbggenerated Wed Nov 09 22:45:15 CST 2016
     */
    public void setLimitStart(int limitStart) {
        this.limitStart=limitStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbggenerated Wed Nov 09 22:45:15 CST 2016
     */
    public int getLimitStart() {
        return limitStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbggenerated Wed Nov 09 22:45:15 CST 2016
     */
    public void setLimitEnd(int limitEnd) {
        this.limitEnd=limitEnd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbggenerated Wed Nov 09 22:45:15 CST 2016
     */
    public int getLimitEnd() {
        return limitEnd;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table user_info
     *
     * @mbggenerated Wed Nov 09 22:45:15 CST 2016
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andMembGagaidIsNull() {
            addCriterion("memb_gagaid is null");
            return (Criteria) this;
        }

        public Criteria andMembGagaidIsNotNull() {
            addCriterion("memb_gagaid is not null");
            return (Criteria) this;
        }

        public Criteria andMembGagaidEqualTo(String value) {
            addCriterion("memb_gagaid =", value, "membGagaid");
            return (Criteria) this;
        }

        public Criteria andMembGagaidNotEqualTo(String value) {
            addCriterion("memb_gagaid <>", value, "membGagaid");
            return (Criteria) this;
        }

        public Criteria andMembGagaidGreaterThan(String value) {
            addCriterion("memb_gagaid >", value, "membGagaid");
            return (Criteria) this;
        }

        public Criteria andMembGagaidGreaterThanOrEqualTo(String value) {
            addCriterion("memb_gagaid >=", value, "membGagaid");
            return (Criteria) this;
        }

        public Criteria andMembGagaidLessThan(String value) {
            addCriterion("memb_gagaid <", value, "membGagaid");
            return (Criteria) this;
        }

        public Criteria andMembGagaidLessThanOrEqualTo(String value) {
            addCriterion("memb_gagaid <=", value, "membGagaid");
            return (Criteria) this;
        }

        public Criteria andMembGagaidLike(String value) {
            addCriterion("memb_gagaid like", value, "membGagaid");
            return (Criteria) this;
        }

        public Criteria andMembGagaidNotLike(String value) {
            addCriterion("memb_gagaid not like", value, "membGagaid");
            return (Criteria) this;
        }

        public Criteria andMembGagaidIn(List<String> values) {
            addCriterion("memb_gagaid in", values, "membGagaid");
            return (Criteria) this;
        }

        public Criteria andMembGagaidNotIn(List<String> values) {
            addCriterion("memb_gagaid not in", values, "membGagaid");
            return (Criteria) this;
        }

        public Criteria andMembGagaidBetween(String value1, String value2) {
            addCriterion("memb_gagaid between", value1, value2, "membGagaid");
            return (Criteria) this;
        }

        public Criteria andMembGagaidNotBetween(String value1, String value2) {
            addCriterion("memb_gagaid not between", value1, value2, "membGagaid");
            return (Criteria) this;
        }

        public Criteria andMembGaganoIsNull() {
            addCriterion("memb_gagano is null");
            return (Criteria) this;
        }

        public Criteria andMembGaganoIsNotNull() {
            addCriterion("memb_gagano is not null");
            return (Criteria) this;
        }

        public Criteria andMembGaganoEqualTo(String value) {
            addCriterion("memb_gagano =", value, "membGagano");
            return (Criteria) this;
        }

        public Criteria andMembGaganoNotEqualTo(String value) {
            addCriterion("memb_gagano <>", value, "membGagano");
            return (Criteria) this;
        }

        public Criteria andMembGaganoGreaterThan(String value) {
            addCriterion("memb_gagano >", value, "membGagano");
            return (Criteria) this;
        }

        public Criteria andMembGaganoGreaterThanOrEqualTo(String value) {
            addCriterion("memb_gagano >=", value, "membGagano");
            return (Criteria) this;
        }

        public Criteria andMembGaganoLessThan(String value) {
            addCriterion("memb_gagano <", value, "membGagano");
            return (Criteria) this;
        }

        public Criteria andMembGaganoLessThanOrEqualTo(String value) {
            addCriterion("memb_gagano <=", value, "membGagano");
            return (Criteria) this;
        }

        public Criteria andMembGaganoLike(String value) {
            addCriterion("memb_gagano like", value, "membGagano");
            return (Criteria) this;
        }

        public Criteria andMembGaganoNotLike(String value) {
            addCriterion("memb_gagano not like", value, "membGagano");
            return (Criteria) this;
        }

        public Criteria andMembGaganoIn(List<String> values) {
            addCriterion("memb_gagano in", values, "membGagano");
            return (Criteria) this;
        }

        public Criteria andMembGaganoNotIn(List<String> values) {
            addCriterion("memb_gagano not in", values, "membGagano");
            return (Criteria) this;
        }

        public Criteria andMembGaganoBetween(String value1, String value2) {
            addCriterion("memb_gagano between", value1, value2, "membGagano");
            return (Criteria) this;
        }

        public Criteria andMembGaganoNotBetween(String value1, String value2) {
            addCriterion("memb_gagano not between", value1, value2, "membGagano");
            return (Criteria) this;
        }

        public Criteria andMembLightGaganoIsNull() {
            addCriterion("memb_light_gagano is null");
            return (Criteria) this;
        }

        public Criteria andMembLightGaganoIsNotNull() {
            addCriterion("memb_light_gagano is not null");
            return (Criteria) this;
        }

        public Criteria andMembLightGaganoEqualTo(String value) {
            addCriterion("memb_light_gagano =", value, "membLightGagano");
            return (Criteria) this;
        }

        public Criteria andMembLightGaganoNotEqualTo(String value) {
            addCriterion("memb_light_gagano <>", value, "membLightGagano");
            return (Criteria) this;
        }

        public Criteria andMembLightGaganoGreaterThan(String value) {
            addCriterion("memb_light_gagano >", value, "membLightGagano");
            return (Criteria) this;
        }

        public Criteria andMembLightGaganoGreaterThanOrEqualTo(String value) {
            addCriterion("memb_light_gagano >=", value, "membLightGagano");
            return (Criteria) this;
        }

        public Criteria andMembLightGaganoLessThan(String value) {
            addCriterion("memb_light_gagano <", value, "membLightGagano");
            return (Criteria) this;
        }

        public Criteria andMembLightGaganoLessThanOrEqualTo(String value) {
            addCriterion("memb_light_gagano <=", value, "membLightGagano");
            return (Criteria) this;
        }

        public Criteria andMembLightGaganoLike(String value) {
            addCriterion("memb_light_gagano like", value, "membLightGagano");
            return (Criteria) this;
        }

        public Criteria andMembLightGaganoNotLike(String value) {
            addCriterion("memb_light_gagano not like", value, "membLightGagano");
            return (Criteria) this;
        }

        public Criteria andMembLightGaganoIn(List<String> values) {
            addCriterion("memb_light_gagano in", values, "membLightGagano");
            return (Criteria) this;
        }

        public Criteria andMembLightGaganoNotIn(List<String> values) {
            addCriterion("memb_light_gagano not in", values, "membLightGagano");
            return (Criteria) this;
        }

        public Criteria andMembLightGaganoBetween(String value1, String value2) {
            addCriterion("memb_light_gagano between", value1, value2, "membLightGagano");
            return (Criteria) this;
        }

        public Criteria andMembLightGaganoNotBetween(String value1, String value2) {
            addCriterion("memb_light_gagano not between", value1, value2, "membLightGagano");
            return (Criteria) this;
        }

        public Criteria andMembNicknameIsNull() {
            addCriterion("memb_nickname is null");
            return (Criteria) this;
        }

        public Criteria andMembNicknameIsNotNull() {
            addCriterion("memb_nickname is not null");
            return (Criteria) this;
        }

        public Criteria andMembNicknameEqualTo(String value) {
            addCriterion("memb_nickname =", value, "membNickname");
            return (Criteria) this;
        }

        public Criteria andMembNicknameNotEqualTo(String value) {
            addCriterion("memb_nickname <>", value, "membNickname");
            return (Criteria) this;
        }

        public Criteria andMembNicknameGreaterThan(String value) {
            addCriterion("memb_nickname >", value, "membNickname");
            return (Criteria) this;
        }

        public Criteria andMembNicknameGreaterThanOrEqualTo(String value) {
            addCriterion("memb_nickname >=", value, "membNickname");
            return (Criteria) this;
        }

        public Criteria andMembNicknameLessThan(String value) {
            addCriterion("memb_nickname <", value, "membNickname");
            return (Criteria) this;
        }

        public Criteria andMembNicknameLessThanOrEqualTo(String value) {
            addCriterion("memb_nickname <=", value, "membNickname");
            return (Criteria) this;
        }

        public Criteria andMembNicknameLike(String value) {
            addCriterion("memb_nickname like", value, "membNickname");
            return (Criteria) this;
        }

        public Criteria andMembNicknameNotLike(String value) {
            addCriterion("memb_nickname not like", value, "membNickname");
            return (Criteria) this;
        }

        public Criteria andMembNicknameIn(List<String> values) {
            addCriterion("memb_nickname in", values, "membNickname");
            return (Criteria) this;
        }

        public Criteria andMembNicknameNotIn(List<String> values) {
            addCriterion("memb_nickname not in", values, "membNickname");
            return (Criteria) this;
        }

        public Criteria andMembNicknameBetween(String value1, String value2) {
            addCriterion("memb_nickname between", value1, value2, "membNickname");
            return (Criteria) this;
        }

        public Criteria andMembNicknameNotBetween(String value1, String value2) {
            addCriterion("memb_nickname not between", value1, value2, "membNickname");
            return (Criteria) this;
        }

        public Criteria andMembLightNicknameIsNull() {
            addCriterion("memb_light_nickname is null");
            return (Criteria) this;
        }

        public Criteria andMembLightNicknameIsNotNull() {
            addCriterion("memb_light_nickname is not null");
            return (Criteria) this;
        }

        public Criteria andMembLightNicknameEqualTo(String value) {
            addCriterion("memb_light_nickname =", value, "membLightNickname");
            return (Criteria) this;
        }

        public Criteria andMembLightNicknameNotEqualTo(String value) {
            addCriterion("memb_light_nickname <>", value, "membLightNickname");
            return (Criteria) this;
        }

        public Criteria andMembLightNicknameGreaterThan(String value) {
            addCriterion("memb_light_nickname >", value, "membLightNickname");
            return (Criteria) this;
        }

        public Criteria andMembLightNicknameGreaterThanOrEqualTo(String value) {
            addCriterion("memb_light_nickname >=", value, "membLightNickname");
            return (Criteria) this;
        }

        public Criteria andMembLightNicknameLessThan(String value) {
            addCriterion("memb_light_nickname <", value, "membLightNickname");
            return (Criteria) this;
        }

        public Criteria andMembLightNicknameLessThanOrEqualTo(String value) {
            addCriterion("memb_light_nickname <=", value, "membLightNickname");
            return (Criteria) this;
        }

        public Criteria andMembLightNicknameLike(String value) {
            addCriterion("memb_light_nickname like", value, "membLightNickname");
            return (Criteria) this;
        }

        public Criteria andMembLightNicknameNotLike(String value) {
            addCriterion("memb_light_nickname not like", value, "membLightNickname");
            return (Criteria) this;
        }

        public Criteria andMembLightNicknameIn(List<String> values) {
            addCriterion("memb_light_nickname in", values, "membLightNickname");
            return (Criteria) this;
        }

        public Criteria andMembLightNicknameNotIn(List<String> values) {
            addCriterion("memb_light_nickname not in", values, "membLightNickname");
            return (Criteria) this;
        }

        public Criteria andMembLightNicknameBetween(String value1, String value2) {
            addCriterion("memb_light_nickname between", value1, value2, "membLightNickname");
            return (Criteria) this;
        }

        public Criteria andMembLightNicknameNotBetween(String value1, String value2) {
            addCriterion("memb_light_nickname not between", value1, value2, "membLightNickname");
            return (Criteria) this;
        }

        public Criteria andMembDateIsNull() {
            addCriterion("memb_date is null");
            return (Criteria) this;
        }

        public Criteria andMembDateIsNotNull() {
            addCriterion("memb_date is not null");
            return (Criteria) this;
        }

        public Criteria andMembDateEqualTo(String value) {
            addCriterion("memb_date =", value, "membDate");
            return (Criteria) this;
        }

        public Criteria andMembDateNotEqualTo(String value) {
            addCriterion("memb_date <>", value, "membDate");
            return (Criteria) this;
        }

        public Criteria andMembDateGreaterThan(String value) {
            addCriterion("memb_date >", value, "membDate");
            return (Criteria) this;
        }

        public Criteria andMembDateGreaterThanOrEqualTo(String value) {
            addCriterion("memb_date >=", value, "membDate");
            return (Criteria) this;
        }

        public Criteria andMembDateLessThan(String value) {
            addCriterion("memb_date <", value, "membDate");
            return (Criteria) this;
        }

        public Criteria andMembDateLessThanOrEqualTo(String value) {
            addCriterion("memb_date <=", value, "membDate");
            return (Criteria) this;
        }

        public Criteria andMembDateLike(String value) {
            addCriterion("memb_date like", value, "membDate");
            return (Criteria) this;
        }

        public Criteria andMembDateNotLike(String value) {
            addCriterion("memb_date not like", value, "membDate");
            return (Criteria) this;
        }

        public Criteria andMembDateIn(List<String> values) {
            addCriterion("memb_date in", values, "membDate");
            return (Criteria) this;
        }

        public Criteria andMembDateNotIn(List<String> values) {
            addCriterion("memb_date not in", values, "membDate");
            return (Criteria) this;
        }

        public Criteria andMembDateBetween(String value1, String value2) {
            addCriterion("memb_date between", value1, value2, "membDate");
            return (Criteria) this;
        }

        public Criteria andMembDateNotBetween(String value1, String value2) {
            addCriterion("memb_date not between", value1, value2, "membDate");
            return (Criteria) this;
        }

        public Criteria andMembBirthIsNull() {
            addCriterion("memb_birth is null");
            return (Criteria) this;
        }

        public Criteria andMembBirthIsNotNull() {
            addCriterion("memb_birth is not null");
            return (Criteria) this;
        }

        public Criteria andMembBirthEqualTo(String value) {
            addCriterion("memb_birth =", value, "membBirth");
            return (Criteria) this;
        }

        public Criteria andMembBirthNotEqualTo(String value) {
            addCriterion("memb_birth <>", value, "membBirth");
            return (Criteria) this;
        }

        public Criteria andMembBirthGreaterThan(String value) {
            addCriterion("memb_birth >", value, "membBirth");
            return (Criteria) this;
        }

        public Criteria andMembBirthGreaterThanOrEqualTo(String value) {
            addCriterion("memb_birth >=", value, "membBirth");
            return (Criteria) this;
        }

        public Criteria andMembBirthLessThan(String value) {
            addCriterion("memb_birth <", value, "membBirth");
            return (Criteria) this;
        }

        public Criteria andMembBirthLessThanOrEqualTo(String value) {
            addCriterion("memb_birth <=", value, "membBirth");
            return (Criteria) this;
        }

        public Criteria andMembBirthLike(String value) {
            addCriterion("memb_birth like", value, "membBirth");
            return (Criteria) this;
        }

        public Criteria andMembBirthNotLike(String value) {
            addCriterion("memb_birth not like", value, "membBirth");
            return (Criteria) this;
        }

        public Criteria andMembBirthIn(List<String> values) {
            addCriterion("memb_birth in", values, "membBirth");
            return (Criteria) this;
        }

        public Criteria andMembBirthNotIn(List<String> values) {
            addCriterion("memb_birth not in", values, "membBirth");
            return (Criteria) this;
        }

        public Criteria andMembBirthBetween(String value1, String value2) {
            addCriterion("memb_birth between", value1, value2, "membBirth");
            return (Criteria) this;
        }

        public Criteria andMembBirthNotBetween(String value1, String value2) {
            addCriterion("memb_birth not between", value1, value2, "membBirth");
            return (Criteria) this;
        }

        public Criteria andMembAgeIsNull() {
            addCriterion("memb_age is null");
            return (Criteria) this;
        }

        public Criteria andMembAgeIsNotNull() {
            addCriterion("memb_age is not null");
            return (Criteria) this;
        }

        public Criteria andMembAgeEqualTo(String value) {
            addCriterion("memb_age =", value, "membAge");
            return (Criteria) this;
        }

        public Criteria andMembAgeNotEqualTo(String value) {
            addCriterion("memb_age <>", value, "membAge");
            return (Criteria) this;
        }

        public Criteria andMembAgeGreaterThan(String value) {
            addCriterion("memb_age >", value, "membAge");
            return (Criteria) this;
        }

        public Criteria andMembAgeGreaterThanOrEqualTo(String value) {
            addCriterion("memb_age >=", value, "membAge");
            return (Criteria) this;
        }

        public Criteria andMembAgeLessThan(String value) {
            addCriterion("memb_age <", value, "membAge");
            return (Criteria) this;
        }

        public Criteria andMembAgeLessThanOrEqualTo(String value) {
            addCriterion("memb_age <=", value, "membAge");
            return (Criteria) this;
        }

        public Criteria andMembAgeLike(String value) {
            addCriterion("memb_age like", value, "membAge");
            return (Criteria) this;
        }

        public Criteria andMembAgeNotLike(String value) {
            addCriterion("memb_age not like", value, "membAge");
            return (Criteria) this;
        }

        public Criteria andMembAgeIn(List<String> values) {
            addCriterion("memb_age in", values, "membAge");
            return (Criteria) this;
        }

        public Criteria andMembAgeNotIn(List<String> values) {
            addCriterion("memb_age not in", values, "membAge");
            return (Criteria) this;
        }

        public Criteria andMembAgeBetween(String value1, String value2) {
            addCriterion("memb_age between", value1, value2, "membAge");
            return (Criteria) this;
        }

        public Criteria andMembAgeNotBetween(String value1, String value2) {
            addCriterion("memb_age not between", value1, value2, "membAge");
            return (Criteria) this;
        }

        public Criteria andMembSexIsNull() {
            addCriterion("memb_sex is null");
            return (Criteria) this;
        }

        public Criteria andMembSexIsNotNull() {
            addCriterion("memb_sex is not null");
            return (Criteria) this;
        }

        public Criteria andMembSexEqualTo(String value) {
            addCriterion("memb_sex =", value, "membSex");
            return (Criteria) this;
        }

        public Criteria andMembSexNotEqualTo(String value) {
            addCriterion("memb_sex <>", value, "membSex");
            return (Criteria) this;
        }

        public Criteria andMembSexGreaterThan(String value) {
            addCriterion("memb_sex >", value, "membSex");
            return (Criteria) this;
        }

        public Criteria andMembSexGreaterThanOrEqualTo(String value) {
            addCriterion("memb_sex >=", value, "membSex");
            return (Criteria) this;
        }

        public Criteria andMembSexLessThan(String value) {
            addCriterion("memb_sex <", value, "membSex");
            return (Criteria) this;
        }

        public Criteria andMembSexLessThanOrEqualTo(String value) {
            addCriterion("memb_sex <=", value, "membSex");
            return (Criteria) this;
        }

        public Criteria andMembSexLike(String value) {
            addCriterion("memb_sex like", value, "membSex");
            return (Criteria) this;
        }

        public Criteria andMembSexNotLike(String value) {
            addCriterion("memb_sex not like", value, "membSex");
            return (Criteria) this;
        }

        public Criteria andMembSexIn(List<String> values) {
            addCriterion("memb_sex in", values, "membSex");
            return (Criteria) this;
        }

        public Criteria andMembSexNotIn(List<String> values) {
            addCriterion("memb_sex not in", values, "membSex");
            return (Criteria) this;
        }

        public Criteria andMembSexBetween(String value1, String value2) {
            addCriterion("memb_sex between", value1, value2, "membSex");
            return (Criteria) this;
        }

        public Criteria andMembSexNotBetween(String value1, String value2) {
            addCriterion("memb_sex not between", value1, value2, "membSex");
            return (Criteria) this;
        }

        public Criteria andMembEmailIsNull() {
            addCriterion("memb_email is null");
            return (Criteria) this;
        }

        public Criteria andMembEmailIsNotNull() {
            addCriterion("memb_email is not null");
            return (Criteria) this;
        }

        public Criteria andMembEmailEqualTo(String value) {
            addCriterion("memb_email =", value, "membEmail");
            return (Criteria) this;
        }

        public Criteria andMembEmailNotEqualTo(String value) {
            addCriterion("memb_email <>", value, "membEmail");
            return (Criteria) this;
        }

        public Criteria andMembEmailGreaterThan(String value) {
            addCriterion("memb_email >", value, "membEmail");
            return (Criteria) this;
        }

        public Criteria andMembEmailGreaterThanOrEqualTo(String value) {
            addCriterion("memb_email >=", value, "membEmail");
            return (Criteria) this;
        }

        public Criteria andMembEmailLessThan(String value) {
            addCriterion("memb_email <", value, "membEmail");
            return (Criteria) this;
        }

        public Criteria andMembEmailLessThanOrEqualTo(String value) {
            addCriterion("memb_email <=", value, "membEmail");
            return (Criteria) this;
        }

        public Criteria andMembEmailLike(String value) {
            addCriterion("memb_email like", value, "membEmail");
            return (Criteria) this;
        }

        public Criteria andMembEmailNotLike(String value) {
            addCriterion("memb_email not like", value, "membEmail");
            return (Criteria) this;
        }

        public Criteria andMembEmailIn(List<String> values) {
            addCriterion("memb_email in", values, "membEmail");
            return (Criteria) this;
        }

        public Criteria andMembEmailNotIn(List<String> values) {
            addCriterion("memb_email not in", values, "membEmail");
            return (Criteria) this;
        }

        public Criteria andMembEmailBetween(String value1, String value2) {
            addCriterion("memb_email between", value1, value2, "membEmail");
            return (Criteria) this;
        }

        public Criteria andMembEmailNotBetween(String value1, String value2) {
            addCriterion("memb_email not between", value1, value2, "membEmail");
            return (Criteria) this;
        }

        public Criteria andMembCountryIsNull() {
            addCriterion("memb_country is null");
            return (Criteria) this;
        }

        public Criteria andMembCountryIsNotNull() {
            addCriterion("memb_country is not null");
            return (Criteria) this;
        }

        public Criteria andMembCountryEqualTo(String value) {
            addCriterion("memb_country =", value, "membCountry");
            return (Criteria) this;
        }

        public Criteria andMembCountryNotEqualTo(String value) {
            addCriterion("memb_country <>", value, "membCountry");
            return (Criteria) this;
        }

        public Criteria andMembCountryGreaterThan(String value) {
            addCriterion("memb_country >", value, "membCountry");
            return (Criteria) this;
        }

        public Criteria andMembCountryGreaterThanOrEqualTo(String value) {
            addCriterion("memb_country >=", value, "membCountry");
            return (Criteria) this;
        }

        public Criteria andMembCountryLessThan(String value) {
            addCriterion("memb_country <", value, "membCountry");
            return (Criteria) this;
        }

        public Criteria andMembCountryLessThanOrEqualTo(String value) {
            addCriterion("memb_country <=", value, "membCountry");
            return (Criteria) this;
        }

        public Criteria andMembCountryLike(String value) {
            addCriterion("memb_country like", value, "membCountry");
            return (Criteria) this;
        }

        public Criteria andMembCountryNotLike(String value) {
            addCriterion("memb_country not like", value, "membCountry");
            return (Criteria) this;
        }

        public Criteria andMembCountryIn(List<String> values) {
            addCriterion("memb_country in", values, "membCountry");
            return (Criteria) this;
        }

        public Criteria andMembCountryNotIn(List<String> values) {
            addCriterion("memb_country not in", values, "membCountry");
            return (Criteria) this;
        }

        public Criteria andMembCountryBetween(String value1, String value2) {
            addCriterion("memb_country between", value1, value2, "membCountry");
            return (Criteria) this;
        }

        public Criteria andMembCountryNotBetween(String value1, String value2) {
            addCriterion("memb_country not between", value1, value2, "membCountry");
            return (Criteria) this;
        }

        public Criteria andMembLanguageIsNull() {
            addCriterion("memb_language is null");
            return (Criteria) this;
        }

        public Criteria andMembLanguageIsNotNull() {
            addCriterion("memb_language is not null");
            return (Criteria) this;
        }

        public Criteria andMembLanguageEqualTo(String value) {
            addCriterion("memb_language =", value, "membLanguage");
            return (Criteria) this;
        }

        public Criteria andMembLanguageNotEqualTo(String value) {
            addCriterion("memb_language <>", value, "membLanguage");
            return (Criteria) this;
        }

        public Criteria andMembLanguageGreaterThan(String value) {
            addCriterion("memb_language >", value, "membLanguage");
            return (Criteria) this;
        }

        public Criteria andMembLanguageGreaterThanOrEqualTo(String value) {
            addCriterion("memb_language >=", value, "membLanguage");
            return (Criteria) this;
        }

        public Criteria andMembLanguageLessThan(String value) {
            addCriterion("memb_language <", value, "membLanguage");
            return (Criteria) this;
        }

        public Criteria andMembLanguageLessThanOrEqualTo(String value) {
            addCriterion("memb_language <=", value, "membLanguage");
            return (Criteria) this;
        }

        public Criteria andMembLanguageLike(String value) {
            addCriterion("memb_language like", value, "membLanguage");
            return (Criteria) this;
        }

        public Criteria andMembLanguageNotLike(String value) {
            addCriterion("memb_language not like", value, "membLanguage");
            return (Criteria) this;
        }

        public Criteria andMembLanguageIn(List<String> values) {
            addCriterion("memb_language in", values, "membLanguage");
            return (Criteria) this;
        }

        public Criteria andMembLanguageNotIn(List<String> values) {
            addCriterion("memb_language not in", values, "membLanguage");
            return (Criteria) this;
        }

        public Criteria andMembLanguageBetween(String value1, String value2) {
            addCriterion("memb_language between", value1, value2, "membLanguage");
            return (Criteria) this;
        }

        public Criteria andMembLanguageNotBetween(String value1, String value2) {
            addCriterion("memb_language not between", value1, value2, "membLanguage");
            return (Criteria) this;
        }

        public Criteria andMembJobIsNull() {
            addCriterion("memb_job is null");
            return (Criteria) this;
        }

        public Criteria andMembJobIsNotNull() {
            addCriterion("memb_job is not null");
            return (Criteria) this;
        }

        public Criteria andMembJobEqualTo(String value) {
            addCriterion("memb_job =", value, "membJob");
            return (Criteria) this;
        }

        public Criteria andMembJobNotEqualTo(String value) {
            addCriterion("memb_job <>", value, "membJob");
            return (Criteria) this;
        }

        public Criteria andMembJobGreaterThan(String value) {
            addCriterion("memb_job >", value, "membJob");
            return (Criteria) this;
        }

        public Criteria andMembJobGreaterThanOrEqualTo(String value) {
            addCriterion("memb_job >=", value, "membJob");
            return (Criteria) this;
        }

        public Criteria andMembJobLessThan(String value) {
            addCriterion("memb_job <", value, "membJob");
            return (Criteria) this;
        }

        public Criteria andMembJobLessThanOrEqualTo(String value) {
            addCriterion("memb_job <=", value, "membJob");
            return (Criteria) this;
        }

        public Criteria andMembJobLike(String value) {
            addCriterion("memb_job like", value, "membJob");
            return (Criteria) this;
        }

        public Criteria andMembJobNotLike(String value) {
            addCriterion("memb_job not like", value, "membJob");
            return (Criteria) this;
        }

        public Criteria andMembJobIn(List<String> values) {
            addCriterion("memb_job in", values, "membJob");
            return (Criteria) this;
        }

        public Criteria andMembJobNotIn(List<String> values) {
            addCriterion("memb_job not in", values, "membJob");
            return (Criteria) this;
        }

        public Criteria andMembJobBetween(String value1, String value2) {
            addCriterion("memb_job between", value1, value2, "membJob");
            return (Criteria) this;
        }

        public Criteria andMembJobNotBetween(String value1, String value2) {
            addCriterion("memb_job not between", value1, value2, "membJob");
            return (Criteria) this;
        }

        public Criteria andMembHeightIsNull() {
            addCriterion("memb_height is null");
            return (Criteria) this;
        }

        public Criteria andMembHeightIsNotNull() {
            addCriterion("memb_height is not null");
            return (Criteria) this;
        }

        public Criteria andMembHeightEqualTo(String value) {
            addCriterion("memb_height =", value, "membHeight");
            return (Criteria) this;
        }

        public Criteria andMembHeightNotEqualTo(String value) {
            addCriterion("memb_height <>", value, "membHeight");
            return (Criteria) this;
        }

        public Criteria andMembHeightGreaterThan(String value) {
            addCriterion("memb_height >", value, "membHeight");
            return (Criteria) this;
        }

        public Criteria andMembHeightGreaterThanOrEqualTo(String value) {
            addCriterion("memb_height >=", value, "membHeight");
            return (Criteria) this;
        }

        public Criteria andMembHeightLessThan(String value) {
            addCriterion("memb_height <", value, "membHeight");
            return (Criteria) this;
        }

        public Criteria andMembHeightLessThanOrEqualTo(String value) {
            addCriterion("memb_height <=", value, "membHeight");
            return (Criteria) this;
        }

        public Criteria andMembHeightLike(String value) {
            addCriterion("memb_height like", value, "membHeight");
            return (Criteria) this;
        }

        public Criteria andMembHeightNotLike(String value) {
            addCriterion("memb_height not like", value, "membHeight");
            return (Criteria) this;
        }

        public Criteria andMembHeightIn(List<String> values) {
            addCriterion("memb_height in", values, "membHeight");
            return (Criteria) this;
        }

        public Criteria andMembHeightNotIn(List<String> values) {
            addCriterion("memb_height not in", values, "membHeight");
            return (Criteria) this;
        }

        public Criteria andMembHeightBetween(String value1, String value2) {
            addCriterion("memb_height between", value1, value2, "membHeight");
            return (Criteria) this;
        }

        public Criteria andMembHeightNotBetween(String value1, String value2) {
            addCriterion("memb_height not between", value1, value2, "membHeight");
            return (Criteria) this;
        }

        public Criteria andMembPwdIsNull() {
            addCriterion("memb_pwd is null");
            return (Criteria) this;
        }

        public Criteria andMembPwdIsNotNull() {
            addCriterion("memb_pwd is not null");
            return (Criteria) this;
        }

        public Criteria andMembPwdEqualTo(String value) {
            addCriterion("memb_pwd =", value, "membPwd");
            return (Criteria) this;
        }

        public Criteria andMembPwdNotEqualTo(String value) {
            addCriterion("memb_pwd <>", value, "membPwd");
            return (Criteria) this;
        }

        public Criteria andMembPwdGreaterThan(String value) {
            addCriterion("memb_pwd >", value, "membPwd");
            return (Criteria) this;
        }

        public Criteria andMembPwdGreaterThanOrEqualTo(String value) {
            addCriterion("memb_pwd >=", value, "membPwd");
            return (Criteria) this;
        }

        public Criteria andMembPwdLessThan(String value) {
            addCriterion("memb_pwd <", value, "membPwd");
            return (Criteria) this;
        }

        public Criteria andMembPwdLessThanOrEqualTo(String value) {
            addCriterion("memb_pwd <=", value, "membPwd");
            return (Criteria) this;
        }

        public Criteria andMembPwdLike(String value) {
            addCriterion("memb_pwd like", value, "membPwd");
            return (Criteria) this;
        }

        public Criteria andMembPwdNotLike(String value) {
            addCriterion("memb_pwd not like", value, "membPwd");
            return (Criteria) this;
        }

        public Criteria andMembPwdIn(List<String> values) {
            addCriterion("memb_pwd in", values, "membPwd");
            return (Criteria) this;
        }

        public Criteria andMembPwdNotIn(List<String> values) {
            addCriterion("memb_pwd not in", values, "membPwd");
            return (Criteria) this;
        }

        public Criteria andMembPwdBetween(String value1, String value2) {
            addCriterion("memb_pwd between", value1, value2, "membPwd");
            return (Criteria) this;
        }

        public Criteria andMembPwdNotBetween(String value1, String value2) {
            addCriterion("memb_pwd not between", value1, value2, "membPwd");
            return (Criteria) this;
        }

        public Criteria andMembWeightIsNull() {
            addCriterion("memb_weight is null");
            return (Criteria) this;
        }

        public Criteria andMembWeightIsNotNull() {
            addCriterion("memb_weight is not null");
            return (Criteria) this;
        }

        public Criteria andMembWeightEqualTo(String value) {
            addCriterion("memb_weight =", value, "membWeight");
            return (Criteria) this;
        }

        public Criteria andMembWeightNotEqualTo(String value) {
            addCriterion("memb_weight <>", value, "membWeight");
            return (Criteria) this;
        }

        public Criteria andMembWeightGreaterThan(String value) {
            addCriterion("memb_weight >", value, "membWeight");
            return (Criteria) this;
        }

        public Criteria andMembWeightGreaterThanOrEqualTo(String value) {
            addCriterion("memb_weight >=", value, "membWeight");
            return (Criteria) this;
        }

        public Criteria andMembWeightLessThan(String value) {
            addCriterion("memb_weight <", value, "membWeight");
            return (Criteria) this;
        }

        public Criteria andMembWeightLessThanOrEqualTo(String value) {
            addCriterion("memb_weight <=", value, "membWeight");
            return (Criteria) this;
        }

        public Criteria andMembWeightLike(String value) {
            addCriterion("memb_weight like", value, "membWeight");
            return (Criteria) this;
        }

        public Criteria andMembWeightNotLike(String value) {
            addCriterion("memb_weight not like", value, "membWeight");
            return (Criteria) this;
        }

        public Criteria andMembWeightIn(List<String> values) {
            addCriterion("memb_weight in", values, "membWeight");
            return (Criteria) this;
        }

        public Criteria andMembWeightNotIn(List<String> values) {
            addCriterion("memb_weight not in", values, "membWeight");
            return (Criteria) this;
        }

        public Criteria andMembWeightBetween(String value1, String value2) {
            addCriterion("memb_weight between", value1, value2, "membWeight");
            return (Criteria) this;
        }

        public Criteria andMembWeightNotBetween(String value1, String value2) {
            addCriterion("memb_weight not between", value1, value2, "membWeight");
            return (Criteria) this;
        }

        public Criteria andMembBigimgIsNull() {
            addCriterion("memb_bigimg is null");
            return (Criteria) this;
        }

        public Criteria andMembBigimgIsNotNull() {
            addCriterion("memb_bigimg is not null");
            return (Criteria) this;
        }

        public Criteria andMembBigimgEqualTo(String value) {
            addCriterion("memb_bigimg =", value, "membBigimg");
            return (Criteria) this;
        }

        public Criteria andMembBigimgNotEqualTo(String value) {
            addCriterion("memb_bigimg <>", value, "membBigimg");
            return (Criteria) this;
        }

        public Criteria andMembBigimgGreaterThan(String value) {
            addCriterion("memb_bigimg >", value, "membBigimg");
            return (Criteria) this;
        }

        public Criteria andMembBigimgGreaterThanOrEqualTo(String value) {
            addCriterion("memb_bigimg >=", value, "membBigimg");
            return (Criteria) this;
        }

        public Criteria andMembBigimgLessThan(String value) {
            addCriterion("memb_bigimg <", value, "membBigimg");
            return (Criteria) this;
        }

        public Criteria andMembBigimgLessThanOrEqualTo(String value) {
            addCriterion("memb_bigimg <=", value, "membBigimg");
            return (Criteria) this;
        }

        public Criteria andMembBigimgLike(String value) {
            addCriterion("memb_bigimg like", value, "membBigimg");
            return (Criteria) this;
        }

        public Criteria andMembBigimgNotLike(String value) {
            addCriterion("memb_bigimg not like", value, "membBigimg");
            return (Criteria) this;
        }

        public Criteria andMembBigimgIn(List<String> values) {
            addCriterion("memb_bigimg in", values, "membBigimg");
            return (Criteria) this;
        }

        public Criteria andMembBigimgNotIn(List<String> values) {
            addCriterion("memb_bigimg not in", values, "membBigimg");
            return (Criteria) this;
        }

        public Criteria andMembBigimgBetween(String value1, String value2) {
            addCriterion("memb_bigimg between", value1, value2, "membBigimg");
            return (Criteria) this;
        }

        public Criteria andMembBigimgNotBetween(String value1, String value2) {
            addCriterion("memb_bigimg not between", value1, value2, "membBigimg");
            return (Criteria) this;
        }

        public Criteria andMembRegistertimeIsNull() {
            addCriterion("memb_registertime is null");
            return (Criteria) this;
        }

        public Criteria andMembRegistertimeIsNotNull() {
            addCriterion("memb_registertime is not null");
            return (Criteria) this;
        }

        public Criteria andMembRegistertimeEqualTo(String value) {
            addCriterion("memb_registertime =", value, "membRegistertime");
            return (Criteria) this;
        }

        public Criteria andMembRegistertimeNotEqualTo(String value) {
            addCriterion("memb_registertime <>", value, "membRegistertime");
            return (Criteria) this;
        }

        public Criteria andMembRegistertimeGreaterThan(String value) {
            addCriterion("memb_registertime >", value, "membRegistertime");
            return (Criteria) this;
        }

        public Criteria andMembRegistertimeGreaterThanOrEqualTo(String value) {
            addCriterion("memb_registertime >=", value, "membRegistertime");
            return (Criteria) this;
        }

        public Criteria andMembRegistertimeLessThan(String value) {
            addCriterion("memb_registertime <", value, "membRegistertime");
            return (Criteria) this;
        }

        public Criteria andMembRegistertimeLessThanOrEqualTo(String value) {
            addCriterion("memb_registertime <=", value, "membRegistertime");
            return (Criteria) this;
        }

        public Criteria andMembRegistertimeLike(String value) {
            addCriterion("memb_registertime like", value, "membRegistertime");
            return (Criteria) this;
        }

        public Criteria andMembRegistertimeNotLike(String value) {
            addCriterion("memb_registertime not like", value, "membRegistertime");
            return (Criteria) this;
        }

        public Criteria andMembRegistertimeIn(List<String> values) {
            addCriterion("memb_registertime in", values, "membRegistertime");
            return (Criteria) this;
        }

        public Criteria andMembRegistertimeNotIn(List<String> values) {
            addCriterion("memb_registertime not in", values, "membRegistertime");
            return (Criteria) this;
        }

        public Criteria andMembRegistertimeBetween(String value1, String value2) {
            addCriterion("memb_registertime between", value1, value2, "membRegistertime");
            return (Criteria) this;
        }

        public Criteria andMembRegistertimeNotBetween(String value1, String value2) {
            addCriterion("memb_registertime not between", value1, value2, "membRegistertime");
            return (Criteria) this;
        }

        public Criteria andMefiLevelIsNull() {
            addCriterion("mefi_level is null");
            return (Criteria) this;
        }

        public Criteria andMefiLevelIsNotNull() {
            addCriterion("mefi_level is not null");
            return (Criteria) this;
        }

        public Criteria andMefiLevelEqualTo(String value) {
            addCriterion("mefi_level =", value, "mefiLevel");
            return (Criteria) this;
        }

        public Criteria andMefiLevelNotEqualTo(String value) {
            addCriterion("mefi_level <>", value, "mefiLevel");
            return (Criteria) this;
        }

        public Criteria andMefiLevelGreaterThan(String value) {
            addCriterion("mefi_level >", value, "mefiLevel");
            return (Criteria) this;
        }

        public Criteria andMefiLevelGreaterThanOrEqualTo(String value) {
            addCriterion("mefi_level >=", value, "mefiLevel");
            return (Criteria) this;
        }

        public Criteria andMefiLevelLessThan(String value) {
            addCriterion("mefi_level <", value, "mefiLevel");
            return (Criteria) this;
        }

        public Criteria andMefiLevelLessThanOrEqualTo(String value) {
            addCriterion("mefi_level <=", value, "mefiLevel");
            return (Criteria) this;
        }

        public Criteria andMefiLevelLike(String value) {
            addCriterion("mefi_level like", value, "mefiLevel");
            return (Criteria) this;
        }

        public Criteria andMefiLevelNotLike(String value) {
            addCriterion("mefi_level not like", value, "mefiLevel");
            return (Criteria) this;
        }

        public Criteria andMefiLevelIn(List<String> values) {
            addCriterion("mefi_level in", values, "mefiLevel");
            return (Criteria) this;
        }

        public Criteria andMefiLevelNotIn(List<String> values) {
            addCriterion("mefi_level not in", values, "mefiLevel");
            return (Criteria) this;
        }

        public Criteria andMefiLevelBetween(String value1, String value2) {
            addCriterion("mefi_level between", value1, value2, "mefiLevel");
            return (Criteria) this;
        }

        public Criteria andMefiLevelNotBetween(String value1, String value2) {
            addCriterion("mefi_level not between", value1, value2, "mefiLevel");
            return (Criteria) this;
        }

        public Criteria andMefiIsshowfirstIsNull() {
            addCriterion("mefi_isshowfirst is null");
            return (Criteria) this;
        }

        public Criteria andMefiIsshowfirstIsNotNull() {
            addCriterion("mefi_isshowfirst is not null");
            return (Criteria) this;
        }

        public Criteria andMefiIsshowfirstEqualTo(String value) {
            addCriterion("mefi_isshowfirst =", value, "mefiIsshowfirst");
            return (Criteria) this;
        }

        public Criteria andMefiIsshowfirstNotEqualTo(String value) {
            addCriterion("mefi_isshowfirst <>", value, "mefiIsshowfirst");
            return (Criteria) this;
        }

        public Criteria andMefiIsshowfirstGreaterThan(String value) {
            addCriterion("mefi_isshowfirst >", value, "mefiIsshowfirst");
            return (Criteria) this;
        }

        public Criteria andMefiIsshowfirstGreaterThanOrEqualTo(String value) {
            addCriterion("mefi_isshowfirst >=", value, "mefiIsshowfirst");
            return (Criteria) this;
        }

        public Criteria andMefiIsshowfirstLessThan(String value) {
            addCriterion("mefi_isshowfirst <", value, "mefiIsshowfirst");
            return (Criteria) this;
        }

        public Criteria andMefiIsshowfirstLessThanOrEqualTo(String value) {
            addCriterion("mefi_isshowfirst <=", value, "mefiIsshowfirst");
            return (Criteria) this;
        }

        public Criteria andMefiIsshowfirstLike(String value) {
            addCriterion("mefi_isshowfirst like", value, "mefiIsshowfirst");
            return (Criteria) this;
        }

        public Criteria andMefiIsshowfirstNotLike(String value) {
            addCriterion("mefi_isshowfirst not like", value, "mefiIsshowfirst");
            return (Criteria) this;
        }

        public Criteria andMefiIsshowfirstIn(List<String> values) {
            addCriterion("mefi_isshowfirst in", values, "mefiIsshowfirst");
            return (Criteria) this;
        }

        public Criteria andMefiIsshowfirstNotIn(List<String> values) {
            addCriterion("mefi_isshowfirst not in", values, "mefiIsshowfirst");
            return (Criteria) this;
        }

        public Criteria andMefiIsshowfirstBetween(String value1, String value2) {
            addCriterion("mefi_isshowfirst between", value1, value2, "mefiIsshowfirst");
            return (Criteria) this;
        }

        public Criteria andMefiIsshowfirstNotBetween(String value1, String value2) {
            addCriterion("mefi_isshowfirst not between", value1, value2, "mefiIsshowfirst");
            return (Criteria) this;
        }

        public Criteria andLastLoginIsNull() {
            addCriterion("last_login is null");
            return (Criteria) this;
        }

        public Criteria andLastLoginIsNotNull() {
            addCriterion("last_login is not null");
            return (Criteria) this;
        }

        public Criteria andLastLoginEqualTo(String value) {
            addCriterion("last_login =", value, "lastLogin");
            return (Criteria) this;
        }

        public Criteria andLastLoginNotEqualTo(String value) {
            addCriterion("last_login <>", value, "lastLogin");
            return (Criteria) this;
        }

        public Criteria andLastLoginGreaterThan(String value) {
            addCriterion("last_login >", value, "lastLogin");
            return (Criteria) this;
        }

        public Criteria andLastLoginGreaterThanOrEqualTo(String value) {
            addCriterion("last_login >=", value, "lastLogin");
            return (Criteria) this;
        }

        public Criteria andLastLoginLessThan(String value) {
            addCriterion("last_login <", value, "lastLogin");
            return (Criteria) this;
        }

        public Criteria andLastLoginLessThanOrEqualTo(String value) {
            addCriterion("last_login <=", value, "lastLogin");
            return (Criteria) this;
        }

        public Criteria andLastLoginLike(String value) {
            addCriterion("last_login like", value, "lastLogin");
            return (Criteria) this;
        }

        public Criteria andLastLoginNotLike(String value) {
            addCriterion("last_login not like", value, "lastLogin");
            return (Criteria) this;
        }

        public Criteria andLastLoginIn(List<String> values) {
            addCriterion("last_login in", values, "lastLogin");
            return (Criteria) this;
        }

        public Criteria andLastLoginNotIn(List<String> values) {
            addCriterion("last_login not in", values, "lastLogin");
            return (Criteria) this;
        }

        public Criteria andLastLoginBetween(String value1, String value2) {
            addCriterion("last_login between", value1, value2, "lastLogin");
            return (Criteria) this;
        }

        public Criteria andLastLoginNotBetween(String value1, String value2) {
            addCriterion("last_login not between", value1, value2, "lastLogin");
            return (Criteria) this;
        }

        public Criteria andIfOnlineIsNull() {
            addCriterion("if_online is null");
            return (Criteria) this;
        }

        public Criteria andIfOnlineIsNotNull() {
            addCriterion("if_online is not null");
            return (Criteria) this;
        }

        public Criteria andIfOnlineEqualTo(String value) {
            addCriterion("if_online =", value, "ifOnline");
            return (Criteria) this;
        }

        public Criteria andIfOnlineNotEqualTo(String value) {
            addCriterion("if_online <>", value, "ifOnline");
            return (Criteria) this;
        }

        public Criteria andIfOnlineGreaterThan(String value) {
            addCriterion("if_online >", value, "ifOnline");
            return (Criteria) this;
        }

        public Criteria andIfOnlineGreaterThanOrEqualTo(String value) {
            addCriterion("if_online >=", value, "ifOnline");
            return (Criteria) this;
        }

        public Criteria andIfOnlineLessThan(String value) {
            addCriterion("if_online <", value, "ifOnline");
            return (Criteria) this;
        }

        public Criteria andIfOnlineLessThanOrEqualTo(String value) {
            addCriterion("if_online <=", value, "ifOnline");
            return (Criteria) this;
        }

        public Criteria andIfOnlineLike(String value) {
            addCriterion("if_online like", value, "ifOnline");
            return (Criteria) this;
        }

        public Criteria andIfOnlineNotLike(String value) {
            addCriterion("if_online not like", value, "ifOnline");
            return (Criteria) this;
        }

        public Criteria andIfOnlineIn(List<String> values) {
            addCriterion("if_online in", values, "ifOnline");
            return (Criteria) this;
        }

        public Criteria andIfOnlineNotIn(List<String> values) {
            addCriterion("if_online not in", values, "ifOnline");
            return (Criteria) this;
        }

        public Criteria andIfOnlineBetween(String value1, String value2) {
            addCriterion("if_online between", value1, value2, "ifOnline");
            return (Criteria) this;
        }

        public Criteria andIfOnlineNotBetween(String value1, String value2) {
            addCriterion("if_online not between", value1, value2, "ifOnline");
            return (Criteria) this;
        }

        public Criteria andWeightValIsNull() {
            addCriterion("weight_val is null");
            return (Criteria) this;
        }

        public Criteria andWeightValIsNotNull() {
            addCriterion("weight_val is not null");
            return (Criteria) this;
        }

        public Criteria andWeightValEqualTo(String value) {
            addCriterion("weight_val =", value, "weightVal");
            return (Criteria) this;
        }

        public Criteria andWeightValNotEqualTo(String value) {
            addCriterion("weight_val <>", value, "weightVal");
            return (Criteria) this;
        }

        public Criteria andWeightValGreaterThan(String value) {
            addCriterion("weight_val >", value, "weightVal");
            return (Criteria) this;
        }

        public Criteria andWeightValGreaterThanOrEqualTo(String value) {
            addCriterion("weight_val >=", value, "weightVal");
            return (Criteria) this;
        }

        public Criteria andWeightValLessThan(String value) {
            addCriterion("weight_val <", value, "weightVal");
            return (Criteria) this;
        }

        public Criteria andWeightValLessThanOrEqualTo(String value) {
            addCriterion("weight_val <=", value, "weightVal");
            return (Criteria) this;
        }

        public Criteria andWeightValLike(String value) {
            addCriterion("weight_val like", value, "weightVal");
            return (Criteria) this;
        }

        public Criteria andWeightValNotLike(String value) {
            addCriterion("weight_val not like", value, "weightVal");
            return (Criteria) this;
        }

        public Criteria andWeightValIn(List<String> values) {
            addCriterion("weight_val in", values, "weightVal");
            return (Criteria) this;
        }

        public Criteria andWeightValNotIn(List<String> values) {
            addCriterion("weight_val not in", values, "weightVal");
            return (Criteria) this;
        }

        public Criteria andWeightValBetween(String value1, String value2) {
            addCriterion("weight_val between", value1, value2, "weightVal");
            return (Criteria) this;
        }

        public Criteria andWeightValNotBetween(String value1, String value2) {
            addCriterion("weight_val not between", value1, value2, "weightVal");
            return (Criteria) this;
        }

        public Criteria andIsHandIsNull() {
            addCriterion("is_hand is null");
            return (Criteria) this;
        }

        public Criteria andIsHandIsNotNull() {
            addCriterion("is_hand is not null");
            return (Criteria) this;
        }

        public Criteria andIsHandEqualTo(String value) {
            addCriterion("is_hand =", value, "isHand");
            return (Criteria) this;
        }

        public Criteria andIsHandNotEqualTo(String value) {
            addCriterion("is_hand <>", value, "isHand");
            return (Criteria) this;
        }

        public Criteria andIsHandGreaterThan(String value) {
            addCriterion("is_hand >", value, "isHand");
            return (Criteria) this;
        }

        public Criteria andIsHandGreaterThanOrEqualTo(String value) {
            addCriterion("is_hand >=", value, "isHand");
            return (Criteria) this;
        }

        public Criteria andIsHandLessThan(String value) {
            addCriterion("is_hand <", value, "isHand");
            return (Criteria) this;
        }

        public Criteria andIsHandLessThanOrEqualTo(String value) {
            addCriterion("is_hand <=", value, "isHand");
            return (Criteria) this;
        }

        public Criteria andIsHandLike(String value) {
            addCriterion("is_hand like", value, "isHand");
            return (Criteria) this;
        }

        public Criteria andIsHandNotLike(String value) {
            addCriterion("is_hand not like", value, "isHand");
            return (Criteria) this;
        }

        public Criteria andIsHandIn(List<String> values) {
            addCriterion("is_hand in", values, "isHand");
            return (Criteria) this;
        }

        public Criteria andIsHandNotIn(List<String> values) {
            addCriterion("is_hand not in", values, "isHand");
            return (Criteria) this;
        }

        public Criteria andIsHandBetween(String value1, String value2) {
            addCriterion("is_hand between", value1, value2, "isHand");
            return (Criteria) this;
        }

        public Criteria andIsHandNotBetween(String value1, String value2) {
            addCriterion("is_hand not between", value1, value2, "isHand");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table user_info
     *
     * @mbggenerated do_not_delete_during_merge Wed Nov 09 22:45:15 CST 2016
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }

        public Criteria andMembGagaidLikeInsensitive(String value) {
            addCriterion("upper(memb_gagaid) like", value.toUpperCase(), "membGagaid");
            return this;
        }

        public Criteria andMembGaganoLikeInsensitive(String value) {
            addCriterion("upper(memb_gagano) like", value.toUpperCase(), "membGagano");
            return this;
        }

        public Criteria andMembLightGaganoLikeInsensitive(String value) {
            addCriterion("upper(memb_light_gagano) like", value.toUpperCase(), "membLightGagano");
            return this;
        }

        public Criteria andMembNicknameLikeInsensitive(String value) {
            addCriterion("upper(memb_nickname) like", value.toUpperCase(), "membNickname");
            return this;
        }

        public Criteria andMembLightNicknameLikeInsensitive(String value) {
            addCriterion("upper(memb_light_nickname) like", value.toUpperCase(), "membLightNickname");
            return this;
        }

        public Criteria andMembDateLikeInsensitive(String value) {
            addCriterion("upper(memb_date) like", value.toUpperCase(), "membDate");
            return this;
        }

        public Criteria andMembBirthLikeInsensitive(String value) {
            addCriterion("upper(memb_birth) like", value.toUpperCase(), "membBirth");
            return this;
        }

        public Criteria andMembAgeLikeInsensitive(String value) {
            addCriterion("upper(memb_age) like", value.toUpperCase(), "membAge");
            return this;
        }

        public Criteria andMembSexLikeInsensitive(String value) {
            addCriterion("upper(memb_sex) like", value.toUpperCase(), "membSex");
            return this;
        }

        public Criteria andMembEmailLikeInsensitive(String value) {
            addCriterion("upper(memb_email) like", value.toUpperCase(), "membEmail");
            return this;
        }

        public Criteria andMembCountryLikeInsensitive(String value) {
            addCriterion("upper(memb_country) like", value.toUpperCase(), "membCountry");
            return this;
        }

        public Criteria andMembLanguageLikeInsensitive(String value) {
            addCriterion("upper(memb_language) like", value.toUpperCase(), "membLanguage");
            return this;
        }

        public Criteria andMembJobLikeInsensitive(String value) {
            addCriterion("upper(memb_job) like", value.toUpperCase(), "membJob");
            return this;
        }

        public Criteria andMembHeightLikeInsensitive(String value) {
            addCriterion("upper(memb_height) like", value.toUpperCase(), "membHeight");
            return this;
        }

        public Criteria andMembPwdLikeInsensitive(String value) {
            addCriterion("upper(memb_pwd) like", value.toUpperCase(), "membPwd");
            return this;
        }

        public Criteria andMembWeightLikeInsensitive(String value) {
            addCriterion("upper(memb_weight) like", value.toUpperCase(), "membWeight");
            return this;
        }

        public Criteria andMembBigimgLikeInsensitive(String value) {
            addCriterion("upper(memb_bigimg) like", value.toUpperCase(), "membBigimg");
            return this;
        }

        public Criteria andMembRegistertimeLikeInsensitive(String value) {
            addCriterion("upper(memb_registertime) like", value.toUpperCase(), "membRegistertime");
            return this;
        }

        public Criteria andMefiLevelLikeInsensitive(String value) {
            addCriterion("upper(mefi_level) like", value.toUpperCase(), "mefiLevel");
            return this;
        }

        public Criteria andMefiIsshowfirstLikeInsensitive(String value) {
            addCriterion("upper(mefi_isshowfirst) like", value.toUpperCase(), "mefiIsshowfirst");
            return this;
        }

        public Criteria andLastLoginLikeInsensitive(String value) {
            addCriterion("upper(last_login) like", value.toUpperCase(), "lastLogin");
            return this;
        }

        public Criteria andIfOnlineLikeInsensitive(String value) {
            addCriterion("upper(if_online) like", value.toUpperCase(), "ifOnline");
            return this;
        }

        public Criteria andWeightValLikeInsensitive(String value) {
            addCriterion("upper(weight_val) like", value.toUpperCase(), "weightVal");
            return this;
        }

        public Criteria andIsHandLikeInsensitive(String value) {
            addCriterion("upper(is_hand) like", value.toUpperCase(), "isHand");
            return this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table user_info
     *
     * @mbggenerated Wed Nov 09 22:45:15 CST 2016
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}