package com.ddas.sns.privateletter.domain;

import java.io.Serializable;

public class UserPrivateLetter implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_private_letter.id
     *
     * @mbggenerated Sat Nov 26 19:39:03 CST 2016
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_private_letter.sender_id
     *
     * @mbggenerated Sat Nov 26 19:39:03 CST 2016
     */
    private String senderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_private_letter.recive_id
     *
     * @mbggenerated Sat Nov 26 19:39:03 CST 2016
     */
    private String reciveId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_private_letter.letter_comment
     *
     * @mbggenerated Sat Nov 26 19:39:03 CST 2016
     */
    private String letterComment;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_private_letter.create_time
     *
     * @mbggenerated Sat Nov 26 19:39:03 CST 2016
     */
    private String createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_private_letter.is_read
     *
     * @mbggenerated Sat Nov 26 19:39:03 CST 2016
     */
    private String isRead;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table user_private_letter
     *
     * @mbggenerated Sat Nov 26 19:39:03 CST 2016
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_private_letter.id
     *
     * @return the value of user_private_letter.id
     *
     * @mbggenerated Sat Nov 26 19:39:03 CST 2016
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_private_letter.id
     *
     * @param id the value for user_private_letter.id
     *
     * @mbggenerated Sat Nov 26 19:39:03 CST 2016
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_private_letter.sender_id
     *
     * @return the value of user_private_letter.sender_id
     *
     * @mbggenerated Sat Nov 26 19:39:03 CST 2016
     */
    public String getSenderId() {
        return senderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_private_letter.sender_id
     *
     * @param senderId the value for user_private_letter.sender_id
     *
     * @mbggenerated Sat Nov 26 19:39:03 CST 2016
     */
    public void setSenderId(String senderId) {
        this.senderId = senderId == null ? null : senderId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_private_letter.recive_id
     *
     * @return the value of user_private_letter.recive_id
     *
     * @mbggenerated Sat Nov 26 19:39:03 CST 2016
     */
    public String getReciveId() {
        return reciveId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_private_letter.recive_id
     *
     * @param reciveId the value for user_private_letter.recive_id
     *
     * @mbggenerated Sat Nov 26 19:39:03 CST 2016
     */
    public void setReciveId(String reciveId) {
        this.reciveId = reciveId == null ? null : reciveId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_private_letter.letter_comment
     *
     * @return the value of user_private_letter.letter_comment
     *
     * @mbggenerated Sat Nov 26 19:39:03 CST 2016
     */
    public String getLetterComment() {
        return letterComment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_private_letter.letter_comment
     *
     * @param letterComment the value for user_private_letter.letter_comment
     *
     * @mbggenerated Sat Nov 26 19:39:03 CST 2016
     */
    public void setLetterComment(String letterComment) {
        this.letterComment = letterComment == null ? null : letterComment.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_private_letter.create_time
     *
     * @return the value of user_private_letter.create_time
     *
     * @mbggenerated Sat Nov 26 19:39:03 CST 2016
     */
    public String getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_private_letter.create_time
     *
     * @param createTime the value for user_private_letter.create_time
     *
     * @mbggenerated Sat Nov 26 19:39:03 CST 2016
     */
    public void setCreateTime(String createTime) {
        this.createTime = createTime == null ? null : createTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_private_letter.is_read
     *
     * @return the value of user_private_letter.is_read
     *
     * @mbggenerated Sat Nov 26 19:39:03 CST 2016
     */
    public String getIsRead() {
        return isRead;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_private_letter.is_read
     *
     * @param isRead the value for user_private_letter.is_read
     *
     * @mbggenerated Sat Nov 26 19:39:03 CST 2016
     */
    public void setIsRead(String isRead) {
        this.isRead = isRead == null ? null : isRead.trim();
    }
}