package com.ddas.sns.userinfo.mapper;

import com.ddas.sns.userinfo.domain.UserInfo;
import com.ddas.sns.userinfo.domain.UserInfoCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UserInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbggenerated Wed Nov 09 22:45:15 CST 2016
     */
    int countByExample(UserInfoCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbggenerated Wed Nov 09 22:45:15 CST 2016
     */
    int deleteByExample(UserInfoCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbggenerated Wed Nov 09 22:45:15 CST 2016
     */
    int deleteByPrimaryKey(String membGagaid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbggenerated Wed Nov 09 22:45:15 CST 2016
     */
    int insert(UserInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbggenerated Wed Nov 09 22:45:15 CST 2016
     */
    int insertSelective(UserInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbggenerated Wed Nov 09 22:45:15 CST 2016
     */
    List<UserInfo> selectByExample(UserInfoCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbggenerated Wed Nov 09 22:45:15 CST 2016
     */
    UserInfo selectByPrimaryKey(String membGagaid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbggenerated Wed Nov 09 22:45:15 CST 2016
     */
    int updateByExampleSelective(@Param("record") UserInfo record, @Param("example") UserInfoCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbggenerated Wed Nov 09 22:45:15 CST 2016
     */
    int updateByExample(@Param("record") UserInfo record, @Param("example") UserInfoCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbggenerated Wed Nov 09 22:45:15 CST 2016
     */
    int updateByPrimaryKeySelective(UserInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbggenerated Wed Nov 09 22:45:15 CST 2016
     */
    int updateByPrimaryKey(UserInfo record);
}