package com.ddas.sns.userlikesb.mapper;

import com.ddas.sns.userlikesb.domain.UserLikeSomebody;
import com.ddas.sns.userlikesb.domain.UserLikeSomebodyCriteria;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface UserLikeSomebodyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_like_sb
     *
     * @mbggenerated Sat Nov 12 22:24:35 CST 2016
     */
    int countByExample(UserLikeSomebodyCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_like_sb
     *
     * @mbggenerated Sat Nov 12 22:24:35 CST 2016
     */
    int deleteByExample(UserLikeSomebodyCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_like_sb
     *
     * @mbggenerated Sat Nov 12 22:24:35 CST 2016
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_like_sb
     *
     * @mbggenerated Sat Nov 12 22:24:35 CST 2016
     */
    int insert(UserLikeSomebody record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_like_sb
     *
     * @mbggenerated Sat Nov 12 22:24:35 CST 2016
     */
    int insertSelective(UserLikeSomebody record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_like_sb
     *
     * @mbggenerated Sat Nov 12 22:24:35 CST 2016
     */
    List<UserLikeSomebody> selectByExample(UserLikeSomebodyCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_like_sb
     *
     * @mbggenerated Sat Nov 12 22:24:35 CST 2016
     */
    UserLikeSomebody selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_like_sb
     *
     * @mbggenerated Sat Nov 12 22:24:35 CST 2016
     */
    int updateByExampleSelective(@Param("record") UserLikeSomebody record, @Param("example") UserLikeSomebodyCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_like_sb
     *
     * @mbggenerated Sat Nov 12 22:24:35 CST 2016
     */
    int updateByExample(@Param("record") UserLikeSomebody record, @Param("example") UserLikeSomebodyCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_like_sb
     *
     * @mbggenerated Sat Nov 12 22:24:35 CST 2016
     */
    int updateByPrimaryKeySelective(UserLikeSomebody record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_like_sb
     *
     * @mbggenerated Sat Nov 12 22:24:35 CST 2016
     */
    int updateByPrimaryKey(UserLikeSomebody record);
}