package com.ddas.sns.blogcomment.domain;

import java.io.Serializable;

public class BlogComment implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_comment.blog_comment_id
     *
     * @mbggenerated Sun Jul 10 13:28:43 CST 2016
     */
    private String blogCommentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_comment.blog_id
     *
     * @mbggenerated Sun Jul 10 13:28:43 CST 2016
     */
    private String blogId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_comment.comment_user_id
     *
     * @mbggenerated Sun Jul 10 13:28:43 CST 2016
     */
    private String commentUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_comment.comment_content
     *
     * @mbggenerated Sun Jul 10 13:28:43 CST 2016
     */
    private String commentContent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_comment.comment_parent_id
     *
     * @mbggenerated Sun Jul 10 13:28:43 CST 2016
     */
    private String commentParentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_comment.comment_time
     *
     * @mbggenerated Sun Jul 10 13:28:43 CST 2016
     */
    private String commentTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table blog_comment
     *
     * @mbggenerated Sun Jul 10 13:28:43 CST 2016
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_comment.blog_comment_id
     *
     * @return the value of blog_comment.blog_comment_id
     *
     * @mbggenerated Sun Jul 10 13:28:43 CST 2016
     */
    public String getBlogCommentId() {
        return blogCommentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_comment.blog_comment_id
     *
     * @param blogCommentId the value for blog_comment.blog_comment_id
     *
     * @mbggenerated Sun Jul 10 13:28:43 CST 2016
     */
    public void setBlogCommentId(String blogCommentId) {
        this.blogCommentId = blogCommentId == null ? null : blogCommentId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_comment.blog_id
     *
     * @return the value of blog_comment.blog_id
     *
     * @mbggenerated Sun Jul 10 13:28:43 CST 2016
     */
    public String getBlogId() {
        return blogId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_comment.blog_id
     *
     * @param blogId the value for blog_comment.blog_id
     *
     * @mbggenerated Sun Jul 10 13:28:43 CST 2016
     */
    public void setBlogId(String blogId) {
        this.blogId = blogId == null ? null : blogId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_comment.comment_user_id
     *
     * @return the value of blog_comment.comment_user_id
     *
     * @mbggenerated Sun Jul 10 13:28:43 CST 2016
     */
    public String getCommentUserId() {
        return commentUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_comment.comment_user_id
     *
     * @param commentUserId the value for blog_comment.comment_user_id
     *
     * @mbggenerated Sun Jul 10 13:28:43 CST 2016
     */
    public void setCommentUserId(String commentUserId) {
        this.commentUserId = commentUserId == null ? null : commentUserId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_comment.comment_content
     *
     * @return the value of blog_comment.comment_content
     *
     * @mbggenerated Sun Jul 10 13:28:43 CST 2016
     */
    public String getCommentContent() {
        return commentContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_comment.comment_content
     *
     * @param commentContent the value for blog_comment.comment_content
     *
     * @mbggenerated Sun Jul 10 13:28:43 CST 2016
     */
    public void setCommentContent(String commentContent) {
        this.commentContent = commentContent == null ? null : commentContent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_comment.comment_parent_id
     *
     * @return the value of blog_comment.comment_parent_id
     *
     * @mbggenerated Sun Jul 10 13:28:43 CST 2016
     */
    public String getCommentParentId() {
        return commentParentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_comment.comment_parent_id
     *
     * @param commentParentId the value for blog_comment.comment_parent_id
     *
     * @mbggenerated Sun Jul 10 13:28:43 CST 2016
     */
    public void setCommentParentId(String commentParentId) {
        this.commentParentId = commentParentId == null ? null : commentParentId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_comment.comment_time
     *
     * @return the value of blog_comment.comment_time
     *
     * @mbggenerated Sun Jul 10 13:28:43 CST 2016
     */
    public String getCommentTime() {
        return commentTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_comment.comment_time
     *
     * @param commentTime the value for blog_comment.comment_time
     *
     * @mbggenerated Sun Jul 10 13:28:43 CST 2016
     */
    public void setCommentTime(String commentTime) {
        this.commentTime = commentTime == null ? null : commentTime.trim();
    }
}