package com.ddas.sns.vip.domain;

import java.io.Serializable;

public class UserVipInfo implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_vip_info.vip_info_id
     *
     * @mbggenerated Fri Aug 12 22:17:40 CST 2016
     */
    private String vipInfoId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_vip_info.user_id
     *
     * @mbggenerated Fri Aug 12 22:17:40 CST 2016
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_vip_info.vip_type_code
     *
     * @mbggenerated Fri Aug 12 22:17:40 CST 2016
     */
    private String vipTypeCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_vip_info.vip_start_date
     *
     * @mbggenerated Fri Aug 12 22:17:40 CST 2016
     */
    private String vipStartDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_vip_info.vip_end_start
     *
     * @mbggenerated Fri Aug 12 22:17:40 CST 2016
     */
    private String vipEndStart;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_vip_info.describ
     *
     * @mbggenerated Fri Aug 12 22:17:40 CST 2016
     */
    private String describ;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table user_vip_info
     *
     * @mbggenerated Fri Aug 12 22:17:40 CST 2016
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_vip_info.vip_info_id
     *
     * @return the value of user_vip_info.vip_info_id
     *
     * @mbggenerated Fri Aug 12 22:17:40 CST 2016
     */
    public String getVipInfoId() {
        return vipInfoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_vip_info.vip_info_id
     *
     * @param vipInfoId the value for user_vip_info.vip_info_id
     *
     * @mbggenerated Fri Aug 12 22:17:40 CST 2016
     */
    public void setVipInfoId(String vipInfoId) {
        this.vipInfoId = vipInfoId == null ? null : vipInfoId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_vip_info.user_id
     *
     * @return the value of user_vip_info.user_id
     *
     * @mbggenerated Fri Aug 12 22:17:40 CST 2016
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_vip_info.user_id
     *
     * @param userId the value for user_vip_info.user_id
     *
     * @mbggenerated Fri Aug 12 22:17:40 CST 2016
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_vip_info.vip_type_code
     *
     * @return the value of user_vip_info.vip_type_code
     *
     * @mbggenerated Fri Aug 12 22:17:40 CST 2016
     */
    public String getVipTypeCode() {
        return vipTypeCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_vip_info.vip_type_code
     *
     * @param vipTypeCode the value for user_vip_info.vip_type_code
     *
     * @mbggenerated Fri Aug 12 22:17:40 CST 2016
     */
    public void setVipTypeCode(String vipTypeCode) {
        this.vipTypeCode = vipTypeCode == null ? null : vipTypeCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_vip_info.vip_start_date
     *
     * @return the value of user_vip_info.vip_start_date
     *
     * @mbggenerated Fri Aug 12 22:17:40 CST 2016
     */
    public String getVipStartDate() {
        return vipStartDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_vip_info.vip_start_date
     *
     * @param vipStartDate the value for user_vip_info.vip_start_date
     *
     * @mbggenerated Fri Aug 12 22:17:40 CST 2016
     */
    public void setVipStartDate(String vipStartDate) {
        this.vipStartDate = vipStartDate == null ? null : vipStartDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_vip_info.vip_end_start
     *
     * @return the value of user_vip_info.vip_end_start
     *
     * @mbggenerated Fri Aug 12 22:17:40 CST 2016
     */
    public String getVipEndStart() {
        return vipEndStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_vip_info.vip_end_start
     *
     * @param vipEndStart the value for user_vip_info.vip_end_start
     *
     * @mbggenerated Fri Aug 12 22:17:40 CST 2016
     */
    public void setVipEndStart(String vipEndStart) {
        this.vipEndStart = vipEndStart == null ? null : vipEndStart.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_vip_info.describ
     *
     * @return the value of user_vip_info.describ
     *
     * @mbggenerated Fri Aug 12 22:17:40 CST 2016
     */
    public String getDescrib() {
        return describ;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_vip_info.describ
     *
     * @param describ the value for user_vip_info.describ
     *
     * @mbggenerated Fri Aug 12 22:17:40 CST 2016
     */
    public void setDescrib(String describ) {
        this.describ = describ == null ? null : describ.trim();
    }
}