package com.ddas.sns.vip.domain;

import java.util.ArrayList;
import java.util.List;

public class VipRechargeRecordCriteria {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table vip_recharge_records
     *
     * @mbggenerated Tue Sep 06 20:57:55 CST 2016
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table vip_recharge_records
     *
     * @mbggenerated Tue Sep 06 20:57:55 CST 2016
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table vip_recharge_records
     *
     * @mbggenerated Tue Sep 06 20:57:55 CST 2016
     */
    protected List<Criteria> oredCriteria;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table vip_recharge_records
     *
     * @mbggenerated Tue Sep 06 20:57:55 CST 2016
     */
    protected int limitStart = -1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table vip_recharge_records
     *
     * @mbggenerated Tue Sep 06 20:57:55 CST 2016
     */
    protected int limitEnd = -1;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vip_recharge_records
     *
     * @mbggenerated Tue Sep 06 20:57:55 CST 2016
     */
    public VipRechargeRecordCriteria() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vip_recharge_records
     *
     * @mbggenerated Tue Sep 06 20:57:55 CST 2016
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vip_recharge_records
     *
     * @mbggenerated Tue Sep 06 20:57:55 CST 2016
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vip_recharge_records
     *
     * @mbggenerated Tue Sep 06 20:57:55 CST 2016
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vip_recharge_records
     *
     * @mbggenerated Tue Sep 06 20:57:55 CST 2016
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vip_recharge_records
     *
     * @mbggenerated Tue Sep 06 20:57:55 CST 2016
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vip_recharge_records
     *
     * @mbggenerated Tue Sep 06 20:57:55 CST 2016
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vip_recharge_records
     *
     * @mbggenerated Tue Sep 06 20:57:55 CST 2016
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vip_recharge_records
     *
     * @mbggenerated Tue Sep 06 20:57:55 CST 2016
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vip_recharge_records
     *
     * @mbggenerated Tue Sep 06 20:57:55 CST 2016
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vip_recharge_records
     *
     * @mbggenerated Tue Sep 06 20:57:55 CST 2016
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vip_recharge_records
     *
     * @mbggenerated Tue Sep 06 20:57:55 CST 2016
     */
    public void setLimitStart(int limitStart) {
        this.limitStart=limitStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vip_recharge_records
     *
     * @mbggenerated Tue Sep 06 20:57:55 CST 2016
     */
    public int getLimitStart() {
        return limitStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vip_recharge_records
     *
     * @mbggenerated Tue Sep 06 20:57:55 CST 2016
     */
    public void setLimitEnd(int limitEnd) {
        this.limitEnd=limitEnd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vip_recharge_records
     *
     * @mbggenerated Tue Sep 06 20:57:55 CST 2016
     */
    public int getLimitEnd() {
        return limitEnd;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table vip_recharge_records
     *
     * @mbggenerated Tue Sep 06 20:57:55 CST 2016
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andRecordsIdIsNull() {
            addCriterion("records_id is null");
            return (Criteria) this;
        }

        public Criteria andRecordsIdIsNotNull() {
            addCriterion("records_id is not null");
            return (Criteria) this;
        }

        public Criteria andRecordsIdEqualTo(String value) {
            addCriterion("records_id =", value, "recordsId");
            return (Criteria) this;
        }

        public Criteria andRecordsIdNotEqualTo(String value) {
            addCriterion("records_id <>", value, "recordsId");
            return (Criteria) this;
        }

        public Criteria andRecordsIdGreaterThan(String value) {
            addCriterion("records_id >", value, "recordsId");
            return (Criteria) this;
        }

        public Criteria andRecordsIdGreaterThanOrEqualTo(String value) {
            addCriterion("records_id >=", value, "recordsId");
            return (Criteria) this;
        }

        public Criteria andRecordsIdLessThan(String value) {
            addCriterion("records_id <", value, "recordsId");
            return (Criteria) this;
        }

        public Criteria andRecordsIdLessThanOrEqualTo(String value) {
            addCriterion("records_id <=", value, "recordsId");
            return (Criteria) this;
        }

        public Criteria andRecordsIdLike(String value) {
            addCriterion("records_id like", value, "recordsId");
            return (Criteria) this;
        }

        public Criteria andRecordsIdNotLike(String value) {
            addCriterion("records_id not like", value, "recordsId");
            return (Criteria) this;
        }

        public Criteria andRecordsIdIn(List<String> values) {
            addCriterion("records_id in", values, "recordsId");
            return (Criteria) this;
        }

        public Criteria andRecordsIdNotIn(List<String> values) {
            addCriterion("records_id not in", values, "recordsId");
            return (Criteria) this;
        }

        public Criteria andRecordsIdBetween(String value1, String value2) {
            addCriterion("records_id between", value1, value2, "recordsId");
            return (Criteria) this;
        }

        public Criteria andRecordsIdNotBetween(String value1, String value2) {
            addCriterion("records_id not between", value1, value2, "recordsId");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNull() {
            addCriterion("user_id is null");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNotNull() {
            addCriterion("user_id is not null");
            return (Criteria) this;
        }

        public Criteria andUserIdEqualTo(String value) {
            addCriterion("user_id =", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotEqualTo(String value) {
            addCriterion("user_id <>", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThan(String value) {
            addCriterion("user_id >", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThanOrEqualTo(String value) {
            addCriterion("user_id >=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThan(String value) {
            addCriterion("user_id <", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThanOrEqualTo(String value) {
            addCriterion("user_id <=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLike(String value) {
            addCriterion("user_id like", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotLike(String value) {
            addCriterion("user_id not like", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdIn(List<String> values) {
            addCriterion("user_id in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotIn(List<String> values) {
            addCriterion("user_id not in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdBetween(String value1, String value2) {
            addCriterion("user_id between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotBetween(String value1, String value2) {
            addCriterion("user_id not between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andRechargeToUserIsNull() {
            addCriterion("recharge_to_user is null");
            return (Criteria) this;
        }

        public Criteria andRechargeToUserIsNotNull() {
            addCriterion("recharge_to_user is not null");
            return (Criteria) this;
        }

        public Criteria andRechargeToUserEqualTo(String value) {
            addCriterion("recharge_to_user =", value, "rechargeToUser");
            return (Criteria) this;
        }

        public Criteria andRechargeToUserNotEqualTo(String value) {
            addCriterion("recharge_to_user <>", value, "rechargeToUser");
            return (Criteria) this;
        }

        public Criteria andRechargeToUserGreaterThan(String value) {
            addCriterion("recharge_to_user >", value, "rechargeToUser");
            return (Criteria) this;
        }

        public Criteria andRechargeToUserGreaterThanOrEqualTo(String value) {
            addCriterion("recharge_to_user >=", value, "rechargeToUser");
            return (Criteria) this;
        }

        public Criteria andRechargeToUserLessThan(String value) {
            addCriterion("recharge_to_user <", value, "rechargeToUser");
            return (Criteria) this;
        }

        public Criteria andRechargeToUserLessThanOrEqualTo(String value) {
            addCriterion("recharge_to_user <=", value, "rechargeToUser");
            return (Criteria) this;
        }

        public Criteria andRechargeToUserLike(String value) {
            addCriterion("recharge_to_user like", value, "rechargeToUser");
            return (Criteria) this;
        }

        public Criteria andRechargeToUserNotLike(String value) {
            addCriterion("recharge_to_user not like", value, "rechargeToUser");
            return (Criteria) this;
        }

        public Criteria andRechargeToUserIn(List<String> values) {
            addCriterion("recharge_to_user in", values, "rechargeToUser");
            return (Criteria) this;
        }

        public Criteria andRechargeToUserNotIn(List<String> values) {
            addCriterion("recharge_to_user not in", values, "rechargeToUser");
            return (Criteria) this;
        }

        public Criteria andRechargeToUserBetween(String value1, String value2) {
            addCriterion("recharge_to_user between", value1, value2, "rechargeToUser");
            return (Criteria) this;
        }

        public Criteria andRechargeToUserNotBetween(String value1, String value2) {
            addCriterion("recharge_to_user not between", value1, value2, "rechargeToUser");
            return (Criteria) this;
        }

        public Criteria andVipCodeIsNull() {
            addCriterion("vip_code is null");
            return (Criteria) this;
        }

        public Criteria andVipCodeIsNotNull() {
            addCriterion("vip_code is not null");
            return (Criteria) this;
        }

        public Criteria andVipCodeEqualTo(String value) {
            addCriterion("vip_code =", value, "vipCode");
            return (Criteria) this;
        }

        public Criteria andVipCodeNotEqualTo(String value) {
            addCriterion("vip_code <>", value, "vipCode");
            return (Criteria) this;
        }

        public Criteria andVipCodeGreaterThan(String value) {
            addCriterion("vip_code >", value, "vipCode");
            return (Criteria) this;
        }

        public Criteria andVipCodeGreaterThanOrEqualTo(String value) {
            addCriterion("vip_code >=", value, "vipCode");
            return (Criteria) this;
        }

        public Criteria andVipCodeLessThan(String value) {
            addCriterion("vip_code <", value, "vipCode");
            return (Criteria) this;
        }

        public Criteria andVipCodeLessThanOrEqualTo(String value) {
            addCriterion("vip_code <=", value, "vipCode");
            return (Criteria) this;
        }

        public Criteria andVipCodeLike(String value) {
            addCriterion("vip_code like", value, "vipCode");
            return (Criteria) this;
        }

        public Criteria andVipCodeNotLike(String value) {
            addCriterion("vip_code not like", value, "vipCode");
            return (Criteria) this;
        }

        public Criteria andVipCodeIn(List<String> values) {
            addCriterion("vip_code in", values, "vipCode");
            return (Criteria) this;
        }

        public Criteria andVipCodeNotIn(List<String> values) {
            addCriterion("vip_code not in", values, "vipCode");
            return (Criteria) this;
        }

        public Criteria andVipCodeBetween(String value1, String value2) {
            addCriterion("vip_code between", value1, value2, "vipCode");
            return (Criteria) this;
        }

        public Criteria andVipCodeNotBetween(String value1, String value2) {
            addCriterion("vip_code not between", value1, value2, "vipCode");
            return (Criteria) this;
        }

        public Criteria andRechargeMoneyCountIsNull() {
            addCriterion("recharge_money_count is null");
            return (Criteria) this;
        }

        public Criteria andRechargeMoneyCountIsNotNull() {
            addCriterion("recharge_money_count is not null");
            return (Criteria) this;
        }

        public Criteria andRechargeMoneyCountEqualTo(String value) {
            addCriterion("recharge_money_count =", value, "rechargeMoneyCount");
            return (Criteria) this;
        }

        public Criteria andRechargeMoneyCountNotEqualTo(String value) {
            addCriterion("recharge_money_count <>", value, "rechargeMoneyCount");
            return (Criteria) this;
        }

        public Criteria andRechargeMoneyCountGreaterThan(String value) {
            addCriterion("recharge_money_count >", value, "rechargeMoneyCount");
            return (Criteria) this;
        }

        public Criteria andRechargeMoneyCountGreaterThanOrEqualTo(String value) {
            addCriterion("recharge_money_count >=", value, "rechargeMoneyCount");
            return (Criteria) this;
        }

        public Criteria andRechargeMoneyCountLessThan(String value) {
            addCriterion("recharge_money_count <", value, "rechargeMoneyCount");
            return (Criteria) this;
        }

        public Criteria andRechargeMoneyCountLessThanOrEqualTo(String value) {
            addCriterion("recharge_money_count <=", value, "rechargeMoneyCount");
            return (Criteria) this;
        }

        public Criteria andRechargeMoneyCountLike(String value) {
            addCriterion("recharge_money_count like", value, "rechargeMoneyCount");
            return (Criteria) this;
        }

        public Criteria andRechargeMoneyCountNotLike(String value) {
            addCriterion("recharge_money_count not like", value, "rechargeMoneyCount");
            return (Criteria) this;
        }

        public Criteria andRechargeMoneyCountIn(List<String> values) {
            addCriterion("recharge_money_count in", values, "rechargeMoneyCount");
            return (Criteria) this;
        }

        public Criteria andRechargeMoneyCountNotIn(List<String> values) {
            addCriterion("recharge_money_count not in", values, "rechargeMoneyCount");
            return (Criteria) this;
        }

        public Criteria andRechargeMoneyCountBetween(String value1, String value2) {
            addCriterion("recharge_money_count between", value1, value2, "rechargeMoneyCount");
            return (Criteria) this;
        }

        public Criteria andRechargeMoneyCountNotBetween(String value1, String value2) {
            addCriterion("recharge_money_count not between", value1, value2, "rechargeMoneyCount");
            return (Criteria) this;
        }

        public Criteria andRechargeMonthsCountIsNull() {
            addCriterion("recharge_months_count is null");
            return (Criteria) this;
        }

        public Criteria andRechargeMonthsCountIsNotNull() {
            addCriterion("recharge_months_count is not null");
            return (Criteria) this;
        }

        public Criteria andRechargeMonthsCountEqualTo(String value) {
            addCriterion("recharge_months_count =", value, "rechargeMonthsCount");
            return (Criteria) this;
        }

        public Criteria andRechargeMonthsCountNotEqualTo(String value) {
            addCriterion("recharge_months_count <>", value, "rechargeMonthsCount");
            return (Criteria) this;
        }

        public Criteria andRechargeMonthsCountGreaterThan(String value) {
            addCriterion("recharge_months_count >", value, "rechargeMonthsCount");
            return (Criteria) this;
        }

        public Criteria andRechargeMonthsCountGreaterThanOrEqualTo(String value) {
            addCriterion("recharge_months_count >=", value, "rechargeMonthsCount");
            return (Criteria) this;
        }

        public Criteria andRechargeMonthsCountLessThan(String value) {
            addCriterion("recharge_months_count <", value, "rechargeMonthsCount");
            return (Criteria) this;
        }

        public Criteria andRechargeMonthsCountLessThanOrEqualTo(String value) {
            addCriterion("recharge_months_count <=", value, "rechargeMonthsCount");
            return (Criteria) this;
        }

        public Criteria andRechargeMonthsCountLike(String value) {
            addCriterion("recharge_months_count like", value, "rechargeMonthsCount");
            return (Criteria) this;
        }

        public Criteria andRechargeMonthsCountNotLike(String value) {
            addCriterion("recharge_months_count not like", value, "rechargeMonthsCount");
            return (Criteria) this;
        }

        public Criteria andRechargeMonthsCountIn(List<String> values) {
            addCriterion("recharge_months_count in", values, "rechargeMonthsCount");
            return (Criteria) this;
        }

        public Criteria andRechargeMonthsCountNotIn(List<String> values) {
            addCriterion("recharge_months_count not in", values, "rechargeMonthsCount");
            return (Criteria) this;
        }

        public Criteria andRechargeMonthsCountBetween(String value1, String value2) {
            addCriterion("recharge_months_count between", value1, value2, "rechargeMonthsCount");
            return (Criteria) this;
        }

        public Criteria andRechargeMonthsCountNotBetween(String value1, String value2) {
            addCriterion("recharge_months_count not between", value1, value2, "rechargeMonthsCount");
            return (Criteria) this;
        }

        public Criteria andRechargeDateIsNull() {
            addCriterion("recharge_date is null");
            return (Criteria) this;
        }

        public Criteria andRechargeDateIsNotNull() {
            addCriterion("recharge_date is not null");
            return (Criteria) this;
        }

        public Criteria andRechargeDateEqualTo(String value) {
            addCriterion("recharge_date =", value, "rechargeDate");
            return (Criteria) this;
        }

        public Criteria andRechargeDateNotEqualTo(String value) {
            addCriterion("recharge_date <>", value, "rechargeDate");
            return (Criteria) this;
        }

        public Criteria andRechargeDateGreaterThan(String value) {
            addCriterion("recharge_date >", value, "rechargeDate");
            return (Criteria) this;
        }

        public Criteria andRechargeDateGreaterThanOrEqualTo(String value) {
            addCriterion("recharge_date >=", value, "rechargeDate");
            return (Criteria) this;
        }

        public Criteria andRechargeDateLessThan(String value) {
            addCriterion("recharge_date <", value, "rechargeDate");
            return (Criteria) this;
        }

        public Criteria andRechargeDateLessThanOrEqualTo(String value) {
            addCriterion("recharge_date <=", value, "rechargeDate");
            return (Criteria) this;
        }

        public Criteria andRechargeDateLike(String value) {
            addCriterion("recharge_date like", value, "rechargeDate");
            return (Criteria) this;
        }

        public Criteria andRechargeDateNotLike(String value) {
            addCriterion("recharge_date not like", value, "rechargeDate");
            return (Criteria) this;
        }

        public Criteria andRechargeDateIn(List<String> values) {
            addCriterion("recharge_date in", values, "rechargeDate");
            return (Criteria) this;
        }

        public Criteria andRechargeDateNotIn(List<String> values) {
            addCriterion("recharge_date not in", values, "rechargeDate");
            return (Criteria) this;
        }

        public Criteria andRechargeDateBetween(String value1, String value2) {
            addCriterion("recharge_date between", value1, value2, "rechargeDate");
            return (Criteria) this;
        }

        public Criteria andRechargeDateNotBetween(String value1, String value2) {
            addCriterion("recharge_date not between", value1, value2, "rechargeDate");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table vip_recharge_records
     *
     * @mbggenerated do_not_delete_during_merge Tue Sep 06 20:57:55 CST 2016
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }

        public Criteria andRecordsIdLikeInsensitive(String value) {
            addCriterion("upper(records_id) like", value.toUpperCase(), "recordsId");
            return this;
        }

        public Criteria andUserIdLikeInsensitive(String value) {
            addCriterion("upper(user_id) like", value.toUpperCase(), "userId");
            return this;
        }

        public Criteria andRechargeToUserLikeInsensitive(String value) {
            addCriterion("upper(recharge_to_user) like", value.toUpperCase(), "rechargeToUser");
            return this;
        }

        public Criteria andVipCodeLikeInsensitive(String value) {
            addCriterion("upper(vip_code) like", value.toUpperCase(), "vipCode");
            return this;
        }

        public Criteria andRechargeMoneyCountLikeInsensitive(String value) {
            addCriterion("upper(recharge_money_count) like", value.toUpperCase(), "rechargeMoneyCount");
            return this;
        }

        public Criteria andRechargeMonthsCountLikeInsensitive(String value) {
            addCriterion("upper(recharge_months_count) like", value.toUpperCase(), "rechargeMonthsCount");
            return this;
        }

        public Criteria andRechargeDateLikeInsensitive(String value) {
            addCriterion("upper(recharge_date) like", value.toUpperCase(), "rechargeDate");
            return this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table vip_recharge_records
     *
     * @mbggenerated Tue Sep 06 20:57:55 CST 2016
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}