package com.ddas.sns.vip.domain;

import java.io.Serializable;

public class VipRechargeRecord implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vip_recharge_records.records_id
     *
     * @mbggenerated Tue Sep 06 20:57:55 CST 2016
     */
    private String recordsId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vip_recharge_records.user_id
     *
     * @mbggenerated Tue Sep 06 20:57:55 CST 2016
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vip_recharge_records.recharge_to_user
     *
     * @mbggenerated Tue Sep 06 20:57:55 CST 2016
     */
    private String rechargeToUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vip_recharge_records.vip_code
     *
     * @mbggenerated Tue Sep 06 20:57:55 CST 2016
     */
    private String vipCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vip_recharge_records.recharge_money_count
     *
     * @mbggenerated Tue Sep 06 20:57:55 CST 2016
     */
    private String rechargeMoneyCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vip_recharge_records.recharge_months_count
     *
     * @mbggenerated Tue Sep 06 20:57:55 CST 2016
     */
    private String rechargeMonthsCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vip_recharge_records.recharge_date
     *
     * @mbggenerated Tue Sep 06 20:57:55 CST 2016
     */
    private String rechargeDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table vip_recharge_records
     *
     * @mbggenerated Tue Sep 06 20:57:55 CST 2016
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vip_recharge_records.records_id
     *
     * @return the value of vip_recharge_records.records_id
     *
     * @mbggenerated Tue Sep 06 20:57:55 CST 2016
     */
    public String getRecordsId() {
        return recordsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vip_recharge_records.records_id
     *
     * @param recordsId the value for vip_recharge_records.records_id
     *
     * @mbggenerated Tue Sep 06 20:57:55 CST 2016
     */
    public void setRecordsId(String recordsId) {
        this.recordsId = recordsId == null ? null : recordsId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vip_recharge_records.user_id
     *
     * @return the value of vip_recharge_records.user_id
     *
     * @mbggenerated Tue Sep 06 20:57:55 CST 2016
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vip_recharge_records.user_id
     *
     * @param userId the value for vip_recharge_records.user_id
     *
     * @mbggenerated Tue Sep 06 20:57:55 CST 2016
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vip_recharge_records.recharge_to_user
     *
     * @return the value of vip_recharge_records.recharge_to_user
     *
     * @mbggenerated Tue Sep 06 20:57:55 CST 2016
     */
    public String getRechargeToUser() {
        return rechargeToUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vip_recharge_records.recharge_to_user
     *
     * @param rechargeToUser the value for vip_recharge_records.recharge_to_user
     *
     * @mbggenerated Tue Sep 06 20:57:55 CST 2016
     */
    public void setRechargeToUser(String rechargeToUser) {
        this.rechargeToUser = rechargeToUser == null ? null : rechargeToUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vip_recharge_records.vip_code
     *
     * @return the value of vip_recharge_records.vip_code
     *
     * @mbggenerated Tue Sep 06 20:57:55 CST 2016
     */
    public String getVipCode() {
        return vipCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vip_recharge_records.vip_code
     *
     * @param vipCode the value for vip_recharge_records.vip_code
     *
     * @mbggenerated Tue Sep 06 20:57:55 CST 2016
     */
    public void setVipCode(String vipCode) {
        this.vipCode = vipCode == null ? null : vipCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vip_recharge_records.recharge_money_count
     *
     * @return the value of vip_recharge_records.recharge_money_count
     *
     * @mbggenerated Tue Sep 06 20:57:55 CST 2016
     */
    public String getRechargeMoneyCount() {
        return rechargeMoneyCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vip_recharge_records.recharge_money_count
     *
     * @param rechargeMoneyCount the value for vip_recharge_records.recharge_money_count
     *
     * @mbggenerated Tue Sep 06 20:57:55 CST 2016
     */
    public void setRechargeMoneyCount(String rechargeMoneyCount) {
        this.rechargeMoneyCount = rechargeMoneyCount == null ? null : rechargeMoneyCount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vip_recharge_records.recharge_months_count
     *
     * @return the value of vip_recharge_records.recharge_months_count
     *
     * @mbggenerated Tue Sep 06 20:57:55 CST 2016
     */
    public String getRechargeMonthsCount() {
        return rechargeMonthsCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vip_recharge_records.recharge_months_count
     *
     * @param rechargeMonthsCount the value for vip_recharge_records.recharge_months_count
     *
     * @mbggenerated Tue Sep 06 20:57:55 CST 2016
     */
    public void setRechargeMonthsCount(String rechargeMonthsCount) {
        this.rechargeMonthsCount = rechargeMonthsCount == null ? null : rechargeMonthsCount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vip_recharge_records.recharge_date
     *
     * @return the value of vip_recharge_records.recharge_date
     *
     * @mbggenerated Tue Sep 06 20:57:55 CST 2016
     */
    public String getRechargeDate() {
        return rechargeDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vip_recharge_records.recharge_date
     *
     * @param rechargeDate the value for vip_recharge_records.recharge_date
     *
     * @mbggenerated Tue Sep 06 20:57:55 CST 2016
     */
    public void setRechargeDate(String rechargeDate) {
        this.rechargeDate = rechargeDate == null ? null : rechargeDate.trim();
    }
}