package com.ddas.sns.vip.domain;

import java.io.Serializable;

public class VipTypes implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vip_types.vip_id
     *
     * @mbggenerated Fri Aug 12 22:17:41 CST 2016
     */
    private String vipId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vip_types.vip_type_code
     *
     * @mbggenerated Fri Aug 12 22:17:41 CST 2016
     */
    private String vipTypeCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vip_types.describ
     *
     * @mbggenerated Fri Aug 12 22:17:41 CST 2016
     */
    private String describ;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table vip_types
     *
     * @mbggenerated Fri Aug 12 22:17:41 CST 2016
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vip_types.vip_id
     *
     * @return the value of vip_types.vip_id
     *
     * @mbggenerated Fri Aug 12 22:17:41 CST 2016
     */
    public String getVipId() {
        return vipId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vip_types.vip_id
     *
     * @param vipId the value for vip_types.vip_id
     *
     * @mbggenerated Fri Aug 12 22:17:41 CST 2016
     */
    public void setVipId(String vipId) {
        this.vipId = vipId == null ? null : vipId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vip_types.vip_type_code
     *
     * @return the value of vip_types.vip_type_code
     *
     * @mbggenerated Fri Aug 12 22:17:41 CST 2016
     */
    public String getVipTypeCode() {
        return vipTypeCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vip_types.vip_type_code
     *
     * @param vipTypeCode the value for vip_types.vip_type_code
     *
     * @mbggenerated Fri Aug 12 22:17:41 CST 2016
     */
    public void setVipTypeCode(String vipTypeCode) {
        this.vipTypeCode = vipTypeCode == null ? null : vipTypeCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vip_types.describ
     *
     * @return the value of vip_types.describ
     *
     * @mbggenerated Fri Aug 12 22:17:41 CST 2016
     */
    public String getDescrib() {
        return describ;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vip_types.describ
     *
     * @param describ the value for vip_types.describ
     *
     * @mbggenerated Fri Aug 12 22:17:41 CST 2016
     */
    public void setDescrib(String describ) {
        this.describ = describ == null ? null : describ.trim();
    }
}